extends Node

var template = {
	is_person = true,
	is_hirable = false, #allows character to be hired from its tab
	hire_scene = '',
	unique = null,
	
	icon_image = '', #images.portraits[images.portraits.keys()[randi()%images.portraits.size()]].load_path
	dynamic_portrait = true,
	portrait_update = true,
	
	body_image = 'default',
	name = '',
	surname = '',
	nickname = '',
	bonus_description = '',
	race = 'Human',
	racegroup = 'humanoid',
	age = '',
	sex = 'male',
#	slave_class = 'slave1',
	slave_class = '',
	personality = '',
	personality_bold = 0,
	personality_kind = 0,
	old_personality = 'kind',
#	personaltiy_values = [0,0],
	
	trainee_amount = 0,
	training_loyalty = 0,
	training_spirit = 0,
	
	lust = 0.0,
	lustmax = 50,
	lusttick = variables.basic_lust_per_tick,
	hpmax = 100,
	mpmax = 50,
	upgrade_points_total = 0, #does not matter
#	exp_mod = 1,
	hp_reg_mod = 1.0,
	mp_reg_mod = 1.0,
	hp_reg_add = 0.0,
	mp_reg_add = 0.0,
	exp_gain_mod = 1.0,
	manacost_mod = 1.0,
	damage_reduction = 0,
	
	magic_find = 0,
	#enemy combat/reward data
	xpreward = 10,
	loottable = "",
	productivity = 100.0,
	#productivity mods
	mod_build = 1.0,
	mod_collect = 1.0,
	mod_hunt = 1.0,
	mod_fish = 1.0,
	mod_cook = 1.0,
	mod_smith = 1.0,
	mod_tailor = 1.0,
	mod_alchemy = 1.0,
	mod_farm = 1.0,
	mod_pros = 1.0,
	mod_service = 1.0,
	mod_waitress = 1.0,
	mod_hostess = 1.0,
	mod_dancer = 1.0,
	mod_strip = 1.0,
	base_task_crit_chance = 0.0,

	atk = variables.basic_character_atk,
	matk = variables.basic_character_matk,
	
	damagetype = 'normal',
	
	hitrate = 100,
	evasion = 0,
	resists = {},
	resist_damage = {},
	status_resists = {},
	damage_mods = {},
	burn_mod = 1.0,
	burn_damage = 0.07,
	darkflame_damage = 0.1,
	poison_mod = 1.0,
	poison_damage = 0.1,
	bleed_mod = 1.0,
	bleed_damage = 0.1,
	armor = 0,
	mdef = 0,
	armorpenetration = 0,
	critchance = 10,
	critmod = 1.5,
	speed = 30,
	shield = 0,
	#enemy AI. do not forget to set to null at end of combat
	#progress stats
	#maybe bonus stats are to remove
	physics = 0.0,
	physics_bonus = 0.0,
	physics_cap = 100,
	wits = 0.0,
	wits_bonus = 0.0,
	wits_cap = 100,
	sexuals = 0.0,
	sexuals_bonus = 0.0,
	charm = 0.0,
	charm_bonus = 0.0,
	charm_cap = 100,
	#constant stats
	physics_factor = 1,
	magic_factor = 1,
	tame_factor = 1,
	timid_factor = 1, #authority factor
	growth_factor = 1,
	charm_factor = 1,
	wits_factor = 1,
	sexuals_factor = 1,
#	#food
	food_consumption = 1,

	piercing = {earlobes = null, eyebrow = null, nose = null, lips = null, tongue = null, navel = null, nipples = null, clit = null, labia = null, penis = null},
	tattoo = {chest = 'none', face = 'none', ass = 'none', arms = 'none', legs = 'none', waist = 'none'},
	tattooshow = {chest = true, face = true, ass = true, arms = true, legs = true, waist = true},
	mods = {},
	#appearance
	skin = 'fair',
	height = 'average',
	hair_length = 'ear',
	hair_color = 'black',
	hair_style = 'straight',
	ears = 'normal',
	eye_color = 'brown',
	eye_shape = 'normal',
	horns = '',
	wings = '',
	tail = '',
	arms = 'normal',
	legs = 'normal',
	body_lower = '',
	body_shape = 'humanoid',
	skin_coverage = '',
	fur = '',
	facial_hair = '',
	#new ones
	chin = 'default',
	eye_tex = 'eyes1',
	eyeshape = 'face1',
	nose = 'default',
	eyebrows = 'style1',
	lips = 'style1',
	beard = 'no',
	moustache = 'no',

	
	armor_color = {
		base = 'default',
		lower = 'default',
		collar = 'default',
		weapon = 'default',
		underwear = 'default',
		},
	
	#new skin, empty values SHOULD be set in remade char generating function or kept empty to indicate derivative nature
	body_color_skin = '', 
	body_color_wings = '', 
	body_color_tail = '', 
	body_color_horns = '', 
	body_color_animal = '', 
	#new hair, empty values SHOULD be set in remade char generating function or kept empty to indicate derivative nature
	hair_base = '', 
	hair_assist = '', 
	hair_back = '', 
	hair_fringe = '', 
	hair_base_color_1 = '', 
	hair_fringe_color_1 = '', 
	hair_back_color_1 = '', 
	hair_assist_color_1 = '', 
	hair_base_color_2 = '', 
	hair_fringe_color_2 = '', 
	hair_back_color_2 = '', 
	hair_assist_color_2 = '', 
	hair_base_length = '', 
	hair_fringe_length = '', 
	hair_back_length = '', 
	hair_assist_length = '',
	hair_facial_color = "",
	
	#genitals
	penis_size = '',
	penis_type = 'human',
	balls_size = '',
	tits_size = '',
	vagina = '',
	ass_size = '',
	has_pussy = false,
	multiple_tits = 0,
	multiple_tits_developed = false,
	has_womb = false,
	pregnancy = {"fertility": 0, "duration": 0, "baby": null },
	lactation = false,

	was_proposed = false,
	had_cons_sex_with_mc = false,
	had_forced_sex_with_mc = false,
	agreed_to_marry = false,

	penis_virgin = true,
	vaginal_virgin = true,
	anal_virgin = true,
	mouth_virgin = true,
	
	penis_virgin_lost = {source = null},
	vaginal_virgin_lost = {source = null},
	anal_virgin_lost = {source = null},
	mouth_virgin_lost = {source = null},
	
	#communications
	relatives = {},
	sexexp = {partners = {}, watchers = {}, actions = {}, seenactions = {}, orgasms = {}, orgasmpartners = {}},
	sex_skills = {petting = 0, penetration = 0, pussy = 0, oral = 0, anal = 0, tail = 0},
	
	
	consent = 0,
	relations = {},
	metrics = {ownership = 0, sex = 0, dates = 0, partners = [], randompartners = 0, win = 0, kills = 0, goldearn = 0, foodearn = 0, materialearn = 0, serviceperformed = 0, socskillused = 0, spellused = 0, healused = 0, foodeaten = 0, birth = 0, pregnancy = 0, impregnation = 0},
	lastsexday = 0,

	asser = 0,

	masternoun = tr('PROFMASTER'),
	
	#challenge charages
	chg_strength = 0,
	chg_strength_max = 0,
	chg_dexterity = 0,
	chg_dexterity_max = 0,
	chg_wisdom = 0,
	chg_wisdom_max = 0,
	chg_persuasion = 0,
	chg_persuasion_max = 0,
	
	
	
}
