        DATETOOLTIP = "Dates restantes cette semaine. Augmente avec le facteur de charme du maître et se réinitialise au début de la semaine",
        SEXTOOLTIP = "Interactions sexuelles laissées cette semaine. Augmente avec le facteur sexuel du maître et se réinitialise au début de la semaine",
        DATETOOLTIPSHORT = "Character can be dated today",
        SEXTOOLTIPSHORT = "Character can be assigned to sexual interaction today",
        SEXSELECT_CATEGORY_ALL = "Show all characters",
        SEXSELECT_CATEGORY_MALE = "Show male characters",
        SEXSELECT_CATEGORY_FEMALE = "Show female characters",
        SEXSELECT_CATEGORY_FUTA = "Show futanari characters",
        SEXSELECT_INTERACTIONS = "Sex interactions: %s/%s",
        SEXSELECT_INTERACTIONS_UNLIMITED = "Sex interactions: Unlimited",
        SEXSELECT_MISSING_TRAITS = "This character lacks necessary sexual traits and will resist at the start of the scene.",

        TOOLTIPLOYALTYOBEDIENCE = "Des points de loyauté sont gagnés à chaque tour en fonction du facteur d'apprivoisement. Vous pouvez débloquer de nouvelles actions et de nouveaux passifs grâce à ces points. La perte d'obéissance est basée sur le facteur de timidité et l'entraînement du personnage. Si l'obéissance tombe à 0, le personnage tentera de s'échapper. Déverrouillez de nouvelles options et utilisez l'équipement adéquat pour réduire la perte d'obéissance et la rendre plus facile à gérer. ",
