extends Node

var stats_to_look = ['sex', 'race', 'horns', 'ears']

var texture_sets = {
	default_male = [
		{type = 'texture', node = 'male_pose/HumanF1/Spine/ShoulderR/ArmR/HandR/HandR_tex', texture = "res://Character_generator/images/01_body_nude_male/HandR1_m.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/ShoulderR/ArmR_tex', texture = "res://Character_generator/images/01_body_nude_male/ArmR1_m.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/ShoulderR/ShoulderR_tex', texture = "res://Character_generator/images/01_body_nude_male/ShoulderR_m.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/ShoulderL/ArmL/HandL/HandL_tex', texture = "res://Character_generator/images/01_body_nude_male/HandL1_m.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/ShoulderL/ArmL/ArmL_tex', texture = "res://Character_generator/images/01_body_nude_male/ArmL1_m.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/ShoulderL/ShoulderL_tex', texture = "res://Character_generator/images/01_body_nude_male/ShoulderL_m.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/Torso_tex2', texture = "res://Character_generator/images/01_body_nude_male/torso_m.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/Taz/LegL/LegL_tex', texture = "res://Character_generator/images/01_body_nude_male/LegL_m.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/Taz/LegR/LegR_tex', texture = "res://Character_generator/images/01_body_nude_male/LegR_m.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/Taz/Taz_tex', texture = "res://Character_generator/images/01_body_nude_male/taz_m.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/Taz/Dick/Penis_tex', texture = "res://Character_generator/images/13_dicks/Dick_human_up.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/Taz/Dick/Testicles_tex', texture = "res://Character_generator/images/13_dicks/Testicle_human.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/Tits/Tits_mesh', texture = "res://Character_generator/images/00_body_nude/tits_normal.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Head_tex', texture = "res://Character_generator/images/01_heads/head_skull.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Chin_tex', texture = "res://Character_generator/images/01_heads/head_chin_male.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Face/Face_tex', texture = "res://Character_generator/images/02_faces/face_m4.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Face/Nose_tex', texture = "res://Character_generator/images/03_noses/nose_default.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Ears_humanoid_tex', texture = "res://Character_generator/images/03_ears/ears_human.png" },
	],
	beastkin_male = [
		{type = 'texture', node = 'male_pose/HumanF1/Spine/ShoulderR/ArmR/HandR/HandR_tex', texture = "res://Character_generator/images/15_beastkin_body_nude/beastkin_HandR1.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/ShoulderR/ArmR_tex', texture = "res://Character_generator/images/15_beastkin_body_nude/beastkin_ArmR1.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/ShoulderR/ShoulderR_tex', texture = "res://Character_generator/images/15_beastkin_body_nude/beastkin_ShoulderR.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/ShoulderL/ArmL/HandL/HandL_tex', texture = "res://Character_generator/images/15_beastkin_body_nude/beastkin_HandL1.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/ShoulderL/ArmL/ArmL_tex', texture = "res://Character_generator/images/15_beastkin_body_nude/beastkin_ArmL1.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/ShoulderL/ShoulderL_tex', texture = "res://Character_generator/images/15_beastkin_body_nude/beastkin_ShoulderL.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/Torso_tex2', texture = "res://Character_generator/images/15_beastkin_body_nude/beastkin_torso1.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/Taz/LegL/LegL_tex', texture = "res://Character_generator/images/15_beastkin_body_nude/beastkin_LegL1.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/Taz/LegR/LegR_tex', texture = "res://Character_generator/images/15_beastkin_body_nude/beastkin_LegR1.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/Taz/Taz_tex', texture = "res://Character_generator/images/15_beastkin_body_nude/beastkin_taz1.png"}, #or 2
		{type = 'texture', node = 'male_pose/HumanF1/Spine/Taz/Dick/Penis_tex', texture = "res://Character_generator/images/13_dicks/Dick_furry_up.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/Taz/Dick/Testicles_tex', texture = "res://Character_generator/images/13_dicks/Testicle_furry.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/Tits/Tits_mesh', texture = "res://Character_generator/images/15_beastkin_body_nude/beastkin_tits_normal.png"},
		{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Face/Face_tex', texture = "res://Character_generator/images/17_beastkin_faces/beastkin_face_m4.png"},
	],
	default_female = [
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/ShoulderR/ArmR/HandR/HandR_tex', texture = "res://Character_generator/images/01_body_nude_male/HandR1_m.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/ShoulderR/ArmR_tex', texture = "res://Character_generator/images/00_body_nude/ArmR1_m.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/ShoulderR/ShoulderR_tex', texture = "res://Character_generator/images/00_body_nude/ShoulderR_m.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/ShoulderL/ArmL/HandL/HandL_tex', texture = "res://Character_generator/images/00_body_nude/HandL1_m.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/ShoulderL/ArmL/ArmL_tex', texture = "res://Character_generator/images/00_body_nude/ArmL1_m.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/ShoulderL/ShoulderL_tex', texture = "res://Character_generator/images/00_body_nude/ShoulderL_m.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/Torso_tex2', texture = "res://Character_generator/images/00_body_nude/torso_m.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/Taz/LegL/LegL_tex', texture = "res://Character_generator/images/00_body_nude/LegL_m.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/Taz/LegR/LegR_tex', texture = "res://Character_generator/images/00_body_nude/LegR_m.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/Taz/Taz_tex', texture = "res://Character_generator/images/00_body_nude/taz_m.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/Taz/Dick/Penis_tex', texture = "res://Character_generator/images/13_dicks/Dick_human_up.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/Taz/Dick/Testicles_tex', texture = "res://Character_generator/images/13_dicks/Testicle_human.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/Tits/Tits_mesh', texture = "res://Character_generator/images/00_body_nude/tits_normal.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Head_tex', texture = "res://Character_generator/images/01_heads/head_skull.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Chin_tex', texture = "res://Character_generator/images/01_heads/head_chin_default.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Face/Face_tex', texture = "res://Character_generator/images/02_faces/face1.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Face/Nose_tex', texture = "res://Character_generator/images/03_noses/nose_default.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Ears_humanoid_tex', texture = "res://Character_generator/images/03_ears/ears_human.png" },
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/Belly_default_tex', texture = "res://Character_generator/images/00_body_nude/default_belly.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/Pregnancy/Belly_pregnancy_tex', texture = "res://Character_generator/images/00_body_nude/pregnancy_belly_mid.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/Pregnancy/Belly_pregnancy_tex2', texture = "res://Character_generator/images/00_body_nude/pregnancy_belly_big.png"},
	],
	beastkin_female = [
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/ShoulderR/ArmR/HandR/HandR_tex', texture = "res://Character_generator/images/15_beastkin_body_nude/beastkin_HandR1.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/ShoulderR/ArmR_tex', texture = "res://Character_generator/images/15_beastkin_body_nude/beastkin_ArmR1.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/ShoulderR/ShoulderR_tex', texture = "res://Character_generator/images/15_beastkin_body_nude/beastkin_ShoulderR.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/ShoulderL/ArmL/HandL/HandL_tex', texture = "res://Character_generator/images/15_beastkin_body_nude/beastkin_HandL1.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/ShoulderL/ArmL/ArmL_tex', texture = "res://Character_generator/images/15_beastkin_body_nude/beastkin_ArmL1.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/ShoulderL/ShoulderL_tex', texture = "res://Character_generator/images/15_beastkin_body_nude/beastkin_ShoulderL.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/Torso_tex2', texture = "res://Character_generator/images/15_beastkin_body_nude/beastkin_torso1.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/Taz/LegL/LegL_tex', texture = "res://Character_generator/images/15_beastkin_body_nude/beastkin_LegL1.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/Taz/LegR/LegR_tex', texture = "res://Character_generator/images/15_beastkin_body_nude/beastkin_LegR1.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/Taz/Taz_tex', texture = "res://Character_generator/images/15_beastkin_body_nude/beastkin_taz1.png"}, #or 2
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/Taz/Dick/Penis_tex', texture = "res://Character_generator/images/13_dicks/Dick_furry_up.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/Taz/Dick/Testicles_tex', texture = "res://Character_generator/images/13_dicks/Testicle_furry.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/Tits/Tits_mesh', texture = "res://Character_generator/images/15_beastkin_body_nude/beastkin_tits_normal.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Face/Face_tex', texture = "res://Character_generator/images/17_beastkin_faces/beastkin_face4.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/Belly_default_tex', texture = "res://Character_generator/images/15_beastkin_body_nude/beastkin_belly1.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/Pregnancy/Belly_pregnancy_tex', texture = "res://Character_generator/images/15_beastkin_body_nude/beastkin_pregnancy_belly_mid1.png"},
		{type = 'texture', node = 'Female_pose/HumanF1/Spine/Pregnancy/Belly_pregnancy_tex2', texture = "res://Character_generator/images/15_beastkin_body_nude/beastkin_pregnancy_belly_big1.png"},
	],
}

var transforms = {
	cloth = {
		true:[
			{type = 'node_group_attr', group = 'cloth', attr = 'visible', value = true},
		],
		false:[
			{type = 'node_group_attr', group = 'cloth', attr = 'visible', value = false},
		]
	},
	
	sex = {
		male = [
			{type = 'node_group_select', group = 'sex', select = 'male_pose'},
		],
		female = [
			{type = 'node_group_select', group = 'sex', select = 'female_pose'},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Taz/Dick', attr = 'visible', value = false}
		],
		futa = [
			{type = 'node_group_select', group = 'sex', select = 'female_pose'},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Taz/Dick', attr = 'visible', value = true}
		],
	},
	
	race = {
		Human = [
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
#			{type = 'import_recolor_group', group = 'skin_main', material = "remove_racial_masks", ids = []}, non-existed material
			{type = 'texture_set', set = 'default_male'},
			{type = 'texture_set', set = 'default_female'},
		],
		Elf = [
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
#			{type = 'import_recolor_group', group = 'skin_main', material = "remove_racial_masks", ids = []}, non-existed material
			{type = 'texture_set', set = 'default_male'},
			{type = 'texture_set', set = 'default_female'},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Ears_humanoid_tex', texture = "res://Character_generator/images/03_ears/ears_elven.png" },
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Ears_humanoid_tex', texture = "res://Character_generator/images/03_ears/ears_elven.png" },
		],
		TribalElf = [
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
#			{type = 'import_recolor_group', group = 'skin_main', material = "remove_racial_masks", ids = []}, non-existed material
			{type = 'texture_set', set = 'default_male'},
			{type = 'texture_set', set = 'default_female'},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Ears_humanoid_tex', texture = "res://Character_generator/images/03_ears/ears_elven.png" },
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Ears_humanoid_tex', texture = "res://Character_generator/images/03_ears/ears_elven.png" },
		],
		DarkElf = [
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
#			{type = 'import_recolor_group', group = 'skin_main', material = "remove_racial_masks", ids = []}, non-existed material
			{type = 'texture_set', set = 'default_male'},
			{type = 'texture_set', set = 'default_female'},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Ears_humanoid_tex', texture = "res://Character_generator/images/03_ears/ears_elven.png" },
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Ears_humanoid_tex', texture = "res://Character_generator/images/03_ears/ears_elven.png" },
		],
		Orc = [
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
#			{type = 'import_recolor_group', group = 'skin_main', material = "remove_racial_masks", ids = []}, non-existed material
			{type = 'texture_set', set = 'default_male'},
			{type = 'texture_set', set = 'default_female'},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Ears_humanoid_tex', texture = "res://Character_generator/images/03_ears/ears_orc.png" },
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Ears_humanoid_tex', texture = "res://Character_generator/images/03_ears/ears_orc.png" },
		],
		Goblin = [
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
#			{type = 'import_recolor_group', group = 'skin_main', material = "remove_racial_masks", ids = []}, non-existed material
			{type = 'texture_set', set = 'default_male'},
			{type = 'texture_set', set = 'default_female'},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Ears_humanoid_tex', texture = "res://Character_generator/images/03_ears/ears_orc.png" },
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Ears_humanoid_tex', texture = "res://Character_generator/images/03_ears/ears_orc.png" },
		],
		Kobold = [ #horns are set in horns
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
			{type = 'node_group_attr', group = 'kobold', attr = 'visible', value = true},
#			{type = 'import_recolor_group', group = 'skin_main', material = "scale_mask", ids = []}, non-existed material
			{type = 'texture_set', set = 'default_male'},
			{type = 'texture_set', set = 'default_female'},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Tail_tex', texture = "res://Character_generator/images/06_tails/dragon_tail.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Face/Nose_tex', texture = "res://Character_generator/images/03_noses/nose_kobold.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Tail_tex', texture = "res://Character_generator/images/06_tails/dragon_tail.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Face/Nose_tex', texture = "res://Character_generator/images/03_noses/nose_kobold.png"},
		],
		Gnome = [
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
#			{type = 'import_recolor_group', group = 'skin_main', material = "remove_racial_masks", ids = []}, non-existed material
			{type = 'texture_set', set = 'default_male'},
			{type = 'texture_set', set = 'default_female'},
		],
		Dwarf = [
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
#			{type = 'import_recolor_group', group = 'skin_main', material = "remove_racial_masks", ids = []}, non-existed material
			{type = 'texture_set', set = 'default_male'},
			{type = 'texture_set', set = 'default_female'},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Face/Nose_tex', texture = "res://Character_generator/images/03_noses/nose_dwarf.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Face/Nose_tex', texture = "res://Character_generator/images/03_noses/nose_dwarf.png"},
		],
		Fairy = [
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
			{type = 'node_group_attr', group = 'fairy', attr = 'visible', value = true},
#			{type = 'import_recolor_group', group = 'skin_main', material = "remove_racial_masks", ids = []}, non-existed material
			{type = 'texture_set', set = 'default_male'},
			{type = 'texture_set', set = 'default_female'},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Ears_humanoid_tex', texture = "res://Character_generator/images/03_ears/ears_elven.png" },
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Wings_tex', texture = "res://Character_generator/images/09_wings/Wings_fairy.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Ears_humanoid_tex', texture = "res://Character_generator/images/03_ears/ears_elven.png" },
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Wings_tex', texture = "res://Character_generator/images/09_wings/Wings_fairy.png"},
		],
		Dryad = [
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
			{type = 'node_group_attr', group = 'dryad', attr = 'visible', value = true},
#			{type = 'import_recolor_group', group = 'skin_main', material = "bark_mask", ids = []}, non-existed material
			{type = 'texture_set', set = 'default_male'},
			{type = 'texture_set', set = 'default_female'},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Ears_humanoid_tex', texture = "res://Character_generator/images/03_ears/ears_elven.png" },
			{type = 'texture', node = 'male_pose/HumanF1/Spine/ShoulderR/ShoulderR_races', texture = "res://Character_generator/images/20_dryad/dryad_shoulderR.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/ShoulderL/ShoulderL_races', texture = "res://Character_generator/images/20_dryad/dryad_shoulderL.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Torso_races', texture = "res://Character_generator/images/20_dryad/dryad_body.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Taz/LegR/LegR_races', texture = "res://Character_generator/images/20_dryad/dryad_legR.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Ears_humanoid_tex', texture = "res://Character_generator/images/03_ears/ears_elven.png" },
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/ShoulderR/ShoulderR_races', texture = "res://Character_generator/images/20_dryad/dryad_shoulderR.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/ShoulderL/ShoulderL_races', texture = "res://Character_generator/images/20_dryad/dryad_shoulderL.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Torso_races', texture = "res://Character_generator/images/20_dryad/dryad_body.png"}, # or not
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Taz/LegR/LegR_races', texture = "res://Character_generator/images/20_dryad/dryad_legR.png"},
		],
		Demon = [ #horns are set in horns
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
			{type = 'node_group_attr', group = 'demon', attr = 'visible', value = true},
#			{type = 'import_recolor_group', group = 'skin_main', material = "remove_racial_masks", ids = []}, non-existed material
			{type = 'texture_set', set = 'default_male'},
			{type = 'texture_set', set = 'default_female'},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Ears_humanoid_tex', texture = "res://Character_generator/images/03_ears/ears_elven.png" }, #no demon ears
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Tail_tex', texture = "res://Character_generator/images/07_tails/tail_demon.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Wings_tex', texture = "res://Character_generator/images/09_wings/wings_demon.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Ears_humanoid_tex', texture = "res://Character_generator/images/03_ears/ears_elven.png" }, #no demon ears
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Tail_tex', texture = "res://Character_generator/images/07_tails/tail_demon.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Wings_tex', texture = "res://Character_generator/images/09_wings/wings_demon.png"},
		],
		Seraph = [
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
			{type = 'node_group_attr', group = 'fairy', attr = 'visible', value = true}, #the same wings only
#			{type = 'import_recolor_group', group = 'skin_main', material = "remove_racial_masks", ids = []}, non-existed material
			{type = 'texture_set', set = 'default_male'},
			{type = 'texture_set', set = 'default_female'},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Wings_tex', texture = "res://Character_generator/images/09_wings/Wings_seraph.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Wings_tex', texture = "res://Character_generator/images/09_wings/Wings_seraph.png"},
		],
		Dragonkin = [ #horns are set in horns
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
			{type = 'node_group_attr', group = 'demon', attr = 'visible', value = true}, #the same tail + horns + wings
#			{type = 'import_recolor_group', group = 'skin_main', material = "scale_mask", ids = []}, non-existed material
			{type = 'texture_set', set = 'default_male'},
			{type = 'texture_set', set = 'default_female'},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Ears_humanoid_tex', texture = "res://Character_generator/images/03_ears/ears_elven.png" }, 
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Tail_tex', texture = "res://Character_generator/images/07_tails/tail_dragon.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Wings_tex', texture = "res://Character_generator/images/09_wings/Wings_dragon.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Ears_humanoid_tex', texture = "res://Character_generator/images/03_ears/ears_elven.png" }, 
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Tail_tex', texture = "res://Character_generator/images/07_tails/tail_dragon.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Wings_tex', texture = "res://Character_generator/images/09_wings/Wings_dragon.png"},
		],
		Centaur = [
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
			{type = 'node_group_attr', group = 'l_body', attr = 'visible', value = false},
			{type = 'node_group_attr', group = 'l_body_alter', attr = 'visible', value = true},
#			{type = 'import_recolor_group', group = 'skin_main', material = "remove_racial_masks", ids = []}, non-existed material
#			{type = 'import_recolor_group', group = 'l_body_alter', material = "centaurus", ids = []}, non-existed material, mb not here
			{type = 'texture_set', set = 'default_male'},
			{type = 'texture_set', set = 'default_female'},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Animal_body/Animal_taz', attr = 'visible', value = false},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Animal_body/Animal_body_assist', attr = 'visible', value = false},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Animal_body/Animal_taz', attr = 'visible', value = false},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Animal_body/Animal_body_assist', attr = 'visible', value = false},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Animal_body', texture = "res://Character_generator/images/14_animals_body/kentaur_body.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Animal_body', texture = "res://Character_generator/images/14_animals_body/kentaur_body.png"},
		],
		#zero support for taurus race
		#half support for harpies - mb no tail, no legs, no ears
		Slime = [ #don't think that shoulder additional parts are positioned correctly
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
			{type = 'node_group_attr', group = 'dryad', attr = 'visible', value = true},
#			{type = 'import_recolor_group', group = 'skin_main', material = "slime", ids = []}, non-existed material
			{type = 'texture_set', set = 'default_male'},
			{type = 'texture_set', set = 'default_female'},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/ShoulderR/ShoulderR_races', texture = "res://Character_generator/images/22_slime/slime_armR.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/ShoulderL/ShoulderL_races', texture = "res://Character_generator/images/22_slime/slime_armL.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Torso_races', texture = "res://Character_generator/images/22_slime/slime_body.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Taz/Taz_races', texture = "res://Character_generator/images/22_slime/slime_taz.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Taz/LegR/LegR_races', texture = "res://Character_generator/images/22_slime/slime_legR.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Taz/LegR/LegL_races', texture = "res://Character_generator/images/22_slime/slime_legL.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/ShoulderR/ShoulderR_races', texture = "res://Character_generator/images/22_slime/slime_armR.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/ShoulderL/ShoulderL_races', texture = "res://Character_generator/images/22_slime/slime_armL.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Torso_races', texture = "res://Character_generator/images/22_slime/slime_body.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Taz/Taz_races', texture = "res://Character_generator/images/22_slime/slime_taz.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Taz/LegR/LegR_races', texture = "res://Character_generator/images/22_slime/slime_legR.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Taz/LegR/LegL_races', texture = "res://Character_generator/images/22_slime/slime_legL.png"},
		],
		#male variants of animal low-body have no genitals (or there supposed to be centaurus with it)
		Lamia = [
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
			{type = 'node_group_attr', group = 'l_body', attr = 'visible', value = false},
			{type = 'node_group_attr', group = 'l_body_alter', attr = 'visible', value = true},
#			{type = 'import_recolor_group', group = 'skin_main', material = "remove_racial_masks", ids = []}, non-existed material
#			{type = 'import_recolor_group', group = 'l_body_alter', material = "lamia", ids = []}, non-existed material, mb not here
			{type = 'texture_set', set = 'default_male'},
			{type = 'texture_set', set = 'default_female'},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Animal_body/Animal_taz', attr = 'visible', value = true},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Animal_body/Animal_body_assist', attr = 'visible', value = false},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Animal_body/Animal_taz', attr = 'visible', value = true},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Animal_body/Animal_body_assist', attr = 'visible', value = false},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Ears_humanoid_tex', texture = "res://Character_generator/images/03_ears/ears_elven.png" }, 
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Animal_body', texture = "res://Character_generator/images/14_animals_body/lamia_body.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Animal_body/Animal_taz', texture = "res://Character_generator/images/14_animals_body/lamia_taz.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Ears_humanoid_tex', texture = "res://Character_generator/images/03_ears/ears_elven.png" }, 
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Animal_body', texture = "res://Character_generator/images/14_animals_body/lamia_body.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Animal_body/Animal_taz', texture = "res://Character_generator/images/14_animals_body/lamia_taz.png"},
		],
		Arachna = [
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
			{type = 'node_group_attr', group = 'l_body', attr = 'visible', value = false},
			{type = 'node_group_attr', group = 'l_body_alter', attr = 'visible', value = true},
#			{type = 'import_recolor_group', group = 'skin_main', material = "remove_racial_masks", ids = []}, non-existed material
#			{type = 'import_recolor_group', group = 'l_body_alter', material = "spider", ids = []}, non-existed material, mb not here
			{type = 'texture_set', set = 'default_male'},
			{type = 'texture_set', set = 'default_female'},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Animal_body/Animal_taz', attr = 'visible', value = true},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Animal_body/Animal_body_assist', attr = 'visible', value = true},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Animal_body/Animal_taz', attr = 'visible', value = true},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Animal_body/Animal_body_assist', attr = 'visible', value = true},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Ears_humanoid_tex', texture = "res://Character_generator/images/03_ears/ears_elven.png" }, 
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Animal_body', texture = "res://Character_generator/images/14_animals_body/arachna_body.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Animal_body/Animal_taz', texture = "res://Character_generator/images/14_animals_body/arachna_taz.png" },
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Animal_body/Animal_body_assist', texture = "res://Character_generator/images/14_animals_body/arachna_helicere.png"},
		],
		Scylla = [
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
			{type = 'node_group_attr', group = 'l_body', attr = 'visible', value = false},
			{type = 'node_group_attr', group = 'l_body_alter', attr = 'visible', value = true},
#			{type = 'import_recolor_group', group = 'skin_main', material = "remove_racial_masks", ids = []}, non-existed material
#			{type = 'import_recolor_group', group = 'l_body_alter', material = "scylla", ids = []}, non-existed material, mb not here
			{type = 'texture_set', set = 'default_male'},
			{type = 'texture_set', set = 'default_female'},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Animal_body/Animal_taz', attr = 'visible', value = false},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Animal_body/Animal_body_assist', attr = 'visible', value = false},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Animal_body/Animal_taz', attr = 'visible', value = false},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Animal_body/Animal_body_assist', attr = 'visible', value = false},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Animal_body', texture = "res://Character_generator/images/14_animals_body/scylla_body.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Animal_body', texture = "res://Character_generator/images/14_animals_body/scylla_body.png"},
		],
		Nereid = [
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
			{type = 'node_group_attr', group = 'nereid', attr = 'visible', value = true},
#			{type = 'import_recolor_group', group = 'skin_main', material = "fish_mask", ids = []}, or not, nvn non-existed material
			{type = 'texture_set', set = 'default_male'},
			{type = 'texture_set', set = 'default_female'},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Ears_humanoid_tex', texture = "res://Character_generator/images/03_ears/ears_nereid.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/ShoulderR/ShoulderR_races', texture = "res://Character_generator/images/21_nereid/nereid_armR.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/ShoulderL/ShoulderL_races', texture = "res://Character_generator/images/21_nereid/Nereid_armL.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Taz/LegR/LegR_races', texture = "res://Character_generator/images/21_nereid/nereid_LegR.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Taz/LegL/LegL_races', texture = "res://Character_generator/images/21_nereid/nereid_LegL.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Ears_humanoid_tex', texture = "res://Character_generator/images/03_ears/ears_nereid.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/ShoulderR/ShoulderR_races', texture = "res://Character_generator/images/21_nereid/nereid_armR.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/ShoulderL/ShoulderL_races', texture = "res://Character_generator/images/21_nereid/Nereid_armL.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Taz/LegR/LegR_races', texture = "res://Character_generator/images/21_nereid/nereid_LegR.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Taz/LegL/LegL_races', texture = "res://Character_generator/images/21_nereid/nereid_LegL.png"},
		],
		BeastkinCat = [
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
#			{type = 'import_recolor_group', group = 'skin_main', material = "remove_racial_masks", ids = []}, non-existed material
			{type = 'texture_set', set = 'beastkin_male'},
			{type = 'texture_set', set = 'beastkin_female'},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Head/Ears_humanoid_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Head/Ears_furry_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Head/Chin_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Tail_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Head/Ears_humanoid_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Head/Ears_furry_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Head/Chin_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Tail_tex', attr = 'visible', value = true},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Head_tex', texture = "res://Character_generator/images/16_beastkin_heads/beastkin_head_cat.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Ears_furry_tex', texture = "res://Character_generator/images/03_ears/ears_cat.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Tail_tex', texture = "res://Character_generator/images/07_tails/tail_cat.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Head_tex', texture = "res://Character_generator/images/16_beastkin_heads/beastkin_head_cat.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Ears_furry_tex', texture = "res://Character_generator/images/03_ears/ears_cat.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Tail_tex', texture = "res://Character_generator/images/07_tails/tail_cat.png"},
		],
		BeastkinWolf = [
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
#			{type = 'import_recolor_group', group = 'skin_main', material = "remove_racial_masks", ids = []}, non-existed material
			{type = 'texture_set', set = 'beastkin_male'},
			{type = 'texture_set', set = 'beastkin_female'},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Head/Ears_humanoid_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Head/Ears_furry_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Head/Chin_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Tail_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Head/Ears_humanoid_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Head/Ears_furry_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Head/Chin_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Tail_tex', attr = 'visible', value = true},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Head_tex', texture = "res://Character_generator/images/16_beastkin_heads/beastkin_head_wolf.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Ears_furry_tex', texture = "res://Character_generator/images/03_ears/ears_wolf.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Tail_tex', texture = "res://Character_generator/images/07_tails/tail_wolf.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Head_tex', texture = "res://Character_generator/images/16_beastkin_heads/beastkin_head_wolf.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Ears_furry_tex', texture = "res://Character_generator/images/03_ears/ears_wolf.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Tail_tex', texture = "res://Character_generator/images/07_tails/tail_wolf.png"},
		],
		BeastkinFox = [
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
#			{type = 'import_recolor_group', group = 'skin_main', material = "remove_racial_masks", ids = []}, non-existed material
			{type = 'texture_set', set = 'beastkin_male'},
			{type = 'texture_set', set = 'beastkin_female'},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Head/Ears_humanoid_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Head/Ears_furry_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Head/Chin_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Tail_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Head/Ears_humanoid_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Head/Ears_furry_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Head/Chin_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Tail_tex', attr = 'visible', value = true},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Head_tex', texture = "res://Character_generator/images/16_beastkin_heads/beastkin_head_fox.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Ears_furry_tex', texture = "res://Character_generator/images/03_ears/ears_fox.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Tail_tex', texture = "res://Character_generator/images/07_tails/tail_fox.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Head_tex', texture = "res://Character_generator/images/16_beastkin_heads/beastkin_head_fox.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Ears_furry_tex', texture = "res://Character_generator/images/03_ears/ears_fox.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Tail_tex', texture = "res://Character_generator/images/07_tails/tail_fox.png"},
		],
		BeastkinBunny = [ #move ears to separate dir
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
#			{type = 'import_recolor_group', group = 'skin_main', material = "remove_racial_masks", ids = []}, non-existed material
			{type = 'texture_set', set = 'beastkin_male'},
			{type = 'texture_set', set = 'beastkin_female'},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Head/Ears_humanoid_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Head/Ears_furry_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Head/Chin_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Head/Ears_humanoid_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Head/Ears_furry_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Head/Chin_tex', attr = 'visible', value = false},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Head_tex', texture = "res://Character_generator/images/16_beastkin_heads/beastkin_head_rabbit.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Ears_furry_tex', texture = "res://Character_generator/images/03_ears/ears_rabbit.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Head_tex', texture = "res://Character_generator/images/16_beastkin_heads/beastkin_head_rabbit.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Ears_furry_tex', texture = "res://Character_generator/images/03_ears/ears_rabbit.png"},
		],
		BeastkinTanuki = [
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
#			{type = 'import_recolor_group', group = 'skin_main', material = "remove_racial_masks", ids = []}, non-existed material
			{type = 'texture_set', set = 'beastkin_male'},
			{type = 'texture_set', set = 'beastkin_female'},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Head/Ears_humanoid_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Head/Ears_furry_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Head/Chin_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Tail_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Head/Ears_humanoid_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Head/Ears_furry_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Head/Chin_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Tail_tex', attr = 'visible', value = true},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Head_tex', texture = "res://Character_generator/images/16_beastkin_heads/beastkin_head_tanuki.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Ears_furry_tex', texture = "res://Character_generator/images/03_ears/ears_tanuk.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Tail_tex', texture = "res://Character_generator/images/07_tails/tail_tanuk.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Head_tex', texture = "res://Character_generator/images/16_beastkin_heads/beastkin_head_tanuki.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Ears_furry_tex', texture = "res://Character_generator/images/03_ears/ears_tanuk.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Tail_tex', texture = "res://Character_generator/images/07_tails/tail_tanuk.png"},
		],
		HalfkinCat = [
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
#			{type = 'import_recolor_group', group = 'skin_main', material = "remove_racial_masks", ids = []}, non-existed material
			{type = 'texture_set', set = 'default_male'},
			{type = 'texture_set', set = 'default_female'},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Head/Ears_humanoid_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Head/Ears_furry_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Tail_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Head/Ears_humanoid_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Head/Ears_furry_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Tail_tex', attr = 'visible', value = true},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Ears_furry_tex', texture = "res://Character_generator/images/03_ears/ears_cat.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Tail_tex', texture = "res://Character_generator/images/07_tails/tail_cat.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Ears_furry_tex', texture = "res://Character_generator/images/03_ears/ears_cat.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Tail_tex', texture = "res://Character_generator/images/07_tails/tail_cat.png"},
		],
		HalfkinWolf = [
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
#			{type = 'import_recolor_group', group = 'skin_main', material = "remove_racial_masks", ids = []}, non-existed material
			{type = 'texture_set', set = 'default_male'},
			{type = 'texture_set', set = 'default_female'},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Head/Ears_humanoid_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Head/Ears_furry_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Tail_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Head/Ears_humanoid_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Head/Ears_furry_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Tail_tex', attr = 'visible', value = true},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Ears_furry_tex', texture = "res://Character_generator/images/03_ears/ears_wolf.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Tail_tex', texture = "res://Character_generator/images/07_tails/tail_wolf.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Ears_furry_tex', texture = "res://Character_generator/images/03_ears/ears_wolf.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Tail_tex', texture = "res://Character_generator/images/07_tails/tail_wolf.png"},
		],
		HalfkinFox = [
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
#			{type = 'import_recolor_group', group = 'skin_main', material = "remove_racial_masks", ids = []}, non-existed material
			{type = 'texture_set', set = 'default_male'},
			{type = 'texture_set', set = 'default_female'},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Head/Ears_humanoid_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Head/Ears_furry_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Tail_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Head/Ears_humanoid_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Head/Ears_furry_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Tail_tex', attr = 'visible', value = true},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Ears_furry_tex', texture = "res://Character_generator/images/03_ears/ears_fox.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Tail_tex', texture = "res://Character_generator/images/07_tails/tail_fox.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Ears_furry_tex', texture = "res://Character_generator/images/03_ears/ears_fox.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Tail_tex', texture = "res://Character_generator/images/07_tails/tail_fox.png"},
		],
		HalfkinBunny = [ #move ears to separate dir
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
#			{type = 'import_recolor_group', group = 'skin_main', material = "remove_racial_masks", ids = []}, non-existed material
			{type = 'texture_set', set = 'default_male'},
			{type = 'texture_set', set = 'default_female'},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Head/Ears_humanoid_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Head/Ears_furry_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Head/Ears_humanoid_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Head/Ears_furry_tex', attr = 'visible', value = true},
		],
		HalfkinTanuki = [
			{type = 'node_group_attr', group = 'human', attr = 'visible', value = true},
			{type = 'node_group_attr', group = 'nonhuman', attr = 'visible', value = false},
#			{type = 'import_recolor_group', group = 'skin_main', material = "remove_racial_masks", ids = []}, non-existed material
			{type = 'texture_set', set = 'default_male'},
			{type = 'texture_set', set = 'default_female'},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Head/Ears_humanoid_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Head/Ears_furry_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'male_pose/HumanF1/Spine/Tail_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Head/Ears_humanoid_tex', attr = 'visible', value = false},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Head/Ears_furry_tex', attr = 'visible', value = true},
			{type = 'node_attr', node = 'Female_pose/HumanF1/Spine/Tail_tex', attr = 'visible', value = true},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Head/Ears_furry_tex', texture = "res://Character_generator/images/03_ears/ears_tanuk.png"},
			{type = 'texture', node = 'male_pose/HumanF1/Spine/Tail_tex', texture = "res://Character_generator/images/07_tails/tail_tanuk.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Head/Ears_furry_tex', texture = "res://Character_generator/images/03_ears/ears_tanuk.png"},
			{type = 'texture', node = 'Female_pose/HumanF1/Spine/Tail_tex', texture = "res://Character_generator/images/07_tails/tail_tanuk.png"},
		],
	},
	
}
