extends Reference

# Skeleton contract for the Doll 2 rig.  BONES, SLOTS and IK are generated
# from the Spine export; HANDLES are hand-authored and preserved on rebuild.
#
# Everything in universal/ is keyed to CONTRACT_ID instead of to one export
# file, so a second skeleton (the male export) either satisfies this contract
# or gets its own id, and poses written against it can never silently drift.

const CONTRACT_ID = "doll2_v1"

const BONES = [
	"root",
	"bone4",
	"spine1",
	"spine2",
	"spine3",
	"spine4",
	"collarbone_l",
	"shoulder_l",
	"forearm_l",
	"hand_l",
	"finger1_l",
	"finger2_l",
	"collarbone_r",
	"shoulder_r",
	"forearm_r",
	"hand_r",
	"finger1_r",
	"finger2_r",
	"neck",
	"head",
	"fringe1_r",
	"fringe2_r",
	"fringe3_r",
	"fringe1_l",
	"fringe2_l",
	"fringe3_l",
	"hair1_r",
	"hair2_r",
	"hair3_r",
	"hair4_r",
	"hair1_l",
	"hair2_l",
	"hair3_l",
	"hair4_l",
	"chest_r",
	"chest_l",
	"nipple4_r",
	"nipple4_l",
	"sternum_r",
	"sternum_l",
	"spine46",
	"spine47",
	"spine48",
	"bone",
	"bone2",
	"bone3",
	"nipple3_r",
	"nipple3_l",
	"pelvisr_3",
	"pelvisr_2",
	"pelvisl_3",
	"pelvisl_2",
	"nipple2_r",
	"nipple2_l",
	"nipple5_r",
	"nipple5_l",
	"pelvisr_1",
	"pelvisl_1",
	"brov_l",
	"brov_r",
	"head2",
	"head3",
	"head4",
	"head5",
	"head6",
	"head7",
	"head8",
	"head9",
	"head10",
	"hair4_l2",
	"hair4_r2",
	"head11",
	"head12",
	"hair4_r3",
	"hair4_r4",
	"hair4_r5",
	"hair4_l3",
	"hair4_l4",
	"head13",
	"head14",
	"hair1_r2",
	"hair1_r3",
	"hair1_r4",
	"hair1_r5",
	"hair1_r6",
	"hair1_r7",
	"hair1_r8",
	"hair1_r9",
	"hair1_r10",
	"hair1_l2",
	"hair1_l3",
	"hair1_l4",
	"hair1_l5",
	"hair1_l6",
	"hair1_l7",
	"hair1_l8",
	"hair1_l9",
	"hair1_l10",
	"hair1_l11",
	"hair1_r11",
	"hair1_r12",
	"hair1_r13",
	"hair1_r14",
	"hair1_r15",
	"hair1_l12",
	"hair1_l13",
	"hair1_l14",
	"hair1_l15",
	"hair1_l16",
	"hair1_l17",
	"hair4_r6",
	"hair4_r7",
	"head15",
	"head16",
	"head17",
	"head18",
	"spine5",
	"spine6",
	"spine7",
	"spine8",
	"spine9",
	"spine10",
	"spine11",
	"spine12",
	"spine13",
	"spine14",
	"spine15",
	"spine16",
	"spine17",
	"spine18",
	"spine19",
	"spine20",
	"spine21",
	"spine22",
	"spine23",
	"spine24",
	"spine25",
	"spine26",
	"spine27",
	"spine28",
	"spine29",
	"spine30",
	"spine31",
	"spine32",
	"spine33",
	"spine34",
	"spine35",
	"spine36",
	"spine37",
	"spine38",
	"spine39",
	"spine40",
	"spine41",
	"spine42",
	"spine43",
	"spine44",
	"spine45",
	"spine49",
	"spine50",
	"spine51",
	"spine52",
	"spine53",
	"spine54",
	"spine55",
	"spine56",
	"spine57",
	"spine58",
	"spine59",
	"spine60",
	"spine61",
	"spine62",
	"spine63",
	"spine64",
	"spine65",
	"spine66",
	"spine67",
	"spine68",
	"spine69",
	"spine70",
	"spine71",
	"spine72",
	"spine73",
	"spine74",
	"spine75",
	"spine76",
	"spine77",
	"spine78",
	"spine79",
	"spine80",
	"spine81",
	"spine82",
	"spine83",
	"spine84",
	"spine85",
	"spine86",
	"spine87",
	"spine88",
	"spine89",
	"spine90",
	"spine91",
	"spine92",
	"spine93",
	"spine94",
	"spine95",
	"spine96",
	"spine97",
	"spine98",
	"spine99",
	"spine100",
	"spine101",
	"spine102",
	"spine103",
	"spine104",
	"spine105",
	"spine106",
	"spine107",
	"spine108",
	"spine109",
	"spine110",
	"spine111",
	"spine112",
	"spine113",
	"spine114",
	"spine115",
	"spine116",
	"spine117",
	"spine118",
	"spine119",
	"spine120",
	"spine121",
	"spine122",
	"nipple4_r2",
	"nipple5_r2",
	"nipple3_r2",
	"nipple2_r2",
	"nipple2_l2",
	"nipple3_l2",
	"nipple4_l2",
	"nipple5_l2",
	"collarbone_l2",
	"collarbone_l3",
	"collarbone_l4",
	"collarbone_l5",
	"collarbonr_r2",
	"collarbonr_r3",
	"collarbonr_r4",
	"collarbonr_r5",
	"spine123",
	"spine124",
	"spine125",
	"spine126",
	"target1",
	"target2",
	"target4",
	"target3",
	"target5",
	"target6",
	"target7",
	"target8",
	"eyes_l",
	"eyes_r",
	"ear_l",
	"ear_r",
	"ear_lt",
	"ear_rt",
	"pupil_l",
	"pupil_r",
	"nose",
	"lips",
	"lips2",
	"lips3",
]

const SLOTS = [
	"animal_body",
	"weapon_back",
	"wings",
	"hairs_back",
	"tails",
	"equip_back",
	"hand_left",
	"equip_hand_left",
	"arm_left",
	"race_arm_left",
	"equip_arm_left",
	"shoulder_left",
	"race_shoulder_left",
	"equip_shoulder_left",
	"hand_right",
	"equip_hand_right",
	"arm_right",
	"race_arm_right",
	"equip_arm_right",
	"shoulder_right",
	"race_shoulder_right",
	"equip_shoulder_right",
	"torso",
	"equip_collar",
	"torso_nipples_mask",
	"leg_left",
	"race_leg_left",
	"equip_leg_left",
	"leg_right",
	"race_leg_right",
	"equip_leg_right",
	"pelvis",
	"belly",
	"equip_torso",
	"breasts_beastkin_many",
	"beastkin_torso_many_nipples",
	"race_pelvis",
	"animal_frontbody",
	"testicle",
	"equip_pelvis",
	"equip_belly",
	"pregnancy_belly",
	"race_torso_lower",
	"breasts_beastkin_pregnancy",
	"beastkin_pregnancy_nipple",
	"tatoos",
	"dick",
	"equip_pregnancy_low",
	"equip_pregnancy_up",
	"weapon_belt",
	"breasts",
	"breasts_beastkin",
	"breast_nipples",
	"race_torso",
	"equip_breasts",
	"hairs_assist",
	"head_skull",
	"head",
	"sclera",
	"eyes",
	"eyes_hearts",
	"race_head",
	"face",
	"hairs_base",
	"ears",
	"lips",
	"eyebrows",
	"noses",
	"blush",
	"hairs_fringe",
	"equip_masks",
	"equip_head",
	"horns",
]

const IK = [
	{
		"bend": 1,
		"bones": ["bone", "bone2"],
		"name": "target1",
		"order": 0,
		"target": "target1",
	},
	{
		"bend": 1,
		"bones": ["spine46", "spine47"],
		"name": "target2",
		"order": 1,
		"target": "target2",
	},
	{
		"bend": 1,
		"bones": ["bone3"],
		"name": "target3",
		"order": 3,
		"target": "target3",
	},
	{
		"bend": 1,
		"bones": ["spine48"],
		"name": "target4",
		"order": 2,
		"target": "target4",
	},
	{
		"bend": 1,
		"bones": ["spine116", "spine117"],
		"name": "target5",
		"order": 4,
		"target": "target5",
	},
	{
		"bend": -1,
		"bones": ["spine119", "spine120"],
		"name": "target6",
		"order": 5,
		"target": "target6",
	},
	{
		"bend": 1,
		"bones": ["spine107", "spine108"],
		"name": "target7",
		"order": 6,
		"target": "target7",
	},
	{
		"bend": 1,
		"bones": ["spine104", "spine105"],
		"name": "target8",
		"order": 7,
		"target": "target8",
	},
]

# Friendly drag handles exposed by the preview.  Hands use a synthetic
# two-bone chain; feet move the Spine foot endpoint and ankle target together.
const HANDLES = {
	"left_foot": {
		"label": "DOLL2_PREVIEW_HANDLE_LEFT_FOOT",
		"target_bones": ["target4", "target2"],
	},
	"left_hand": {
		"bend": 1,
		"end_bone": "hand_l",
		"ik_bones": ["shoulder_l", "forearm_l"],
		"label": "DOLL2_PREVIEW_HANDLE_LEFT_HAND",
	},
	"right_foot": {
		"label": "DOLL2_PREVIEW_HANDLE_RIGHT_FOOT",
		"target_bones": ["target3", "target1"],
	},
	"right_hand": {
		"bend": -1,
		"end_bone": "hand_r",
		"ik_bones": ["shoulder_r", "forearm_r"],
		"label": "DOLL2_PREVIEW_HANDLE_RIGHT_HAND",
	},
}
