	MSLMCONTEXT_OPEN_CLASS_TAB = """Class & Skills""", # MISSING TRANSLATION
	MSLMCONTEXT_OPEN_SIBLINGS_TAB = """Training & Rules""", # MISSING TRANSLATION
	MSLMCONTEXT_OPEN_CUSTOMIZATION_TAB = """Customization""", # MISSING TRANSLATION
	MSLMCONTEXT_OPEN_OCCUPATION = """Occupation""", # MISSING TRANSLATION
