extends Node

#var sceneexample = [
#{effect = 'background', value = 'castle'},
#{effect = 'music', value = 'intro'},
#{effect = 'sfx', value = 'blackscreenturnon', args = null, delay = 1},
#{effect = 'sfx', value = 'blackscreenunfade', args = 2, delay = 0.5},
#{effect = 'text', value = 'This a narrator message', source = 'narrator', portrait = null, sound = null},
#{effect = 'sprite', value = 'unfade', args = 0.5},
#{effect = 'sprite', value = 'set', args = 'rose', delay = 0.5},
#{effect = 'text', value = "This is a Rose's message, ahshajsja jfdsjfsj ", source = 'Rose', portrait = 'rosenormal'},
#{effect = 'text', value = 'This a narrator message2', source = 'narrator', portrait = null, sound = null},
#{effect = 'sprite', value = 'fade', args = 0.5, delay = 0.5},
#{effect = 'sprite', value = 'hide', args = null},
#]
var introdesert = [
{effect = 'background', value = 'castleroom'},
{effect = 'text', source = 'narrator', portrait = null, sound = null,
value = "In the middle of empty desert two bodies appear on the ground."},
{effect = 'text', source = 'ARRON', portrait = null, sound = null,
value = "Ouch... Damn it, Rose you are an idiot!"},
{effect = 'text', source = 'ROSE', portrait = null, sound = null,
value = "Ugh. What's this place? Where are we?"},
{effect = 'text', source = 'ARRON', portrait = null, sound = null,
value = "Hell if I know. Untie me already."},
{effect = 'background', value = 'castle'},
{effect = 'text', source = 'narrator', portrait = null, sound = null,
value = "Arron barely managed to get up with his hands still tied behind his back."},
{effect = 'text', source = 'narrator', portrait = null, sound = null,
value = "After a couple of moments, Rose finally frees Arron from ropes."},
{effect = 'text', source = 'narrator', portrait = null, sound = null,
value = "*Thud*"},
{effect = 'background', value = 'desert'},
{effect = 'text', source = 'ROSE', portrait = null, sound = null,
value = "Owie... Why!?"},
{effect = 'text', source = 'ARRON', portrait = null, sound = null,
value = "Why? I ask you, why jump in, you moron? In what universe that seemed like a good idea?"},
{effect = 'text', source = 'ROSE', portrait = null, sound = null,
value = "I'm sorry, Master... I just... didn't know what else to do."},
{effect = 'text', source = 'narrator', portrait = null, sound = null,
value = "Rose's eyes gone moist from sudden punishment, as Master rarely used force with her, even when she wasn't obedient."},
{effect = 'text', source = 'ARRON', portrait = null, sound = null,
value = "Forget it. Now what is this place? Shit, I really shouldn't have sleept during those geography lessons."},
{effect = 'text', source = 'ARRON', portrait = null, sound = null,
value = "Norb will really pay for this once I get back. Firstly I'll take care of those suspicious guys with him..."},
{effect = 'text', source = 'ROSE', portrait = null, sound = null,
value = "I think it will be better if we start moving."},
{effect = 'text', source = 'ARRON', portrait = null, sound = null,
value = "Yeah, it does not seem like anyone will be serving us any time soon. Let's go."},
{effect = 'text', source = 'ROSE', portrait = null, sound = null,
value = "Where to?"},
{effect = 'text', source = 'ARRON', portrait = null, sound = null,
value = "Hrm.. Anywhere! I'm free now, so I can go anywhere I want, Mwahaha!"},
{effect = 'text', source = 'ARRON', portrait = null, sound = null,
value = "(Despite the situtation, looks like Master has returned to his normal mood really quickly. That's a reflief...)"},
{effect = 'sfx', value = 'blackscreenunfade', args = 2, delay = 2},
{effect = 'sfx', value = 'blackscreenfade', args = 2, delay = 2},
{effect = 'text', source = 'ROSE', portrait = null, sound = null,
value = "Hmmm... It was midnight when we were at castle, but its a noon here, that must mean..."},
{effect = 'text', source = 'ARRON', portrait = null, sound = null,
value = "A timetravel!"},
{effect = 'text', source = 'ROSE', portrait = null, sound = null,
value = "No, this land must be very far away from Kingdom."},
{effect = 'text', source = 'ARRON', portrait = null, sound = null,
value = "Bullshit, you telling me timetravel isn't real now?"},
{effect = 'text', source = 'ROSE', portrait = null, sound = null,
value = "It never was..."},
{effect = 'text', source = 'ARRON', portrait = null, sound = null,
value = "So I will never be able to become my own grandfather?"},
{effect = 'text', source = 'ROSE', portrait = null, sound = null,
value = "...Thankfully"},
]



