extends Node

var TranslationDict = {
	#Buildings
	WORKERMARKET = "Market",
	PURCHASE = "Purchase",
	SELL = "Sell",
	TASKS = "Tasks",
	UPGRADES = "Upgrades",
	TOWNHALL = "Town Hall",
	FOODCONV = "Food Conversion",
	HARVESTMETAL = "Harvest Ore",
	HARVESTPLANT = "Harvest Plants",
	GOBLINWORKER = "Goblin Worker",
	ELFWORKER = "Elven Worker",
	
	
	#Materials
	STARTINGADJ = "Starting",
	
	
	
	
	WOODADJ = "wooden",
	STONEADJ = 'stone',
	LEATHERADJ = "Leather",
	BONEADJ = "Bone",
	CLOTHADJ = "Cotton",
	
	
	MATERIALMEAT = "Meat",
	MATERIALMEATDESCRIPT = "A rich source of nutrients. Can be acquired from hunting. ",
	MATERIALFISH = "Fish",
	MATERIALFISHDESCRIPT = "A common source of food. Acquired from fishing. ",
	MATERIALVEGETABLES = "Vegetables",
	MATERIALVEGETABLESDESCRIPT = "A common source of food of grown origin. Harvested at farm. ",
	MATERIALGRAINS = "Grains",
	MATERIALGRAINSDESCRIPT = "A common source of food of grown origin. Harvested at farm. ",
	MATERIALBREAD = "Bread",
	MATERIALBREADDESCRIPT = "A staple food baked from grains. Produced by cooking.",
	MATERIALMEATSOUP = "Meat Soup",
	MATERIALMEATSOUPDESCRIPT = "An adequate water and nutrient combination for a long time. Produced by cooking. ",
	MATERIALFISHCAKES = "Fish Cakes",
	MATERIALFISHCAKESDESCRIPT = "A baked dough with fish paste. Especially liked by Cat folk. Produced by cooking. ",
	MATERIALSTONE = "Stone",
	MATERIALSTONEDESCRIPT = "Stone comes in many forms and shapes, but might serve as good building material or even poor instrumentum. Produced by mining. ",
	MATERIALOBSIDIAN = "Obsidian",
	MATERIALOBSIDIANDESCRIPT = "Stone comes in many forms and shapes, but might serve as good building material or even poor instrumentum. ",
	MATERIALWOOD = "Wood",
	MATERIALWOODDESCRIPT = "Sturdy wood for general building and furnishing purposes. Produced by wood cutting. ",
	MATERIALWOODMAGIC = "Magic Wood",
	MATERIALWOODMAGICDESCRIPT = "An unusual wood imbued with traces of magic power.",
	MATERIALWOODIRON = "Iron Wood",
	MATERIALWOODIRONDESCRIPT = "A dense and sturdy piece of wood suitable even for defensive tasks.",
	MATERIALWOODANCIENT = "Ancient Wood",
	MATERIALWOODANCIENTDESCRIPT = "A wood of an ancient plant. Its perservance over the ages showcases its mighty properties",
	MATERIALLEATHER = "Leather",
	MATERIALLEATHERDESCRIPT = "A common animal leather. Can be used for light armor and accessory. Produced by hunting and acquired from weak monsters. ",
	MATERIALLEATHERTHICK = "Thick Leather",
	MATERIALLEATHERTHICKDESCRIPT = "A thicker and sturdier leather which can provide aditional defense. Acquired from strong monsters. ",
	MATERIALLEATHERMYTHIC = "Mythic Leather",
	MATERIALLEATHERMYTHICDESCRIPT = "A leather belonging to the rare mythic beasts posessing an unusual properties. Acquired from rare strong monsters. ",
	MATERIALLEATHERDRAGON = "Dragon Leather",
	MATERIALLEATHERDRAGONDESCRIPT = "Dragon leather is extremely rare and hard to work with. Acquired from slaying dragons.",
	MATERIALBONE = "Bone",
	MATERIALBONEDESCRIPT = "A common animal bone. With right approach can provide some interesting properties. Acquired from slaying enemies. ",
	MATERIALBONEANCIENT = "Ancient Bone",
	MATERIALBONEANCIENTDESCRIPT = "A bone of creature from myths. Its properties are on par with metal. Acquired from slaying enemies. ",
	MATERIALBONEDRAGON = "Dragon Bone",
	MATERIALBONEDRAGONDESCRIPT = "Dragon bones are rare and expensive material. Acquired from slaying dragons.",
	MATERIALCLOTH = "Cloth",
	MATERIALCLOTHDESCRIPT = "A simple cotton fibre for simple clothes. Can be used for cloth armor. Acquired from farming. ",
	MATERIALCLOTHSILK = "Silk",
	MATERIALCLOTHSILKDESCRIPT = "A fine cloth material. Acquired from slaying monsters.",
	MATERIALCLOTHMAGIC = "Magic Cloth",
	MATERIALCLOTHMAGICDESCRIPT = "A cloth material with magic properties. Acquired from crafting.",
	MATERIALCLOTHETHEREAL = "Ethereal Cloth",
	MATERIALCLOTHETHEREALDESCRIPT = "A cloth material with rare magic properties. Acquired from monsters.",
	MATERIALIRON = "Iron",
	MATERIALIRONDESCRIPT = "A common metal suitable for weapon and armor. Acquired from mining. ",
	MATERIALSTEEL = "Steel",
	MATERIALSTEELDESCRIPT = "A strong metal alloy of carbon and iron. Acquired from crafting",
	MATERIALMITHRIL = "Mythril",
	MATERIALMITHRILDESCRIPT = "A metal with strong magic properties. Acquired from mining.",
	MATERIALADAMANTINE = "Adamantine",
	MATERIALADAMANTINEDESCRIPT = "A very rare and strong magic alloy. Acquired from crafting. ",
	MATERIALFLEAWARTS = "Fleawarts",
	MATERIALFLEAWARTSDESCRIPT = "A common plant with healing properties.",
	MATERIALSALVIA = "Salvia",
	MATERIALSALVIADESCRIPT = "An uncommon plant with mind influencing properties. ",
	MATERIALTRAP = "Trap",
	MATERIALTRAPDESCRIPT = "A mechanical trap designed to hold target in place. Required for certain skills. ",
	MATERIALUNSTABLE_CONCOCTION = "Unstable Concoction",
	MATERIALUNSTABLE_CONCOCTIONDESCRIPT = "A potent alchemical mixture. Required for certain skills. ",
	
	ITEMBED = "Bed",
	ITEMBEDDESCRIPT = "",
	ITEMLEATHER_COLLAR = "Leather Collar",
	ITEMLEATHER_COLLARDESCRIPT = "",
	ITEMELEGANT_CHOCKER = "Elegant Choker",
	ITEMELEGANT_CHOCKERDESCRIPT = "",
	ITEMSTEEL_COLLAR = "Steel Collar",
	ITEMSTEEL_COLLARDESCRIPT = "",
	ITEMANIMAL_EARS = "Animal Ears",
	ITEMANIMAL_EARSDESCRIPT = "",
	ITEMTAIL_PLUG = "Tail Plug",
	ITEMTAIL_PLUGDESCRIPT = "",
	ITEMANIMAL_GLOVES = "Animal Gloves",
	ITEMPET_SUIT = "Pet Suit",
	ITEMPET_SUITDESCRIPT = "",
	ITEMSHACKLES = "Shackles",
	ITEMSHACKLESDESCRIPT = "",
	ITEMCHASTITY_BELT = "Chastity Belt",
	ITEMCHASTITY_BELTDESCRIPT = "",
	ITEMSTIMULATIVE_UNDERWEAR = 'Stimulative Underwear',
	ITEMSTIMULATIVE_UNDERWEARDESCRIPT = "",
	ITEMTENTACLE_SUIT = 'Tentacle Suit',
	ITEMTENTACLE_SUITDESCRIPT = "",
	
	ITEMAPHRODISIAC = "Aphrodisiac",
	ITEMAPHRODISIACDESCRIPT = "",
	ITEMALCOHOL = "Alcohol",
	ITEMALCOHOLDESCRIPT = "",
	ITEMTAMEDRUG = "Tame Drug",
	ITEMTAMEDRUGDESCRIPT = "",
	ITEMRAGEDRUG = "Rage Drug",
	ITEMRAGEDRUGDESCRIPT = "",
	ITEMSEXDRUG = "Sex Drug",
	ITEMSEXDRUGDESCRIP = "",
	
	
	
	
	#Items
	WEAPONAXENAME = "Axe",
	WEAPONPICKAXENAME = "Pickaxe",
	WEAPONSWORDNAME = 'Sword',
	WEAPONBOWNAME = "Bow",
	WEAPONSTAFFNAME = "Staff",
	
	
	WEAPONAXEDESCRIPT = 'Axe can be used for cutting wood and combat.',
	WEAPONSWORDDESCRIPT = "Good damage vs unarmored enemies.",
	WEAPONPICKAXEDESCRIPT = "Allows workers to harvest ore, but also can be use in combat.",
	WEAPONBOWDESCRIPT = "Simple weapon for ranged fighters.",
	WEAPONSTAFFDESCRIPT = "A simple tool for magic users.",
	
	ARMORBASICCHEST = "Chestplate",
	ARMORROBE = "Robe",
	ARMORHOOD = "Hood",
	ARMORSHOES = "Shoes",
	ARMORBASICCHESTDESCRIPT = "Offers basic body protection.",
	ARMORBASICHELM = "Helmet",
	ARMORBASICHELMDESCRIPT = "Offers basic head protection.",
	ARMORBASICBOOTS = "Boots",
	ARMORBASICBOOTSDESCRIPT = "Offers basic foot protection",
	ARMORBASICGLOVES = "Gloves",
	ARMORBASICGLOVESDESCRIPT = "Offers basic hand protection",
	
	USABLEMORSEL = "Morsel",
	USABLEMORSELDESCRIPT = "A questionable piece of meat. Restores 50 health. Can be converted into Food.",
	USABLEMANAGRASS = "Blue Grass",
	USABLEMANAGRASSDESCRIPT = "An unusual plant with magical properties. Restores 25 mana on use. ",
	USABLEBARRICADE = "Barricade",
	USABLEBARRICADEDESCRIPT = "A makeshift wooden obstacle. Shields target from 50 physical damage for 2 turns",
	USABLEPROTECTIVECHARM = "Protective Charm",
	USABLEPROTECTIVECHARMDESCRIPT = "An enchanted piece of paper. Shields target from 50 magic damage for 2 turns",
	USABLEELIXIR = "Elixir",
	USABLEELIXIRDESCRIPT = "A rejuvinating potion. Restores 75 health and 40 mana.",
	
	
	#enemies
	MONSTERELVENRAT = "Elven Rat",
	MONSTERELVENRATFLAVOR = "These animals are fairly common in most areas. Distinct ears make them accumulate all sorts of moniker, but goblins seem to label them this way...",
	MONSTERTREANT = "Ent",
	MONSTERTREANTFLAVOR = "Despite its looks, this thing is actually a plant. Often disguises itself as a simple trunk for a nasty surprise.",
	MONSTERBIGTREANT = "Big Ent",
	MONSTERBIGTREANTFLAVOR = "Big ents are somewhat mobile and quite dangerous when provoked.",
	MONSTEREARTHGOLEM = "Earth Golem",
	MONSTEREARTHGOLEMFLAVOR = "A magic creature of considerable power. They seem to roam around some caves and dungeons with little thought. I would expect more from a hand-made slave. ",
	MONSTERSPIDER = "Spider",
	MONSTERSPIDERFLAVOR = "Of course just ents weren't enough...",
	MONSTERFAIRIES = "Fairies",
	MONSTERFAIRIESFLAVOR = "If not for their nasty nature, I would even consider them appealing.",
	MONSTERANGRYDWARF = "Angry Dwarf",
	MONSTERANGRYDWARFFLAVOR = "Dumb but strong for their size. Despite my best attempts, they didn't seem to be up for any sort of negotiation. ",
	MONSTEREARTHGOLEMBOSS = "Greater Golem",
	MONSTEREARTHGOLEMBOSSFLAVOR = "Twice as big as normal golem. And twice as angry...",
	#gearclasses
	GEARSWORD = "Swords",
	GEARAXE = "Axes",
	GEARSTAFF = "Staves",
	GEARBOW = "Bows",
	GEARPICKAXE = "Pickaxes",
	
	#Stats
	DAMAGE = 'Damage',
	DAMAGEMOD = "Damage Mult.",
	ARMOR = 'Armor',
	MDEF = "Magic Armor",
	EVASION = 'Evasion',
	HITRATE = 'Hit Chance',
	HEALTH = 'Health',
	DURABILITY = "Durability",
	DURABILITYMOD = "Dur. Factor",
	ARMORPENETRATION = "Armor Pen.",
	RESISTFIRE = "Fire Res.",
	RESISTEARTH = "Earth Res.",
	RESISTAIR = "Air Res.",
	RESISTWATER = "Water Res.",
	HEALTHPERCENT = "Max. Health",
	MANAPERCENT = "Max. Mana",
	CRITICAL = "Critical",
	CRITCHANCE = "Crit. Chance",
	CRITMOD = "Crit. Mod",
	LEVELUP = "Level up",
	MAXLEVEL =  "Maximum Level",
	LEVEUPTEXT = " has just acquired a level. Select a new trait to unlock",
	
	#stat tooltips
	TOOLTIPDAMAGE = "Defines damage output of skills and spells",
	TOOLTIPARMOR = "Reduces skill damage taken by this percent",
	TOOLTIPMDEF = "Reduces spell damage taken by this percent",
	TOOLTIPCRIT = "Percent chance to crit for extra damage\nFirst value is a chance. Second value is a modifier.",
	TOOLTIPHITRATE = "Percent chance to hit target\nReduced by enemy's evasion",
	TOOLTIPARMORPEN = "Reduces enemy armor by this value",
	TOOLTIPEVASION = "Reduces enemy hit chance by this value",
	TOOLTIPSPEED = "Improves your odds to act before other characters",
	TOOLTIPRESISTS = "Reduces elemental damage by relative resist",
	
	#Item Parts
	TOOLHANDLE = 'Handle',
	BLADE = 'Blade',
	BLUNT = 'Head',
	ROD = 'Knub',
	BOWBASE = 'Bow Limb',
	ARMORBASE = 'Base',
	ARMORPLATE = 'Plate',
	ARMORTRIM = 'Trim',
	JEWELRYGEM = 'Gem',
	
	
	#Material Effects
	GOBMETALHANDLEDESCRIPT = "Deals 15% more damage when enemy's health below 30%",
	ELFMETALHANDLEDESCRIPT = "Gain +1 Mana on skill hit",
	GOBMETALBLADEDESCRIPT = "Deals small bonus earth damage",
	ELFMETALBLADEDESCRIPT = "Deals +10 damage on first hit",
	ELFWOODRODDESCRIPT = "Restores 10% mana on the end of combat",
	GOBMETALRODDESCRIPT = "For 1 turn reduces target's speed by 10 on spell hit",
	BONERODDESCRIPT = "Restores 3% health on spell hit",
	BONEBOWDESCRIPT = "+1 health on hit",
	
	
	#Menu
	NEWGAME = "New Game",
	LOAD = 'Load',
	OPTIONS = 'Options',
	QUIT = 'Quit',
	CLOSE = "Close",
	PROCEED = "Proceed",
	SELECTHERO = "Select Hero",
	SOUND = "Sound",
	MUSIC = "Music",
	MASTERSOUND = "Master Volume",
	MUTE = "Mute",
	AUDIO = "Audio",
	
	TEXTSPEED = "Text Speed",
	SKIPREAD = "Skip Read",
	
	CURRENTFOOD = "Current Food",
	GAINFOOD = "Food Value",
	FOODCONVERT = "Convert Food",
	
	#System
	CONFIRM = "Confirm",
	FRONT = "Front",
	BACK = "Back",
	CANCEL = "Cancel",
	REMOVE = "Remove",
	NONE = "None",
	SPEED = "Speed",
	DAY = "Day",
	ENERGY = "Energy",
	TIME = "Time",
	CRAFT = "Craft",
	BLACKSMITH = "Blacksmith",
	PROGRESS = "Progress",
	REPAIR = "Repair",
	REPAIRALL = "Repair All",
	WORKERNOENERGY = " has no energy left and stopped working.",
	TOOLBROKEN = " has broken.",
	CURRENTTASK = "Current Task",
	REQUIREDMATERIAL = "Required Material",
	REQUIREDMATERIALS = "Required Materials",
	SELECTREPAIR = "Select Item(s) to Repair",
	TOTALPRICE = "Total Price",
	SELECTMATERIAL = "Select materials for all parts.",
	INPOSESSION = "In Possession",
	BASECHANCE = "Base Chance",
	CANTREPAIREFFECT = "This item can't be repaired.",
	NOTENOUGH = "Not enough",
	ITEMCREATED = "Item Created",
	UPGRADEUNLOCKED = "Upgrade Unlocked",
	MAINQUEST = "Main Quest",
	SIDEQUESTS = "Sidequests",
	MAINQUESTUPDATED = "Main Quest Updated",
	QUESTLOG = "Quest Log",
	NOACTIVEQUESTS = "You have no active quests.",
	INVALIDCLASS = "Invalid class for this gear.",
	NOTENOUGHGOLD = "Not enough gold",
	PURCHASETHISTRAIT = "Purchase this trait",
	TRAITPOINTSCOST = "Trait Points",
	TRAITPOINTS = "Trait Points used",
	GOLDPRICE = "Gold Cost",
	
	SYSNOFOOD = "Work canceled: No food",
	SYSNOWORKERENERGY = "Work canceled: No energy",
	
	
	SELECT = "Select",
	SELECTTOOL = "Select Tool",
	SELECTWORKER = "Select Worker",
	SELECTITEM = "Select Item",
	WORKERLIMITREACHER = "Worker Limit Reached: Upgrade Houses to increase",
	TOTALWORKERS = "Total Workers",
	
	TUTORIAL = "Tutorial",
	TRAITS = "Traits",
	CLASSINFO = "Class Details",
	
	INVENTORY = "Inventory",
	WORKERLIST = "Worker List",
	HEROLIST = "Hero List",
	OPTIONMENU = "Options",
	
	INVENTORYALL = "All items",
	INVENTORYWEAPON = "Weapons",
	INVENTORYARMOR = "Armor",
	INVENTORYMATERIAL = "Materials",
	INVENTORYUSE = "Usables",
	INVENTORYQUEST = "Misc",
	SELLCONFIRM = "Sell",
	RAWPRICE = "Raw Price",
	FOODDESCRIPT = "Food is used to feed workers. ",
	MONEYDESCRIPT = "Money is used to purchase goods and workers.",
	
	AREAISENDLESS = "This area has no progression",
	TOWNRETURN = "Return",
	
	#Confirms
	
	LEAVECONFIRM = "Leave to Main Menu? Unsaved progress will be lost. ",
	LOADCONFIRM = "Load this save file?",
	OVERWRITECONFIRM = "Overwrite this save file?",
	DELETECONFIRM = "Delete this save file?",
	STOPTASKCONFIRM = "Stop this job?",
	SLAVEREMOVECONFIRM = "Expel this worker?",
	
	
	#Inbuilt Tooltips
	PAUSEBUTTONTOOLTIP = 'Pause\nHotkey: 1',
	NORMALBUTTONTOOLTIP = 'Normal Speed\nHotkey: 2',
	FASTBUTTONTOOLTIP = 'Fast Speed\nHotkey: 3',
	
	
	
	
	#Skills
	SKILLATTACK = "Attack",
	SKILLATTACKDESCRIPT = "Attacks target with equipped weapon for %d damage. ",
	SKILLFIREBOLT = "Firebolt",
	SKILLFIREBOLTDESCRIPT = "Launches a fire spell on target. Deal %d Fire damage to all targets in same row.",
	SKILLWINDARROW = "Wind Arrow",
	SKILLWINDARROWDESCRIPT = "Imbues the arrow with Wind element and deal %d damage. Requires a bow equipped.",
	SKILLTAUNT = "Taunt",
	SKILLTAUNTDESCRIPT = "Forces enemy to attack you on its next turn and reduces its damage by 25% for 2 turns.",
	SKILLSLASH = "Slash",
	SKILLSLASHDESCRIPT = "Deals %d Weapon damage to all targets in nearby column. Requires a weapon equipped.",
	SKILLMINORHEAL = "Minor Heal",
	SKILLMINORHEALDESCRIPT = "Restore %d health of the target.",
	SKILLCONCENTRATE = "Concentrate",
	SKILLCONCENTRATEDESCRIPT = "Restore %d mana for self.",
	SKILLFIRESTORM = "Fire Storm",
	SKILLFIRESTORMDESCRIPT = "Deals %d fire damage to all enemies.",
	SKILLSTRONGSHOT = "Strong Shot",
	SKILLSTRONGSHOTDESCRIPT = "Deals %d Weapon damage to target enemy and stuns for 1 turn. Requires a bow equipped.",
	SKILLARROWSHOWER = "Arrow Shower",
	SKILLARROWSHOWERDESCRIPT = "Deals %d Weapon damage to all enemies.",
	SKILLTACKLE = "Tackle",
	SKILLTACKLEDESCRIPT = "Deals %d Physical damage and stuns target for 1 turn.",
	SKILLCRIPPLE = "Cripple",
	SKILLCRIPPLEDESCRIPT = "Deals %d Weapon damage and reduces target's damage by 33%% for 3 turns.",
	SKILLCOMBOATTACK = "Combo Attack",
	SKILLCOMBOATTACKDESCRIPT = "Deals 3 consecutive hits for %d Weapon damage to target. ",
	SKILLDOUBLEATTACK = "Double Attack",
	SKILLDOUBLEATTACKDESCRIPT= "Attacks for %d damage twice.",
	
	
	TASKHUNTING = "Hunt",
	TASKHUNTINGDESCRIPT = "Track down native wildlife for related resources.",
	TASKFISHING = "Fishing",
	TASKFISHINGDESCRIPT = "Fishing in a nearby waters for naval resources.",
	TASKWOODCUTTING = "Wood cutting",
	TASKWOODCUTTINGDESCRIPT = "Work in forests to gather wood materials.",
	TASKMINING = "Mining",
	TASKMININGDESCRIPT = "Use underground mines to gather rocks and metal.",
	TASKFARMING = "Farming",
	TASKFARMINGDESCRIPT = "Produce crops at farm.",
	TASKPROSTITUTION = "Prostitution",
	TASKPROSTITUTIONDESCRIPT = "Earn some gold by selling your body.",
	TASKCOOKING = "Cooking",
	TASKCOOKINGDESCRIPT = "Craft food related items. Must have crafting items selected. ",
	TASKTAILOR = "Tailor",
	TASKTAILORDESCRIPT = "Craft cloth and leather items and gear. Must have crafting items selected. ",
	TASKSMITH = "Smith",
	TASKSMITHDESCRIPT = "Craft metal items and gear. Must have crafting items selected. ",
	TASKALCHEMY = "Alchemy",
	TASKALCHEMYDESCRIPT = "Craft alchemical potions and items. Must have crafting items selected. ",
	TASKBUILDING = "Upgrading",
	TASKBUILDINGDESCRIPT = "Work on the currently active upgrade. ",
	
	TASKMAINSTAT = "Main characteristic",
	
	
	JOBPROSTITUTEGOLDDESCRIPT = "Earn gold by prostitution.",
	JOBCOOKINGCRAFTDESCRIPT = "Cook food at kitchen.",
	JOBBUILDCRAFTDESCRIPT = "Work on actie upgrade.",
	JOBSMITHCRAFTDESCRIPT = "Craft item at forge.",
	JOBTAILORCRAFTDESCRIPT = "Craft item at tailor workshop.",
	JOBALCHEMYCRAFTDESCRIPT = "Craft item at alchemy workshop.",
	
	
	SLAVEPARTNAME = "Name",
	SLAVEPARTSURNAME = "Surname",
	SLAVEPARTNICKNAME = "Nickname",
	SLAVEPARTRACE = "Race",
	SLAVEPARTAGE = "Age",
	SLAVEPARTSEX = "Sex",
	SLAVEPARTSKIN = "Skin Color",
	SLAVEPARTHAIR_COLOR = "Hair Color",
	SLAVEPARTHAIR_LENGTH = "Hair Length",
	SLAVEPARTHAIR_STYLE = "Hair Style",
	SLAVEPARTEARS = "Ears",
	SLAVEPARTEYE_COLOR = "Eye Color",
	SLAVEPARTEYE_SHAPE = "Eye Shape",
	SLAVEPARTTAIL = "Tail",
	SLAVEPARTHORNS = "Horns",
	SLAVEPARTWINGS = "Wings",
	SLAVEPARTHEIGHT = "Height",
	SLAVEPARTARMS = "Arms",
	SLAVEPARTLEGS = "Legs",
	SLAVEPARTPENIS_SIZE = 'Penis Size',
	SLAVEPARTPENIS_TYPE = 'Penis Shape',
	SLAVEPARTBALLS_SIZE = "Testicle Size",
	SLAVEPARTASS_SIZE = "Butt Size",
	SLAVEPARTTITS_SIZE = "Breast Size",
	SLAVEPARTVAGINAL_VIRGIN = "Vaginal Virgin",
	SLAVEPARTANAL_VIRGIN = "Anal Virgin",
	SLAVEPARTPENIS_VIRGIN = "Penis Virgin",
	
	
	#Bodyparts
	
	SIZETINY = "Tiny",
	SIZEPETITE = "Petite",
	SIZESHORT = "Short",
	SIZEAVERAGE = "Average",
	SIZETALL = "Tall",
	SIZETOWERING = "Towering",
	SIZESMALL = "Small",
	SIZEBIG = "Big",
	
	SLAVESEXMALE = "Male",
	SLAVESEXFEMALE = "Female",
	SLAVESEXFUTA = "Futa",
	SLAVEAGETEEN = "Teen",
	SLAVEAGEADULT = "Young Adult",
	SLAVEAGEMATURE = "Mature",
	
	SLAVEAGETEENDESCRIPT = "[He]'s a [color=aqua]teenage [boy][/color] of the [url=race][color=yellow][raceadj] race[/color][/url].",
	SLAVEAGEADULTDESCRIPT = "[He]'s a [color=aqua]young adult [male][/color] of the [url=race][color=yellow][raceadj] race[/color][/url].",
	SLAVEAGEMATUREDESCRIPT = "[He]'s a [color=aqua]matured [male][/color] of the [url=race][color=yellow][raceadj] race[/color][/url].",
	
	SLAVEBODYHUMANOID = "Humanoid",
	SLAVEBODYBESTIAL = "Bestial",
	SLAVEBODYSHORTSTACK = "Shortstack",
	SLAVEBODYJELLY = "Jelly",
	SLAVEBODYHALFBIRD = "Half-bird",
	SLAVEBODYHALFSNAKE = "Half-snake",
	SLAVEBODYHALFFISH = "Half-fish",
	SLAVEBODYHALFSPIDER = "Half-spider",
	SLAVEBODYHALFHORSE = "Half-horse",
	SLAVEBODYHALFSQUID = "Half-squid",
	
	SLAVEBODYHUMANOIDDESCRIPT = "",
	SLAVEBODYBESTIALDESCRIPT = "",
	SLAVEBODYSHORTSTACKDESCRIPT = "[His] body is rather [color=yellow]petite[/color], about half the size of the average person.",
	SLAVEBODYJELLYDESCRIPT = "[His] body is [color=yellow]jelly-like[/color] and partly transparent.",
	SLAVEBODYHALFBIRDDESCRIPT = "[His] body has [color=yellow]wings for arms and avian legs[/color] making everyday tasks difficult.",
	SLAVEBODYHALFSNAKEDESCRIPT = "The lower portion of [his] body consists of a long-winding [color=yellow]snake’s tail[/color].",
	SLAVEBODYHALFFISHDESCRIPT = "[His] body is [color=yellow]scaly and sleek[/color], possessing fins and webbed digits.",
	SLAVEBODYHALFSPIDERDESCRIPT = "The lower portion of [his] body consists of a [color=yellow]spider's legs and abdomen[/color].",
	SLAVEBODYHALFHORSEDESCRIPT = "While [his] upper body is human, [his] lower body is [color=yellow]equine[/color] in nature.",
	SLAVEBODYHALFSQUIDDESCRIPT = "The lower portion of [his] body consists of a [color=yellow]number of tentacular appendages[/color], similar to those of an octopus.",
	
	
	
	
	
	TOOLTIPBASEEXP = "Character's unspent experience. Can be used to unlock classes.",
	TOOLTIPOBEDIENCE = "Obedience represents the character's willingness to work for you. If both obedience and fear drop too low, the character might stop following orders or even escape. Obedience is gained by praises and rewards. ",
	TOOLTIPFEAR = "Fear represents the character's awe towards you and your orders. If both obedience and fear drop too low, the character might stop following orders or even escape. Fear is gained from punishments and abusive behavior. ",
	TOOLTIPLUST = "Lust increases with time and allows the use of specific skills. Lust can be a powerful control and resource tool when approached correctly.",
	TOOLTIPENERGY = "Energy is restored during sleep and is required for task productions. When character is forced to work with no energy left, they accomodate Exhaustion. ",
	TOOLTIPFATIGUE = "Fatigue increases with time and dissipates with entertaining activities. When unmanaged may cause performance penalty.",
	TOOLTIPEXHAUSTION = "Exhaustion grows when character is forced to work with no energy left. Exhaustion causes penalty to maximum health and production, and can lead to fatal cause if not taken care of for a long time.",
	TOOLTIPLOYAL = "Loyalty represents character's willingness to follow master's orders even they neither obedient, nor fearful. It grows with time and stops servants from escaping. ",
	
	TOOLTIPSEXTRAITS = "Sexual traits are a special bonuses which provide benefits during the interaction sequence. ",
	
	TOOLTIPHP = "",
	TOOLTIPMANA = "",
	
	STATHP = "Health",
	STATHPMAX = "Max. Health",
	STATMP = "Mana",
	STATMPMAX = "Max. Mana",
	STATHITRATE = "Hit chance",
	
	STATPHYSICS = "Physical",
	STATWITS = "Wits",
	STATCHARM = "Charm",
	STATSEXUALS = "Sexuals",
	
	STATPHYSICSDESCRIPT = "Physical represent character's muscles and reflexes. The higher it is, the more effective combat and manual labor tasks are. Grows with physical labor. ",
	STATWITSDESCRIPT = "Wits represent character's mind quickness and intelligence. High Wits are mandatory for stronger Mage classes and crafters. ",
	STATCHARMDESCRIPT = "Charm represents character's appeal and appearance. High Charm makes social oriented works and skills a lot more effective. ",
	STATSEXUALSDESCRIPT = "Sexuals represent character's skills in body pleasures. High Sexuals make sexual skill and tasks a lot more effective. Sexuals also increase Lust cap. ",
	
	STATGROWTH_FACTOR = "Growth",
	STATMAGIC_FACTOR = "Magic Affinity",
	STATPHYSICS_FACTOR = "Body Factor",
	STATWITS_FACTOR = "Wits Factor",
	STATCHARM_FACTOR = "Charm Factor",
	STATSEXUALS_FACTOR = "Sexuals Factor",
	STATTAME_FACTOR = "Tame Factor",
	STATBRAVE_FACTOR = "Brave Factor",
	
	
	
	
	
	STATGROWTH_FACTORDESCRIPT = "Growth factor represents how easy it is for the character to acquire a new class. The higher it is, the less experience unlocking new class will take until soft cap limit.",
	STATPHYSICS_FACTORDESCRIPT = "Body factor represents physical potential of the character. It limits [color=aqua]Physical[/color] growth and influences melee combat.",
	STATMAGIC_FACTORDESCRIPT = "Magic factor represents character's magic affinity. The higher it is, the more mana you have and the stronger magic classes you can unlock. Also influences spell effects and damage. ",
	STATTAME_FACTORDESCRIPT = "Tame factor represents how easy is to befriend the character. The higher it is, the slower Obedience decays. ", 
	STATBRAVE_FACTORDESCRIPT = "Brave factor represents how hard is to keep character in Fear. The higher it is, the quicker Fear decays. ",
	STATWITS_FACTORDESCRIPT = "Wits factor represents character's mind potential. It limits [color=aqua]Wits[/color] growth.",
	STATCHARM_FACTORDESCRIPT = "Charm factor represents character's appeal potential. It limits [color=aqua]Charm[/color] growth.",
	STATSEXUALS_FACTORDESCRIPT = "Sex factor represents character's sex development potential. It limits [color=aqua]Sexuals[/color] growth.",
	
	STATFOOD_LOVE = "When favorite food is eaten, it gives minor boost to obedience and reduces fatigue. Food made of both loved and hated ingredients will be considered as neutral and give no bonus or penalty. ",
	STATFOOD_HATE = "When hated food is eaten, it will increase fatigue. Food made of both loved and hated ingredients will be considered as neutral and give no bonus or penalty.",
	
	
	
	
	
	
	RACEHUMAN = "Human",
	RACEHUMANADJ = "Human",
	RACEELF = "Elf",
	RACEELFADJ = "Elven",
	RACEDARKELF = "Dark Elf",
	RACEDARKELFADJ = "Dark Elven",
	RACEDROW = "Drow",
	RACEDROWADJ = "Drow",
	RACEORC = "Orc",
	RACEORCADJ = "Orc",
	RACEGOBLIN = "Goblin",
	RACEGOBLINADJ = "Goblin",
	RACEDWARF = "Dwarf",
	RACEDWARFADJ = "Dwarven",
	RACEGNOME = "Gnome",
	RACEGNOMEADJ = "Gnome",
	RACEFAIRY = "Fairy",
	RACEFAIRYADJ = "Fairy",
	RACEDRYAD = "Dryad",
	RACEDRYADADJ = "Dryad",
	RACEDEMON = "Demon",
	RACEDEMONADJ = "Demon",
	RACESERAPH = "Seraph",
	RACESERAPHADJ = "Seraph",
	RACEDRAGONKIN = "Dragonkin",
	RACEDRAGONKINADJ = "Dragonkin",
	RACECENTAUR = "Centaur",
	RACECENTAURADJ = "Centaur",
	RACETAURUS = "Taurus",
	RACETAURUSADJ = "Taurus",
	RACEHARPY = "Harpy",
	RACEHARPYADJ = "Harpy",
	RACESLIME = "Slime",
	RACESLIMEADJ = "Slime",
	RACELAMIA = "Lamia",
	RACELAMIAADJ = "Lamia",
	RACEARACHNA = "Arachna",
	RACEARACHNAADJ = "Arachna",
	RACESCYLLA = "Scylla",
	RACESCYLLAADJ = "Scylla",
	RACENEREID = "Nereid",
	RACENEREIDADJ = "Nereid",
	
	RACEBEASTKINCAT = "Beast Cat",
	RACEBEASTKINCATADJ = "Beast Cat",
	RACEBEASTKINWOLF = "Beast Wolf",
	RACEBEASTKINWOLFADJ = "Beast Wolf",
	RACEBEASTKINFOX = "Beast Fox",
	RACEBEASTKINFOXADJ = "Beast Fox",
	RACEBEASTKINBUNNY = "Beast Bunny",
	RACEBEASTKINBUNNYADJ = "Beast Bunny",
	RACEBEASTKINTANUKI = "Beast Tanuki",
	RACEBEASTKINTANUKIADJ = "Beast Tanuki",
	
	RACEHALFKINCAT = "Half-Breed Cat",
	RACEHALFKINCATADJ = "Half-Breed Cat",
	RACEHALFKINWOLF = "Half-Breed Wolf",
	RACEHALFKINWOLFADJ = "Half-Breed Wolf",
	RACEHALFKINFOX = "Half-Breed Fox",
	RACEHALFKINFOXADJ = "Half-Breed Fox",
	RACEHALFKINBUNNY = "Half-Breed Bunny",
	RACEHALFKINBUNNYADJ = "Half-Breed Bunny",
	RACEHALFKINTANUKI = "Half-Breed Tanuki",
	RACEHALFKINTANUKIADJ = "Half-Breed Tanuki",
	
	RACEHUMANDESCRIPT = "Humans are one of the most common races. Their strength comes in numbers and flexibility, but they generally are rather weak in magic and have low potential growth with only few exceptional humans can show outstanding feats. \n\nHuman society is rather open to others but also quick to anger and strike wars even among themselves. While some might act prudish, especially on public, humans in general are very sexually active and do not stray from other humanoid races. ",
	RACEELFDESCRIPT = "Elves prefer living in the forests being close to nature with other naturistic races like Dryads and Fairies. They are adept in magic, but their physical strength is fairly mediocre. \n\nElven society is fairly secluded but isn't above contacting and trading with other races. Elves rarely show vivid intereset in sex outside of their social group, and often prefer life-long relationship, but still are considered very appealing and attractive by other races making a popular demand as slaves.",
	RACEDARKELFDESCRIPT = "A rarer version of elves with distinct dark skin. Dark elves mostly inhabit southern regions and show a numerous differences to their common counterparts. They are less prone to magic but possess stronger bodies.\n\nHowever, their society (often separated into tribes) is more secluded and hostile to outsiders, but they are aslo more open to sex than normal elves.   ",
	RACEDROWDESCRIPT = "A rare subspecie of elves propagated and trained for combat. Thier blueish skin and rare eye colors make them very noticeable and force them to hide their bodies in clothes. Being adepts in both physical techniques and magic, they often happen to be a trained assassins, combatants and sellswords. However, they are not able to breed with other species and having no real society they have to desperately seek out each other for the purpose of procreation. Due to it, their sexual activity is the highest among all elves. ",
	RACEORCDESCRIPT = "Orcs are semi-sapient race of brutes inhabitating many deserted and badland regions. Orcs resemble large, greenish humanoids with strong bodies and bad temper. Despite that some orcs are rather capable of fitting into normal society or work as simple bodyguards and soldiers. \n\nCmmonly orcs form tribes and aren't above killing each other or any stray groups they deem dangerous. They are also rather fond of forcefully using members of other races for sex, but aren't really capable of interbreeding with them. ",
	RACEGOBLINDESCRIPT = "Goblins are a short humanoids often occupying caves and dungeons. Most goblins are outright hostile to all outsiders and prefer stick in groups, as their individual power is fairly low, but certain amount of goblins have abandoned their initial groups and strived to live with other races sometimes even becoming a known adventurers, but more often being used for crude work, since they are hardly remarkable at anything except for their libido. ",
	RACEGNOMEDESCRIPT = "Gnomes are a rare species of short, intelligent humanoids. Their poor physical strength makes them rather poor workers or fighters, but they posses some magical capabilities with good amount of charisma and easy time connecting with other races. Many gnomes find their place as traders or entertainers, but good amount is pretty happy to serve at more lewd occupations... assuming they can find the demand. ",
	RACEDWARFDESCRIPT = "Dwarves are a short, stout humanoid race, prefering to live by strict set of rules and encloused underground society. Dwarves are rather physically strong and can be a quick to anger, but they rarely fit for magic tasks. ",
	RACEDRYADDESCRIPT = "Dryads are a rare species of forest humanoids possessing green skin and being covered in plant matter. They rarely engage into communication with other races and generally prefer to stick to their home. Despite that, they are quite capable of fighting and using magic.",
	RACEFAIRYDESCRIPT = "Fairies are a curious children of the forests. Looking like a half-sized humanoids with a pair of insect wings on the back, fairies possess little physical danger, but their natural magic affinity is increadiably high. Thankfully they rarely master it delibirately, prefering instead just having fun and be quick to flee. Despite their childish temper, fairies are very proactive or even omnivorous when it comes down to bodily pleasures not unlike their cave counteparts - goblins.",
	RACEDEMONDESCRIPT = "Demons is a humanoid race came from outer planes. They can be easily distinguished by their horns, leather wings and animalistic eyes. Their magic and physical powers both are capable reaching unusual height when compared to mortals and their temper is on par with it. Demons can be both a dangerous enemy or a mighty ally in case you actually manage to tame one. ",
	RACESERAPHDESCRIPT = "Seraphs are angel-like beings, possessing a pair of white wings. Their character match their pure appearance. While their strength is not very high, they are quite capable of magic. ",
	RACEDRAGONKINDESCRIPT = "An extremely rare bred of humanoid and dragon. Their dragon ancestry provide them with great strength and magic powers. ",
	RACETAURUSDESCRIPT = "Taurus are humanoid race with cow-like features. They exceel in raw strength but are subpar in other fields.",
	RACECENTAURDESCRIPT = "The Centaur race is somewhat distant, yet not unheard of in southern regions. Some individuals have made it very far by adopting a nomadic lifestyle, making the race common enough to be recognized by most. The centauri population is relatively small, due to dealing with territorial oppression from humanoid races.",
	RACEHARPYDESCRIPT = "Harpies are human-bird hybrids with easily recognisable features, such as their feathered arms and avian lower quarters. Commonly seen as monsters, they have existed since time immemorial. Wild harpies generally inhabit mountain regions and are relatively aggressive. Their intelligence has a wide range, and people have had some success making them into slave-pets.",
	RACESLIMEDESCRIPT = "Some slimes have managed to evolve beyond their usual state and are capable of holding soul of living being. Taking the look of humanoid they even able to develop speech skills and eventually acquire personality. Their bodies still capable of unusual properties but they are considerably better at controlling it at will. ",
	RACELAMIADESCRIPT = "Lamias are easily recognized and tend to be timid in their interactions, rarely showing themselves to majority of the population. Their population has been severely reduced by hunting and extermination expeditions launched by different races. Lamias are surprisingly intelligent, as the few captured and studied samples have shown.",
	RACESCYLLADESCRIPT = "Scylla are rather unusual in appearance, possessing a number of tentacle-like appendages they use in the place of legs. They generally prefer damp and aquatic regions. In general, their behavior and capabilities are not much different from lamia. Their appearance is extremely rare, to the point of being treated as mere myth or drunken fancy by some.",
	RACEARACHNADESCRIPT = "Arachna live in isolation and tend to choose caves and other underground locations as their homes. While not being especially aggressive, they are fearsome hunters and have been reported for rare night attacks on both cattle and humans.",
	RACENEREIDESCRIPT = "Nereid are considered to be another subspecies of the humanoid races, yet they likely split from another race in the distant past. They adapted to an aquatic lifestyle. Nereids are often seen by sailors and fishermen, but they tend to be hesitant in making contact with humans, likely viewing them as a threat.",
	RACEBEASTKINDESCRIPT = "Beastkin is a term referred to multiple humanoid-animal races usually of mammal origins. They tend to be covered in fur, having slightly more bestial body structure. However their height and behavior is that of a humans, somehow allows them to breed with humans and elves resulting in a halfkin hybrids. ",
	RACEHALFKINDESCRIPT = "Halfkin are Beastkin's hybrids which keep some of their parent's animalistic feature but appear much more humane, lacking fur and having adequate human body. Halfkins are often rejected by their Beastkin parent's race, but often manage to fit into society of the other one. Despite that, they still tend to inherit some of their race's talents usually being rather different from normal members. ",
	RACEBEASTKINCATDESCRIPT = "Cat folk are an unusually social breed of Beastkin, having no known settlements of their own, and living quite openly in populous towns and cities. They have a great deal of popularity among certain crowds for their lush appearance and lascivious nature.",
	RACEBEASTKINWOLFDESCRIPT = "Unlike other Beastkin, Wolves are not viewed as simple novelties, but are treated as the powerful, agile pack hunters they are. Though they rarely show hostility towards outsiders unless threatened, great caution should be taken when dealing with them.",
	RACEBEASTKINFOXDESCRIPT = "Fox folk are a rare, and relatively mysterious breed of Beastkin. They display high intelligence, a tendency towards lifelong monogamy, and congregate in small, close-knit communities.",
	RACEBEASTKINBUNNYDESCRIPT = "Bunnies are one of the least self-sufficient, but netherless common beast races. They are not aggressive and can actually be quite timid. They are quite well liked  due to their comforting appearance and their natural lewdness makes them a popular choice for slave pets.",
	RACEBEASTKINTANUKIDESCRIPT = "The Tanuki are a rare beast race possessing raccoon features. It's hard to pinpoint any specific mental differences between them and the majority of the humanoid races. Some say that their behavior and attitudes are much like that of the average human.",
	RACEHALFKINCATDESCRIPT = "Cat folk are an unusually social breed of Beastkin, having no known settlements of their own, and living quite openly in populous towns and cities. They have a great deal of popularity among certain crowds for their lush appearance and lascivious nature.",
	RACEHALFKINWOLFDESCRIPT = "Unlike other Beastkin, Wolves are not viewed as simple novelties, but are treated as the powerful, agile pack hunters they are. Though they rarely show hostility towards outsiders unless threatened, great caution should be taken when dealing with them.",
	RACEHALFKINFOXDESCRIPT = "Fox folk are a rare, and relatively mysterious breed of Beastkin. They display high intelligence, a tendency towards lifelong monogamy, and congregate in small, close-knit communities.",
	RACEHALFKINBUNNYDESCRIPT = "Bunnies are one of the least self-sufficient, but netherless common beast races. They are not aggressive and can actually be quite timid. They are quite well liked  due to their comforting appearance and their natural lewdness makes them a popular choice for slave pets.",
	RACEHALFKINTANUKIDESCRIPT = "The Tanuki are a rare beast race possessing raccoon features. It's hard to pinpoint any specific mental differences between them and the majority of the humanoid races. Some say that their behavior and attitudes are much like that of the average human.",
	
	SKILLPRAISE = "Praise",
	SKILLPRAISEDESCRIPT = "A basic tool for obedience improval. Increases obedience slightly.",
	SKILLWARN = "Warn",
	SKILLWARNDESCRIPT = "A basic tool for fear instigation. Increases fear slightly.",
	SKILLPUNISH = "Punish",
	SKILLPUNISHDESCRIPT = "Hit them very hard. Increases fear.",
	SKILLREWARD = "Reward",
	SKILLREWARDDESCRIPT = "Buying their respect might seem line an easy solution... as long as you have enough coin. Increases obedience greatly.",
	SKILLREWARDSEX = "Reward with sex",
	SKILLREWARDSEXDESCRIPT = "Give them some attention as your goodwill... As long as they seek for it. Increases obedience greatly. Can only be used on lustful targets.",
	SKILLSEDUCE = "Seduce",
	SKILLSEDUCEDESCRIPT = "By pushing right buttons you can not only make them horny, but also follow your orders. Maximizes lust and increases obedience. Can be resisted",
	SKILLGREATSEDUCE = "Great Seduce",
	SKILLGREATSEDUCEDESCRIPT = "A dangerous art which can make victim instantaneously fall in love. Maximizes lust, obedience and boost loyalty. Can be resisted.",
	SKILLDRAIN = "Drain",
	SKILLDRAINDESCRIPT = "Restores some fatigue, mana and energy by draining it from target.",
	SKILLSERVE = "Serve",
	SKILLSERVEDESCRIPT = "Help them out and make them feel relaxed while at it. Improves target's obedience and reduces fatigue. ",
	SKILLDISCIPLINE = "Discipline",
	SKILLDISCIPLINEDESCRIPT = "Boosts target's manual labor performance. ",
	SKILLSEDATE = "Sedate",
	SKILLSEDATEDESCRIPT = "Puts target's mind at ease. Improves Obedience",
	SKILLFEAR = "Fear",
	SKILLFEARDESCRIPT = "Strikes fear into target's mind.",
	SKILLINNERVATE = "Innervate",
	SKILLINNERVATEDESCRIPT = "Restores target's energy.",
	SKILLSHACKLE = "Shackle",
	SKILLSHACKLEDESCRIPT = "Creates a magic shackles around target. As long as they persist, it will be unable to escape. Shackles can be dispelled with time if target's magic resistance is high. ",
	SKILLGREATSHACKLE = "Great Shackle",
	SKILLGREATSHACKLEDESCRIPT = "Creates a stronger version of magical shackles which are a lot harder to break.",
	SKILLMINDCONTROL = "Mind Control",
	SKILLMINDCONTROLDESCRIPT = "Overwhelms target's mind forcing a nearly complete submission. Can be resisted with powerful mind. ",
	
	PROFMASTER = "Master",
	PROFMASTERALT = "Mistress",
	PROFMASTERDESCRIPT = "The sole ruler of domain. $His power strike fear and respect even in those who are only joined recently.\n\nPraises and punishments twice as effective.",
	PROFRULER = "Ruler",
	PROFRULERDESCRIPT = "You decided to step up from being only a $master. ",
	PROFDIRECTOR = "Director",
	PROFDIRECTORDESCRIPT = "Director can issue a higher tier discipline on the servants in name of the master. ",
	PROFSADIST = "Sadist",
	PROFSADISTDESCRIPT = "Some people find it pleasant to relieve in pain of others. ",
	PROFWATCHDOG = "Watchdog",
	PROFWATCHDOGDESCRIPT = "The servants, who proven their loyal to master are allowed to act in his name to instigate obedience of others.",
	PROFHEADGIRL = "Headgirl",
	PROFHEADGIRLALT = "Headman",
	PROFHEADGIRLDESCRIPT = "The servant with higher authority is allowed to direct multiple lower servants at once.\n\nPraises and punishements 1.5 times as effective",
	PROFTRAINER = "Trainer",
	PROFTRAINERDESCRIPT = "Trainers can dramatically change the attitude of even very rebellious slave. ",
	PROFWORKER = "Worker",
	PROFWORKERDESCRIPT = "Workers are great manual laborers for your everyday needs. You won't need them to gather resources, but they will do it much faster. \n\nManual labor tasks efficieny +50%.",
	PROFFOREMAN = "Foreman",
	PROFFOREMANDESCRIPT = "A seasoned worker can not only show higher proficiency, but also boost productivity of other workers.\n\nManual labor tasks efficieny +33%.",
	PROFHUNTER = "Hunter",
	PROFHUNTERDESCRIPT = "Hunters specialize in tracking and killing the game. \n\nIncreases Hunting productivity by 50%. Allows to use Bows.",
	PROFSMITH = "Blacksmith",
	PROFSMITHDESCRIPT = "Smiths are mandatory when dealing with metalcrafting. \n\nAllows to craft metal items.",
	PROFCHEF = "Chef",
	PROFCHEFDESCRIPT = "A skilled cook is always a valuable addition to a growing group. \n\nCooking efficiency +50%.",
	PROFATTENDANT = "Attendant",
	PROFATTENDANTDESCRIPT = "Sometimes it's very valuable to have someone packed with nice stuff and free time on their hands.\n\nMost items can be used instantly in combat.",
	PROFALCHEMIST = "Alchemist",
	PROFALCHEMISTDESCRIPT = "Alchemists specialize in brewing processes which is invaluable for steady potion supplies. \n\nPotion brewing efficiency +200%.",
	PROFCATTLE = "Cattle",
	PROFCATTLEDESCRIPT = "Some people are just not cut out for anything better...\n\nIncreases farm task efficiency by 50%.",
	PROFBREEDER = "Breeder",
	PROFBREEDERDESCRIPT = "When you really want to emphasize on their purpose. \n\nIncreases farm task efficiency by additional 50%. Pregnancies last 50% less. Allows impregnations by any race. Offspring will inherit only character's stats. ",
	PROFHARLOT = "Harlot",
	PROFHARLOTDESCRIPT = "The eldest profession might not seem as much, but so far it's been always in demand.\n\nProstitution tasks are 50% more efficient.",
	PROFGEISHA = "Geisha",
	PROFGEISHADESCRIPT = "",
	PROFDANCER = "Dancer",
	PROFDANCERDESCRIPT = "Dancers can entice with their looks and moves. Effective for entertainement but not for the clumsy. ",
	PROFSUCCUBUS = "Succubus",
	PROFSUCCUBUSALT = "Incubus",
	PROFSUCCUBUSDESCRIPT = "Being a sex fiend is a tiresome, but undeniably noble occupation.\n\nSexual Rewards are twice as effective. Fatigue is alleviated from sex.",
	PROFTRUE_SUCCUBUS = "True Succubus",
	PROFTRUE_SUCCUBUSALT = "True Incubus",
	PROFTRUE_SUCCUBUSDESCRIPT = "You've just embraced your real inner self.\n\nSexual Rewards are twice as effective. Fatigue is alleviated from sex.",
	PROFPET = "Pet",
	PROFPETDESCRIPT = "Apparently, giving up your personal rights is not the worst thing in the world, even if you have to wear rather dubious garment.\n\nSexual Rewards are 1.5 times as effective.",
	PROFPETBEAST = "Pet",
	PROFPETBEASTDESCRIPT = "Deep inside you always just wished for nothing but a good master.\n\nSexual Rewards are 1.5 times as effective.",
	PROFSEXTOY = "Sex toy",
	PROFSEXTOYDESCRIPT = "The art of being an object of desire for others.\n\nSexual Rewards are twice as effective. Prostitution efficiency +50%.",
	PROFFIGHTER = "Fighter",
	PROFFIGHTERDESCRIPT = "You've had a dream of becoming a skilled adventurer. This might be a good first step. \n\nAllows the use of weapon and armor.",
	PROFKNIGHT = "Knight",
	PROFKNIGHTDESCRIPT = "A noble fighter ready to serve his master.",
	PROFAPPRENTICE = "Apprentice",
	PROFAPPRENTICEDESCRIPT = "After spending a good amount of time at the libraries you finally managed to show some magic potential.",
	PROFHEALER = "Healer",
	PROFHEALERDESCRIPT = "Focusing on defensive magic you managed to develop the tools suitable for this task, as well as your body.",
	PROFCASTER = "Caster",
	PROFCASTERDESCRIPT = "Long periods of practice have finally paid back. You've managed to sieze a greater power of arcane.",
	PROFDOMINATOR = "Dominator",
	PROFDOMINATORDESCRIPT = "You've always prefered a sly approach to a flashy one. There's no better solution for conflicts, than forcing others to do what you want. ",
	PROFBLOODMAGE = "Blood Mage",
	PROFBLOODMAGEDESCRIPT = "",
	
	PROFMAID = "Maid",
	PROFMAIDALT = "Butler",
	PROFMAIDDESCRIPT = "A trained servant not only knows their place but also is better to the eye.",
	PROFDRAGONKNIGHT = "Dragon Knight",
	PROFDRAGONKNIGHTDESCRIPT = "The dragon blood flowing in their veins allow them become a fearsome warriors resistant to fire.",
	PROFBERSERKER = "Berserker",
	PROFBERSERKERDESCRIPT = "",
	PROFDRUID = "Druid",
	PROFDRUIDDESCRIPT = "",
	PROFVALKYRIE = "Valkyrie",
	PROFVALKYRIEDESCRIPT = "",
	PROFSOULEATER = "Soul Eater",
	PROFSOULEATERDESCRIPT = "",
	PROFNECROMANCER = "Necromancer",
	PROFNECROMANCERDESCRIPT = "",
	PROFARCHER = "Archer",
	PROFARCHERDESCRIPT = "",
	PROFSNIPER = "Sniper",
	PROFSNIPERDESCRIPT = "",
	PROFROGUE = "Rogue",
	PROFROGUEDESCRIPT = "",
	PROFASSASSIN = "Assassin",
	PROFASSASSINDESCRIPT = "",
	
	UPGRADENEXTBONUS = "Upgrade bonus: ",
	
	UPGRADEFARM_VEGETABLES = "Farm: Vegetables",
	UPGRADEFARM_VEGETABLESDESCRIPT = "Upgrades your farm plot.",
	UPGRADEFARMVEGEBONUS = "Allows gathering of Vegetables",
	UPGRADEFARM_GRAINS = "Farm: Grains",
	UPGRADEFARM_GRAINSDESCRIPT = "Upgrades your farm plot",
	UPGRADEFARMGRAINSBONUS = "Allows gathering of Grains",
	UPGRADETAILOR = "Tailor Workshop",
	UPGRADETAILORDESCRIPT = "Allows production of cloth and leather gear",
	UPGRADEFORGE = "Forge",
	UPGRADEFORGEDESCRIPT = "Allows production of metal parts and gear",
	UPGRADEMINE_RESOURCE = "Mine: Resources",
	UPGRADEMINE_RESOURCEDESCRIPT = "Allows harvesting of additional resources from Mining",
	UPGRADEWOOD_RESOURCE = "Wood: Resources",
	UPGRADEWOOD_RESOURCEDESCRIPT = "Allows harvesting of additional resources from Wood Cutting",
	
	
	BODYPARTAGETEEN = "teen",
	BODYPARTAGEADULT = "adult",
	BODYPARTAGEMATURE = "mature",
	BODYPARTBODY_SHAPEHUMANOID = "humanoid",
	BODYPARTBODY_SHAPEBESTIAL = "bestial",
	BODYPARTBODY_SHAPESHORTSTACK = "shortstack",
	BODYPARTBODY_SHAPEJELLY = "jelly",
	BODYPARTBODY_SHAPEHALFBIRD = "half-bird",
	BODYPARTBODY_SHAPEHALFSNAKE = "half-snake",
	BODYPARTBODY_SHAPEHALFFISH = "half-fish",
	BODYPARTBODY_SHAPEHALFSPIDER = "half-spider",
	BODYPARTBODY_SHAPEHALFHORSE = "half-horse",
	BODYPARTBODY_SHAPEHALFSQUID = "half-squid",
	BODYPARTHAIR_LENGTHEAR = "ear",
	BODYPARTHAIR_LENGTHNECK = "neck",
	BODYPARTHAIR_LENGTHSHOULDER = "shoulder",
	BODYPARTHAIR_LENGTHWAIST = "waist",
	BODYPARTHAIR_LENGTHHIPS = "hips",
	BODYPARTHAIR_STYLESTRAIGHT = "straight",
	BODYPARTHAIR_STYLEPONYTAIL = "ponytail",
	BODYPARTHAIR_STYLEPIGTAILS = "pigtails",
	BODYPARTHAIR_STYLEBRAID = "braid",
	BODYPARTHAIR_STYLETWINBRAIDS = "twin braids",
	BODYPARTHAIR_STYLEBUN = "bun",
	BODYPARTEYE_COLORDEFAULT = "default",
	BODYPARTEYE_SHAPENORMAL = "normal",
	BODYPARTEYE_SHAPESLIT = "slit",
	BODYPARTHORNSSHORT = "short",
	BODYPARTHORNSSTRAIGHT = "straight",
	BODYPARTHORNSCURVED = "curved",
	BODYPARTEARSHUMAN = "human",
	BODYPARTEARSELVEN = "elven",
	BODYPARTEARSORCISH = "orcish",
	BODYPARTEARSCAT = "cat",
	BODYPARTEARSWOLF = "wolf",
	BODYPARTEARSFOX = "fox",
	BODYPARTEARSBUNNY_STANDING = "bunny standing",
	BODYPARTEARSBUNNY_DROOPING = "bunny drooping",
	BODYPARTEARSTANUKI = "tanuki",
	BODYPARTEARSDEMON = "demon",
	BODYPARTEARSCOW = "cow",
	BODYPARTEARSFEATHERED = "feathered",
	BODYPARTEARSFISH = "fish",
	BODYPARTSKINPALE = "pale",
	BODYPARTSKINGREY = "grey",
	BODYPARTSKINFAIR = "fair",
	BODYPARTSKINOLIVE = "olive",
	BODYPARTSKINTAN = "tan",
	BODYPARTSKINBROWN = "brown",
	BODYPARTSKINDARK = "dark",
	BODYPARTSKINSLIME = "slime",
	BODYPARTSKINBLUE = "blue",
	BODYPARTSKINPALEBLUE = "paleblue",
	BODYPARTSKINGREEN = "green",
	BODYPARTSKINRED = "red",
	BODYPARTSKINPURPLE = "purple",
	BODYPARTSKINTEAL = "teal",
	BODYPARTSKIN_COVERAGEPLANT = "plant",
	BODYPARTSKIN_COVERAGESCALE = "scale",
	BODYPARTSKIN_COVERAGEFEATHERS = "feathers",
	BODYPARTSKIN_COVERAGEFUR_WHITE = "white fur",
	BODYPARTSKIN_COVERAGEFUR_GREY = "grey fur",
	BODYPARTSKIN_COVERAGEFUR_BROWN = "brown fur",
	BODYPARTSKIN_COVERAGEFUR_STRIPED = "striped fur",
	BODYPARTSKIN_COVERAGEFUR_BLACK = "black fur",
	BODYPARTSKIN_COVERAGEFUR_ORANGE = "orange fur",
	BODYPARTSKIN_COVERAGEFUR_ORANGE_WHITE = "fox fur",
	BODYPARTWINGSFEATHERED_BLACK = "black feathered",
	BODYPARTWINGSSERAPH = "seraph",
	BODYPARTWINGSFEATHERED_BROWN = "brown feathered",
	BODYPARTWINGSFAIRY = "fairy",
	BODYPARTWINGSDEMON = "demon",
	BODYPARTWINGSDRAGON = "dragon",
	BODYPARTWINGSLEATHER_BLACK = "black leather",
	BODYPARTWINGSLEATHER_RED = "red leather",
	BODYPARTTAILCAT = "cat",
	BODYPARTTAILFOX = "fox",
	BODYPARTTAILWOLF = "wolf",
	BODYPARTTAILBUNNY = "bunny",
	BODYPARTTAILTANUKI = "tanuki",
	BODYPARTTAILCOW = "cow",
	BODYPARTTAILDEMON = "demon",
	BODYPARTTAILDRAGON = "dragon",
	BODYPARTTAILAVIAN = "avian",
	BODYPARTTAILFISH = "fish",
	BODYPARTTAILSNAKE = "snake",
	BODYPARTTAILTENTACLES = "tentacles",
	BODYPARTTAILHORSE = "horse",
	BODYPARTTAILSPIDER = "spider",
	BODYPARTHEIGHTTINY = "tiny",
	BODYPARTHEIGHTPETITE = "petite",
	BODYPARTHEIGHTSHORT = "short",
	BODYPARTHEIGHTAVERAGE = "average",
	BODYPARTHEIGHTTALL = "tall",
	BODYPARTHEIGHTTOWERING = "towering",
	BODYPARTTITS_SIZEFLAT = "flat",
	BODYPARTTITS_SIZESMALL = "small",
	BODYPARTTITS_SIZEAVERAGE = "average",
	BODYPARTTITS_SIZEBIG = "big",
	BODYPARTTITS_SIZEHUGE = "huge",
	BODYPARTTITS_SIZEMASCULINE = "masculine",
	BODYPARTASS_SIZEFLAT = "flat",
	BODYPARTASS_SIZESMALL = "small",
	BODYPARTASS_SIZEAVERAGE = "average",
	BODYPARTASS_SIZEBIG = "big",
	BODYPARTASS_SIZEHUGE = "huge",
	BODYPARTASS_SIZEMASCULINE = "masculine",
	BODYPARTBALLS_SIZESMALL = "small",
	BODYPARTBALLS_SIZEAVERAGE = "average",
	BODYPARTBALLS_SIZEBIG = "big",
	BODYPARTPENIS_TYPEHUMAN = "human",
	BODYPARTPENIS_TYPECANINE = "canine",
	BODYPARTPENIS_TYPEFELINE = "feline",
	BODYPARTPENIS_TYPEEQUINE = "equine",
	BODYPARTPENIS_SIZEHUMAN_SMALL = "human_small",
	BODYPARTPENIS_SIZEHUMAN_AVERAGE = "human_average",
	BODYPARTPENIS_SIZEHUMAN_BIG = "human_big",
	BODYPARTPENIS_SIZECANINE_SMALL = "canine_small",
	BODYPARTPENIS_SIZECANINE_AVERAGE = "canine_average",
	BODYPARTPENIS_SIZECANINE_BIG = "canine_big",
	BODYPARTPENIS_SIZEFELINE_SMALL = "feline_small",
	BODYPARTPENIS_SIZEFELINE_AVERAGE = "feline_average",
	BODYPARTPENIS_SIZEFELINE_BIG = "feline_big",
	BODYPARTPENIS_SIZEEQUINE_SMALL = "equine_small",
	BODYPARTPENIS_SIZEEQUINE_AVERAGE = "equine_average",
	BODYPARTPENIS_SIZEEQUINE_BIG = "equine_big",
	BODYPARTHAS_PUSSYTRUE = "has pussy",
	BODYPARTHAS_PUSSYFALSE = " ",
	BODYPARTVAGINAL_VIRGINTRUE_TRUE = "is a virgin",
	BODYPARTVAGINAL_VIRGINTRUE_FALSE = "is not a virgin",
	
	
	BODYPARTPENIS_SIZEHUMAN_SMALLDESCRIPT = 'Below [his] waist dangles a [color=yellow]tiny humanish dick[/color], small enough that it could be called cute.',
	BODYPARTPENIS_SIZEHUMAN_AVERAGEDESCRIPT ='[He] has an [color=yellow]ordinary humanish penis[/color] below [his] waist, more than enough to make most men proud.',
	BODYPARTPENIS_SIZEHUMAN_BIGDESCRIPT = 'A [color=yellow]huge humanish cock[/color] swings heavily from [his] groin, big enough to give even the most veteran whore pause.',
	BODYPARTPENIS_SIZECANINE_SMALLDESCRIPT = 'A slender, pointed [color=yellow]canine dick[/color] hangs below [his] waist, so small that its knot is barely noticeable.',
	BODYPARTPENIS_SIZECANINE_AVERAGEDESCRIPT = '[He] has a knobby, red, [color=yellow]canine cock[/color] of respectable size below [his] waist, which wouldn’t look out of place on a large dog.', 
	BODYPARTPENIS_SIZECANINE_BIGDESCRIPT = 'Growing from [his] crotch is a [color=yellow]massive canine dick[/color], red-skinned and sporting a thick knot near the base.',
	BODYPARTPENIS_SIZEFELINE_SMALLDESCRIPT = 'A [color=yellow]tiny feline penis[/color] dangles below [his] waist, so small you can barely see the barbs.',
	BODYPARTPENIS_SIZEFELINE_AVERAGEDESCRIPT = '[He] has a barbed [color=yellow]cat dick[/color] growing from [his] crotch, big enough to rival an average human.',
	BODYPARTPENIS_SIZEFELINE_BIGDESCRIPT = 'There is a frighteningly [color=yellow]large feline cock[/color] hanging between [his] thighs, its sizable barbs making it somewhat intimidating.', 
	BODYPARTPENIS_SIZEEQUINE_SMALLDESCRIPT = 'Below [his] waist hangs a [color=yellow]smallish equine cock[/color], which is still respectable compared to the average man.',
	BODYPARTPENIS_SIZEEQUINE_AVERAGEDESCRIPT = 'A [color=yellow]sizable equine cock[/color] grows from [his] nethers, which, while small on a horse, is still thicker and heavier than the average human tool.',
	BODYPARTPENIS_SIZEEQUINE_BIGDESCRIPT = 'A [color=yellow]massive equine cock[/color] hangs heavily below [his] waist, its mottled texture not quite matching the rest of [his] skin.',
	
	BODYPARTAGETEENDESCRIPT = "[He]'s a [color=aqua]teenage [boy][/color] of the [url=race][color=yellow][raceadj] race[/color][/url].",
	BODYPARTAGEADULTDESCRIPT = "[He]'s a [color=aqua]young adult [male][/color] of the [url=race][color=yellow][raceadj] race[/color][/url].",
	BODYPARTAGEMATUREDESCRIPT = "[He]'s a [color=aqua]matured [male][/color] of the [url=race][color=yellow][raceadj] race[/color][/url].",
	
	BODYPARTBODY_SHAPEHUMANOIDDESCRIPT = " ",
	BODYPARTBODY_SHAPEBESTIALDESCRIPT = " ",
	BODYPARTBODY_SHAPESHORTSTACKDESCRIPT = "[His] body is rather [color=yellow]petite[/color], about half the size of the average person.",
	BODYPARTBODY_SHAPEJELLYDESCRIPT = "[His] body is [color=yellow]jelly-like[/color] and partly transparent.",
	BODYPARTBODY_SHAPEHALFBIRDDESCRIPT = "[His] body has [color=yellow]wings for arms and avian legs[/color] making everyday tasks difficult.",
	BODYPARTBODY_SHAPEHALFSNAKEDESCRIPT = "The lower portion of [his] body consists of a long-winding [color=yellow]snake’s tail[/color].",
	BODYPARTBODY_SHAPEHALFFISHDESCRIPT = "[His] body is [color=yellow]scaly and sleek[/color], possessing fins and webbed digits.",
	BODYPARTBODY_SHAPEHALFSPIDERDESCRIPT = "The lower portion of [his] body consists of a [color=yellow]spider's legs and abdomen[/color].",
	BODYPARTBODY_SHAPEHALFHORSEDESCRIPT = "While [his] upper body is human, [his] lower body is [color=yellow]equine[/color] in nature.",
	BODYPARTBODY_SHAPEHALFSQUIDDESCRIPT =  "The lower portion of [his] body consists of a [color=yellow]number of tentacular appendages[/color], similar to those of an octopus.",
	
	BODYPARTHAIR_LENGTHEARDESCRIPT = "[His] [color=aqua][hair_color][/color] hair is cut [color=aqua]short[/color].",
	BODYPARTHAIR_LENGTHNECKDESCRIPT = "[His] [color=aqua][hair_color][/color] hair falls down to just [color=aqua]below [his] neck[/color].",
	BODYPARTHAIR_LENGTHSHOULDERDESCRIPT = "[His] wavy [color=aqua][hair_color][/color] hair is [color=aqua]shoulder length[/color].",
	BODYPARTHAIR_LENGTHWAISTDESCRIPT = "[His] gorgeous [color=aqua][hair_color][/color] hair [color=aqua]sways down to [his] waist[/color].",
	BODYPARTHAIR_LENGTHHIPSDESCRIPT = "[His] [color=aqua][hair_color][/color] hair cascades down, [color=aqua]reaching [his] hips[/color].",
	
	
	BODYPARTHAIR_STYLESTRAIGHTDESCRIPT = "It [color=aqua]hangs freely[/color] from [his] head.",
	BODYPARTHAIR_STYLEPONYTAILDESCRIPT = "It is tied in a [color=aqua]high ponytail[/color].",
	BODYPARTHAIR_STYLEPIGTAILSDESCRIPT = "It is managed in girly [color=aqua]twin-tails[/color].",
	BODYPARTHAIR_STYLEBRAIDDESCRIPT = "It is combed into a single [color=aqua]braid[/color].",
	BODYPARTHAIR_STYLETWINBRAIDSDESCRIPT = "It is combed into [color=aqua]two braids[/color].",
	BODYPARTHAIR_STYLEBUNDESCRIPT = "It is tied into a neat [color=aqua]bun[/color].",
	
	BODYPARTEYE_COLORDEFAULTDESCRIPT = "[His] eyes are [color=aqua][eye_color][/color].",
	BODYPARTEYE_SHAPENORMALDESCRIPT = ' ',
	BODYPARTEYE_SHAPESLITDESCRIPT = "[He] has [color=aqua]vertical, animalistic pupils[/color].",
	
	BODYPARTHORNSSHORTDESCRIPT = "There is a pair of [color=aqua]tiny, pointed horns[/color] on top of [his] head.",
	BODYPARTHORNSSTRAIGHTDESCRIPT = "[He] has a pair of [color=aqua]long, bull-like horns[/color].",
	BODYPARTHORNSCURVEDDESCRIPT = "There are [color=aqua]curved horns[/color] coiling around [his] head.",
	
	BODYPARTEARSHUMANDESCRIPT = " ",
	BODYPARTEARSELVENDESCRIPT = "[He] has straight long [color=aqua]pointed[/color] ears.",
	BODYPARTEARSORCISHDESCRIPT = "[He] has [color=aqua]stubby pointed[/color] ears.",
	BODYPARTEARSCATDESCRIPT = "[He] has a pair of perky [color=aqua]cat[/color] ears.",
	BODYPARTEARSWOLFDESCRIPT = "[He] has a pair of stubby [color=aqua]wolf[/color] ears.",
	BODYPARTEARSFOXDESCRIPT = "[He] has a pair of long expressive [color=aqua]fox[/color] ears.",
	BODYPARTEARSBUNNY_STANDINGDESCRIPT = "[He] has a pair of [color=aqua]standing bunny ears[/color] rising above [his] head.",
	BODYPARTEARSBUNNY_DROOPINGDESCRIPT = "[He] has a pair of [color=aqua]droopy, bunny ears[/color] on [his] head.",
	BODYPARTEARSTANUKIDESCRIPT = "[He] has a pair of rounded [color=aqua]racoon[/color] ears.",
	BODYPARTEARSDEMONDESCRIPT = "[He] has a pair of [color=aqua]demonic[/color] ears.",
	BODYPARTEARSCOWDESCRIPT = "[He] has a pair of fluffy [color=aqua]cow[/color] ears.",
	BODYPARTEARSFEATHEREDDESCRIPT = "There's a pair of clutched [color=aqua]feathery ears[/color] on the sides of [His] head.",
	BODYPARTEARSFISHDESCRIPT = "[His] ears look like a pair of [color=aqua]fins[/color].",
	
	BODYPARTSKINPALEDESCRIPT = "[His] skin is a [color=aqua]pale[/color] white.",
	BODYPARTSKINGREYDESCRIPT = "[His] skin is a stone [color=aqua]grey[/color].",
	BODYPARTSKINFAIRDESCRIPT =  "[His] skin is healthy and [color=aqua]fair[/color] color.",
	BODYPARTSKINOLIVEDESCRIPT = "[His] skin is of an unusual [color=aqua]olive[/color] tone.",
	BODYPARTSKINTANDESCRIPT = "[His] skin is a [color=aqua]tanned[/color] bronze color.",
	BODYPARTSKINBROWNDESCRIPT = "[His] skin is a mixed [color=aqua]brown[/color] color.",
	BODYPARTSKINDARKDESCRIPT = "[His] skin is deep [color=aqua]dark[/color].",
	BODYPARTSKINSLIMEDESCRIPT = "[His] skin is [color=aqua]semi-transparent and jelly-like[/color].",
	BODYPARTSKINBLUEDESCRIPT = "[His] skin is dark [color=aqua]blue[/color].",
	BODYPARTSKINPALE_BLUEDESCRIPT = "[His] skin is [color=aqua]light pale blue[/color].",
	BODYPARTSKINGREENDESCRIPT = "[His] skin is [color=aqua]green[/color].",
	BODYPARTSKINREDDESCRIPT = "[His] skin is bright [color=aqua]red[/color].",
	BODYPARTSKINPURPLEDESCRIPT = "[His] skin is [color=aqua]purple[/color].",
	BODYPARTSKINTEALDESCRIPT = "[His] skin is [color=aqua]teal[/color].",
	
	BODYPARTSKIN_COVERAGEPLANTDESCRIPT = "Various leaves and bits of [color=aqua]plant matter[/color] cover parts of [his] body.",
	BODYPARTSKIN_COVERAGESCALEDESCRIPT = "[His] skin is partly covered with [color=aqua]scales[/color].",
	BODYPARTSKIN_COVERAGEFEATHERSDESCRIPT = "[His] body is covered in [color=aqua]bird-like feathers[/color] in many places.",
	BODYPARTSKIN_COVERAGEFUR_WHITEDESCRIPT = "[His] body is covered in thick, soft [color=aqua]fur of marble color[/color].",
	BODYPARTSKIN_COVERAGEFUR_GREYDESCRIPT = "[His] body is covered in thick, soft [color=aqua]fur of gray color[/color].",
	BODYPARTSKIN_COVERAGEFUR_BROWNDESCRIPT = "[His] body is covered in thick, soft [color=aqua]fur of light-brown tone[/color].",
	BODYPARTSKIN_COVERAGEFUR_STRIPEDDESCRIPT = "[His] body is covered in thick, soft [color=aqua]striped fur[/color].",
	BODYPARTSKIN_COVERAGEFUR_BLACKDESCRIPT = "[His] body is covered in thick, soft [color=aqua]fur of jet-black color[/color].",
	BODYPARTSKIN_COVERAGEFUR_ORANGEDESCRIPT = "[His] body is covered in thick, soft [color=aqua]fur of common fox pattern[/color].",
	BODYPARTSKIN_COVERAGEFUR_ORANGE_WHITEDESCRIPT = "[His] body is covered in thick, soft [color=aqua]fur of orange-white pattern[/color].",
	
	BODYPARTWINGSFEATHERED_BLACKDESCRIPT ="On [his] back, [he] has folded, [color=aqua]black, feathery wings[/color].",
	BODYPARTWINGSSERAPHDESCRIPT = "On [his] back, [he] has folded, [color=aqua]white, feathery wings[/color].",
	BODYPARTWINGSFEATHERED_BROWNDESCRIPT = "On [his] back, [he] has folded, [color=aqua]brown, feathery wings[/color].",
	BODYPARTWINGSFAIRYDESCRIPT = "On [his] back rests translucent [color=aqua]fairy wings[/color].",
	BODYPARTWINGSDEMONDESCRIPT = "Hidden on [his] back is a pair of bat-like, [color=aqua]demon wings[/color].",
	BODYPARTWINGSDRAGONDESCRIPT = "Hidden on [his] back is a pair of thick, [color=aqua]dragon wings[/color].",
	BODYPARTWINGSLEATHER_BLACKDESCRIPT = "Hidden on [his] back is a pair of bat-like, [color=aqua]black leather wings[/color].",
	BODYPARTWINGSLEATHER_REDDESCRIPT = "Hidden on [his] back is a pair of bat-like, [color=aqua]red leather wings[/color].",
	
	BODYPARTTAILCATDESCRIPT = 'Below [his] waist, you spot a slim [color=aqua]cat tail[/color] covered with fur.',
	BODYPARTTAILFOXDESCRIPT = '[He] has a large, fluffy [color=aqua]fox tail[/color].',
	BODYPARTTAILWOLFDESCRIPT = "Below [his] waist there's a short, fluffy, [color=aqua]wolf tail[/color].",
	BODYPARTTAILBUNNYDESCRIPT = '[He] has a [color=aqua]small ball of fluff[/color] behind [his] rear.',
	BODYPARTTAILTANUKIDESCRIPT = '[He] has a plump, fluffy [color=aqua]raccoon tail[/color].',
	BODYPARTTAILCOWDESCRIPT = 'Behind [his] back you notice a long tail covered in a thin layer of fur which ends in a [color=aqua]scruffy brush[/color].',
	BODYPARTTAILDEMONDESCRIPT = '[He] has a long, thin, [color=aqua]demonic tail[/color] ending in a pointed tip.',
	BODYPARTTAILDRAGONDESCRIPT = 'Trailing somewhat behind [his] back is a [color=aqua]scaled tail[/color].',
	BODYPARTTAILAVIANDESCRIPT = '[He] has a [color=aqua]feathery bird tail[/color] on [his] rear.', 
	BODYPARTTAILFISHDESCRIPT = '[His] rear ends in long, sleek [color=aqua]fish tail[/color].', 
	BODYPARTTAILSNAKEDESCRIPT = " ",
	BODYPARTTAILTENTACLESDESCRIPT = " ",
	BODYPARTTAILHORSEDESCRIPT = " ",
	BODYPARTTAILSPIDERDESCRIPT = " ",
	
	BODYPARTHEIGHTTINYDESCRIPT = "[His] stature is [color=aqua]extremely small[/color], barely half the size of a normal person.",
	BODYPARTHEIGHTPETITEDESCRIPT = "[His] stature is quite [color=aqua]petite[/color].",
	BODYPARTHEIGHTSHORTESCRIPT ="[His] height is quite [color=aqua]short[/color].",
	BODYPARTHEIGHTAVERAGEDESCRIPT ="[He] is of [color=aqua]average[/color] height.",
	BODYPARTHEIGHTTALLDESCRIPT = "[He] is quite [color=aqua]tall[/color] compared to the average person.",
	BODYPARTHEIGHTTOWERINGDESCRIPT = "[He] is unusually tall, [color=aqua]towering[/color] over others.",
	
	BODYPARTTITS_SIZEFLATDESCRIPT = "[His] chest is barely visible and nearly [color=yellow]flat[/color].",
	BODYPARTTITS_SIZESMALLDESCRIPT = "[He] has [color=yellow]small[/color], round boobs.",
	BODYPARTTITS_SIZEAVERAGEDESCRIPT = "[His] nice, [color=yellow]perky[/color] breasts are firm and inviting.",
	BODYPARTTITS_SIZEBIGDESCRIPT = "[His] [color=yellow]big[/color] tits are pleasantly soft, but still have a nice spring to them.",
	BODYPARTTITS_SIZEHUGEDESCRIPT = "[His] [color=yellow]giant[/color] tits are mind-blowingly big.",
	BODYPARTTITS_SIZEMASCULINEDESCRIPT = "[His] chest is of definitive [color=yellow]masculine[/color] shape.",
	
	BODYPARTASS_SIZEFLATDESCRIPT = "[His] butt is skinny and [color=yellow]flat[/color].",
	BODYPARTASS_SIZESMALLDESCRIPT = "[He] has a [color=yellow]small[/color], firm butt.",
	BODYPARTASS_SIZEAVERAGEDESCRIPT = "[He] has a nice, [color=yellow]pert[/color] ass you could bounce a coin off.",
	BODYPARTASS_SIZEBIGDESCRIPT = "[He] has a pleasantly [color=yellow]plump[/color], heart-shaped ass that jiggles enticingly with each step.",
	BODYPARTASS_SIZEHUGEDESCRIPT = "[He] has a [color=yellow]huge[/color], attention-grabbing ass.",
	BODYPARTASS_SIZEMASCULINEDESCRIPT = "[His] ass definitively has a [color=yellow]masculine[/color] shape.",
	
	BODYPARTBALLS_SIZESMALLDESCRIPT = "[He] has a pair of [color=yellow]tiny[/color] balls.",
	BODYPARTBALLS_SIZEAVERAGEDESCRIPT = "[He] has an [color=yellow]average-sized[/color] ballsack.",
	BODYPARTBALLS_SIZEBIGDESCRIPT = "[He] has a [color=yellow]huge[/color] pair of balls weighing down [his] scrotum.",
	
	BODYPARTVAGINAL_VIRGINTRUE_TRUEDESCRIPT = '[He] has a tight, [color=yellow]virgin pussy[/color].',
	BODYPARTVAGINAL_VIRGINTRUE_FALSEDESCRIPT = "[He] has a [color=yellow]normal pussy[/color] below [his] waist.",
	BODYPARTHAS_PUSSYFALSEDESCRIPT = " ",
	
	SEXTRAITSKILLED_PETTING = "Nimble Fingers",
	SEXTRAITSKILLED_MOUTH = "Masterful Tongue",
	SEXTRAITSKILLED_TAIL = "Resourceful Tail",
	SEXTRAITORAL = "Oral Lover",
	SEXTRAITANAL = "Anal Lover",
	SEXTRAITMASOCHIST = "Masochist",
	SEXTRAITSADIST = "Sadist",
	SEXTRAITSUBMISSIVE = "Submissive",
	SEXTRAITGROUP = "Company Lover",
	SEXTRAITLIKES_SHORTSTACKS = "Shortstack Enthusiast",
	SEXTRAITLIKES_BEASTS = "Likes them beasty",
	SEXTRAITLEWDNESS_AURA = "Perversy Aura",
	SEXTRAITBISEXUAL = "Bisexual",
	SEXTRAITOMNISEXUAL = "Omnisexual",
	
	SEXTRAITSSKILLED_PETTINGDESCRIPT = "[name]'s hands are more skillful at providing pleasure. Partner's lust and arousal on petting actions: +33%. ", 
	SEXTRAITSKILLED_MOUTHDESCRIPT = "[name]'s mouth are more skillful at providing pleasure. Partner's lust and arousal on oral actions: +33%. ",  
	SEXTRAITSKILLED_TAILDESCRIPT = "[name] has mastered the usse of [his] tail and now it can serve as an additional limb. Partner's lust and arousal on tail-related actions: +40%. ", 
	SEXTRAITORALDESCRIPT = "[name]'s mouth is unusually sensetive. Lust and Arousal from oral actions: +50%.", 
	SEXTRAITANALDESCRIPT = "[name] seems to find a special joy form using [his] rear. Lust and Arousal from anal actions: +50%.", 
	SEXTRAITMASOCHISTDESCRIPT = "[name] seems to find pleasure in pain. Lust and Arousal from punishing actions: +50%.",  
	SEXTRAITSADISTDESCRIPT = "[name] seems to find pleasure in causing pain to others. Lust and Arousal from giving punishments: +50%.",  
	SEXTRAITSUBMISSIVEDESCRIPT = "[name] has a thing for being forcefully used by others. Lust and Arousal while being Tied or Subdued: +25%.",  
	SEXTRAITGROUPDESCRIPT = "[name] likes handling multiple partners at once. Group actions give 33% more lust and arousal. ",  
	SEXTRAITLIKES_SHORTSTACKSDESCRIPT = "[name] has a preferences for shorter partners. Actions with Petite or smaller characters give 50% more Arousal and Lust.", 
	SEXTRAITLIKES_BEASTSDESCRIPT = "[name] has a preferences for beasty partners. Actions with beastkin or halfkin races give 50% more Arousal and Lust.",  
	SEXTRAITLEWDNESS_AURADESCRIPT = "[name] has an unusual aura around [him], making everyone participating slightly more aroused every turn. ", 
	SEXTRAITBISEXUALDESCRIPT = "[name] has fully accepted drowning in sexual pleasure with any gender. Removes penalty from same-sex actions.", 
	SEXTRAITOMNISEXUALDESCRIPT = "[name] is ready to go to the lengths normal people wouldn't usually go. Removes penalty from actions with animals and undeads. ", 
	
}

