extends Node

var TranslationDict = {
	#Buildings
	WORKERMARKET = "Market",
	PURCHASE = "Purchase",
	SELL = "Sell",
	TASKS = "Tasks",
	UPGRADES = "Upgrades",
	TOWNHALL = "Town Hall",
	FOODCONV = "Food Conversion",
	HARVESTMETAL = "Harvest Ore",
	HARVESTPLANT = "Harvest Plants",
	GOBLINWORKER = "Goblin Worker",
	ELFWORKER = "Elven Worker",
	
	
	#Materials
	STARTINGADJ = "Starting",
	
	
	
	MATERIALWOOD = "Wood",
	MATERIALSTONE = "Stone",
	MATERIALMEAT = "Meat",
	MATERIALFISH = "Fish",
	MATERIALGRAINS = "Grains",
	MATERIALVEGETABLES = "Vegetables",
	MATERIALLEATHER = "Leather",
	MATERIALIRON = "Iron",
	MATERIALBONE = "Bone",
	MATERIALCLOTH = "Cloth",
	
	
	MATERIALWOODDESCRIPT = "Sturdy wood for general building and furnishing purposes.",
	WOODADJ = "wooden",
	MATERIALSTONEDESCRIPT = "Stone comes in many forms and shapes, but might serve as good building material or even poor instrumentum.",
	STONEADJ = 'stone',
	MATERIALELVENWOODDESCRIPT = "An unusual wood with additional magic properties. ",
	ELVENWOODADJ = "Elven",
	METARIALGOBLINGMETALDESCRIPT = "Rusty looking metal, but still decent for some work. Can be used for heavy armor. ",
	GOBLINMETALADJ = "Goblin",
	METARIALELVENMETALDESCRIPT = "Soft, but strong alloy storing some magical properties. ",
	ELVENMETALADJ = "Elven",
	MATERIALLEATHERDESCRIPT = "A common animal leather. Can be used for light armor.",
	LEATHERADJ = "Leather",
	MATERIALBONEDESCRIPT = "A common animal bone. With right approach can provide some interesting properties. ",
	BONEADJ = "Bone",
	MATERIALCLOTHDESCRIPT = "A simple cotton fibre for simple clothes. Can be used for cloth armor. ",
	CLOTHADJ = "Cotton",
	
	
	ITEMBED = "Bed",
	ITEMBEDDESCRIPT = "",
	ITEMLEATHER_COLLAR = "Leather Collar",
	ITEMLEATHER_COLLARDESCRIPT = "",
	ITEMELEGANT_CHOCKER = "Elegant Choker",
	ITEMELEGANT_CHOCKERDESCRIPT = "",
	ITEMSTEEL_COLLAR = "Steel Collar",
	ITEMSTEEL_COLLARDESCRIPT = "",
	ITEMANIMAL_EARS = "Animal Ears",
	ITEMANIMAL_EARSDESCRIPT = "",
	ITEMTAIL_PLUG = "Tail Plug",
	ITEMTAIL_PLUGDESCRIPT = "",
	ITEMANIMAL_GLOVES = "Animal Gloves",
	ITEMPET_SUIT = "Pet Suit",
	ITEMPET_SUITDESCRIPT = "",
	ITEMSHACKLES = "Shackles",
	ITEMSHACKLESDESCRIPT = "",
	ITEMCHASTITY_BELT = "Chastity Belt",
	ITEMCHASTITY_BELTDESCRIPT = "",
	ITEMSTIMULATIVE_UNDERWEAR = 'Stimulative Underwear',
	ITEMSTIMULATIVE_UNDERWEARDESCRIPT = "",
	ITEMTENTACLE_SUIT = 'Tentacle Suit',
	ITEMTENTACLE_SUITDESCRIPT = "",
	
	ITEMAPHRODISIAC = "Aphrodisiac",
	ITEMAPHRODISIACDESCRIPT = "",
	ITEMALCOHOL = "Alcohol",
	ITEMALCOHOLDESCRIPT = "",
	ITEMTAMEDRUG = "Tame Drug",
	ITEMTAMEDRUGDESCRIPT = "",
	ITEMRAGEDRUG = "Rage Drug",
	ITEMRAGEDRUGDESCRIPT = "",
	ITEMSEXDRUG = "Sex Drug",
	ITEMSEXDRUGDESCRIP = "",
	
	
	
	
	#Items
	WEAPONAXENAME = "Axe",
	WEAPONPICKAXENAME = "Pickaxe",
	WEAPONSWORDNAME = 'Sword',
	WEAPONBOWNAME = "Bow",
	WEAPONSTAFFNAME = "Staff",
	
	
	WEAPONAXEDESCRIPT = 'Axe can be used for cutting wood and combat.',
	WEAPONSWORDDESCRIPT = "Good damage vs unarmored enemies.",
	WEAPONPICKAXEDESCRIPT = "Allows workers to harvest ore, but also can be use in combat.",
	WEAPONBOWDESCRIPT = "Simple weapon for ranged fighters.",
	WEAPONSTAFFDESCRIPT = "A simple tool for magic users.",
	
	ARMORBASICCHEST = "Chestplate",
	ARMORROBE = "Robe",
	ARMORHOOD = "Hood",
	ARMORSHOES = "Shoes",
	ARMORBASICCHESTDESCRIPT = "Offers basic body protection.",
	ARMORBASICHELM = "Helmet",
	ARMORBASICHELMDESCRIPT = "Offers basic head protection.",
	ARMORBASICBOOTS = "Boots",
	ARMORBASICBOOTSDESCRIPT = "Offers basic foot protection",
	ARMORBASICGLOVES = "Gloves",
	ARMORBASICGLOVESDESCRIPT = "Offers basic hand protection",
	
	USABLEMORSEL = "Morsel",
	USABLEMORSELDESCRIPT = "A questionable piece of meat. Restores 50 health. Can be converted into Food.",
	USABLEMANAGRASS = "Blue Grass",
	USABLEMANAGRASSDESCRIPT = "An unusual plant with magical properties. Restores 25 mana on use. ",
	USABLEBARRICADE = "Barricade",
	USABLEBARRICADEDESCRIPT = "A makeshift wooden obstacle. Shields target from 50 physical damage for 2 turns",
	USABLEPROTECTIVECHARM = "Protective Charm",
	USABLEPROTECTIVECHARMDESCRIPT = "An enchanted piece of paper. Shields target from 50 magic damage for 2 turns",
	USABLEELIXIR = "Elixir",
	USABLEELIXIRDESCRIPT = "A rejuvinating potion. Restores 75 health and 40 mana.",
	
	
	#enemies
	MONSTERELVENRAT = "Elven Rat",
	MONSTERELVENRATFLAVOR = "These animals are fairly common in most areas. Distinct ears make them accumulate all sorts of moniker, but goblins seem to label them this way...",
	MONSTERTREANT = "Ent",
	MONSTERTREANTFLAVOR = "Despite its looks, this thing is actually a plant. Often disguises itself as a simple trunk for a nasty surprise.",
	MONSTERBIGTREANT = "Big Ent",
	MONSTERBIGTREANTFLAVOR = "Big ents are somewhat mobile and quite dangerous when provoked.",
	MONSTEREARTHGOLEM = "Earth Golem",
	MONSTEREARTHGOLEMFLAVOR = "A magic creature of considerable power. They seem to roam around some caves and dungeons with little thought. I would expect more from a hand-made slave. ",
	MONSTERSPIDER = "Spider",
	MONSTERSPIDERFLAVOR = "Of course just ents weren't enough...",
	MONSTERFAIRIES = "Fairies",
	MONSTERFAIRIESFLAVOR = "If not for their nasty nature, I would even consider them appealing.",
	MONSTERANGRYDWARF = "Angry Dwarf",
	MONSTERANGRYDWARFFLAVOR = "Dumb but strong for their size. Despite my best attempts, they didn't seem to be up for any sort of negotiation. ",
	MONSTEREARTHGOLEMBOSS = "Greater Golem",
	MONSTEREARTHGOLEMBOSSFLAVOR = "Twice as big as normal golem. And twice as angry...",
	#gearclasses
	GEARSWORD = "Swords",
	GEARAXE = "Axes",
	GEARSTAFF = "Staves",
	GEARBOW = "Bows",
	GEARPICKAXE = "Pickaxes",
	
	#Stats
	DAMAGE = 'Damage',
	DAMAGEMOD = "Damage Mult.",
	ARMOR = 'Armor',
	MDEF = "Magic Armor",
	EVASION = 'Evasion',
	HITRATE = 'Hit Chance',
	HEALTH = 'Health',
	DURABILITY = "Durability",
	DURABILITYMOD = "Dur. Factor",
	ARMORPENETRATION = "Armor Pen.",
	RESISTFIRE = "Fire Res.",
	RESISTEARTH = "Earth Res.",
	RESISTAIR = "Air Res.",
	RESISTWATER = "Water Res.",
	HEALTHPERCENT = "Max. Health",
	MANAPERCENT = "Max. Mana",
	CRITICAL = "Critical",
	CRITCHANCE = "Crit. Chance",
	CRITMOD = "Crit. Mod",
	LEVELUP = "Level up",
	MAXLEVEL =  "Maximum Level",
	LEVEUPTEXT = " has just acquired a level. Select a new trait to unlock",
	
	#stat tooltips
	TOOLTIPDAMAGE = "Defines damage output of skills and spells",
	TOOLTIPARMOR = "Reduces skill damage taken by this percent",
	TOOLTIPMDEF = "Reduces spell damage taken by this percent",
	TOOLTIPCRIT = "Percent chance to crit for extra damage\nFirst value is a chance. Second value is a modifier.",
	TOOLTIPHITRATE = "Percent chance to hit target\nReduced by enemy's evasion",
	TOOLTIPARMORPEN = "Reduces enemy armor by this value",
	TOOLTIPEVASION = "Reduces enemy hit chance by this value",
	TOOLTIPSPEED = "Improves your odds to act before other characters",
	TOOLTIPRESISTS = "Reduces elemental damage by relative resist",
	
	
	
	#Item Parts
	TOOLHANDLE = 'Handle',
	BLADE = 'Blade',
	BLUNT = 'Head',
	ROD = 'Knub',
	BOWBASE = 'Bow Limb',
	ARMORBASE = 'Base',
	ARMORPLATE = 'Plate',
	ARMORTRIM = 'Trim',
	JEWELRYGEM = 'Gem',
	
	
	#Material Effects
	GOBMETALHANDLEDESCRIPT = "Deals 15% more damage when enemy's health below 30%",
	ELFMETALHANDLEDESCRIPT = "Gain +1 Mana on skill hit",
	GOBMETALBLADEDESCRIPT = "Deals small bonus earth damage",
	ELFMETALBLADEDESCRIPT = "Deals +10 damage on first hit",
	ELFWOODRODDESCRIPT = "Restores 10% mana on the end of combat",
	GOBMETALRODDESCRIPT = "For 1 turn reduces target's speed by 10 on spell hit",
	BONERODDESCRIPT = "Restores 3% health on spell hit",
	BONEBOWDESCRIPT = "+1 health on hit",
	
	
	#Menu
	NEWGAME = "New Game",
	LOAD = 'Load',
	OPTIONS = 'Options',
	QUIT = 'Quit',
	CLOSE = "Close",
	PROCEED = "Proceed",
	SELECTHERO = "Select Hero",
	SOUND = "Sound",
	MUSIC = "Music",
	MASTERSOUND = "Master Volume",
	MUTE = "Mute",
	AUDIO = "Audio",
	
	TEXTSPEED = "Text Speed",
	SKIPREAD = "Skip Read",
	
	CURRENTFOOD = "Current Food",
	GAINFOOD = "Food Value",
	FOODCONVERT = "Convert Food",
	
	#System
	CONFIRM = "Confirm",
	FRONT = "Front",
	BACK = "Back",
	CANCEL = "Cancel",
	REMOVE = "Remove",
	NONE = "None",
	SPEED = "Speed",
	DAY = "Day",
	ENERGY = "Energy",
	TIME = "Time",
	CRAFT = "Craft",
	BLACKSMITH = "Blacksmith",
	PROGRESS = "Progress",
	REPAIR = "Repair",
	REPAIRALL = "Repair All",
	WORKERNOENERGY = " has no energy left and stopped working.",
	TOOLBROKEN = " has broken.",
	CURRENTTASK = "Current Task",
	REQUIREDMATERIAL = "Required Material",
	REQUIREDMATERIALS = "Required Materials",
	SELECTREPAIR = "Select Item(s) to Repair",
	TOTALPRICE = "Total Price",
	SELECTMATERIAL = "Select materials for all parts.",
	INPOSESSION = "In Possession",
	BASECHANCE = "Base Chance",
	CANTREPAIREFFECT = "This item can't be repaired.",
	NOTENOUGH = "Not enough",
	ITEMCREATED = "Item Created",
	UPGRADEUNLOCKED = "Upgrade Unlocked",
	MAINQUEST = "Main Quest",
	SIDEQUESTS = "Sidequests",
	MAINQUESTUPDATED = "Main Quest Updated",
	QUESTLOG = "Quest Log",
	NOACTIVEQUESTS = "You have no active quests.",
	INVALIDCLASS = "Invalid class for this gear.",
	NOTENOUGHGOLD = "Not enough gold",
	PURCHASETHISTRAIT = "Purchase this trait",
	TRAITPOINTSCOST = "Trait Points",
	TRAITPOINTS = "Trait Points used",
	GOLDPRICE = "Gold Cost",
	
	SYSNOFOOD = "Work canceled: No food",
	SYSNOWORKERENERGY = "Work canceled: No energy",
	
	
	SELECT = "Select",
	SELECTTOOL = "Select Tool",
	SELECTWORKER = "Select Worker",
	SELECTITEM = "Select Item",
	WORKERLIMITREACHER = "Worker Limit Reached: Upgrade Houses to increase",
	TOTALWORKERS = "Total Workers",
	
	TUTORIAL = "Tutorial",
	TRAITS = "Traits",
	CLASSINFO = "Class Details",
	
	INVENTORY = "Inventory",
	WORKERLIST = "Worker List",
	HEROLIST = "Hero List",
	OPTIONMENU = "Options",
	
	INVENTORYALL = "All items",
	INVENTORYWEAPON = "Weapons",
	INVENTORYARMOR = "Armor",
	INVENTORYMATERIAL = "Materials",
	INVENTORYUSE = "Usables",
	INVENTORYQUEST = "Misc",
	SELLCONFIRM = "Sell",
	RAWPRICE = "Raw Price",
	FOODDESCRIPT = "Food is used to feed workers. ",
	MONEYDESCRIPT = "Money is used to purchase goods and workers.",
	
	AREAISENDLESS = "This area has no progression",
	TOWNRETURN = "Return",
	
	#Confirms
	
	LEAVECONFIRM = "Leave to Main Menu? Unsaved progress will be lost. ",
	LOADCONFIRM = "Load this save file?",
	OVERWRITECONFIRM = "Overwrite this save file?",
	DELETECONFIRM = "Delete this save file?",
	STOPTASKCONFIRM = "Stop this job?",
	SLAVEREMOVECONFIRM = "Expel this worker?",
	
	
	#Inbuilt Tooltips
	PAUSEBUTTONTOOLTIP = 'Pause\nHotkey: 1',
	NORMALBUTTONTOOLTIP = 'Normal Speed\nHotkey: 2',
	FASTBUTTONTOOLTIP = 'Fast Speed\nHotkey: 3',
	
	
	#Tasks
	HARVESTWOOD = "Harvest Lumber",
	WOODCUTTINGTASKDESCRIPTION = "Harvest lumber from nearest vegetation.",
	HARVESTMETALDESCRIPTION = "Harvest metal ores from the mine. \n[color=red]Requires a pickaxe.[/color]",
	HARVESTPLANTDESCRIPTION = "Produce plants from the farm.",
	
	
	#Classes
	CLASSDESCRIPT = "Class defines character's basic characteristics, abilities, specific traits and allowed gear. More abilities are unlocked as you level up. After certain level you can advance into one of the new classes.",
	WARRIOR = "Warrior",
	MAGE = "Mage",
	ARCHER = "Archer",
	BRAWLER = "Brawler",
	WARRIORDESCRIPT = "Warrior is a strong melee class focusing on tanking and dealing damage. They can handle many weapons but lack in magic and range. ",
	MAGEDESCRIPT = "Mage is a supporting class capable of both healing and slinging powerful area spells. ",
	ARCHERDESCRIPT = "Archer is a ranged damaging class. Having access to some spells, they can hit any target on the battlefield. ",
	BRAWLERDESCRIPT = "Brawler is a melee supporting class. They specialize in using special attacks for crowd control. ",
	MAGETRAITDESCRIPT = "Gain 1 bonus Damage for every 2 bonus Magic Armor.",
	ARCHERTRAITDESCRIPT = "Gain 1 bonus Hit Rate for every 1 bonus Evasion.",
	CLASSALLOWEDWEAPONS = "Allowed gear",
	CLASSTRAIT = "Class bonus",
	
	#Names
	ARRON = 'Arron',
	ROSE = 'Rose',
	EMBER = 'Ember',
	ERIKA = 'Erika',
	GOBLIN = 'Goblin',
	GUARD1 = 'Guard1',
	GUARD2 = 'Guard2',
	GUARD3 = 'Guard3',
	NORBERT = 'Norbert',
	DEMITRIUS = "Demitrius",
	LYRA = "Lyra",
	FLAK = "Flak",
	
	#Skills
	SKILLATTACK = "Attack",
	SKILLATTACKDESCRIPT = "Attacks target with equipped weapon for %d damage. ",
	SKILLFIREBOLT = "Firebolt",
	SKILLFIREBOLTDESCRIPT = "Launches a fire spell on target. Deal %d Fire damage to all targets in same row.",
	SKILLWINDARROW = "Wind Arrow",
	SKILLWINDARROWDESCRIPT = "Imbues the arrow with Wind element and deal %d damage. Requires a bow equipped.",
	SKILLTAUNT = "Taunt",
	SKILLTAUNTDESCRIPT = "Forces enemy to attack you on its next turn and reduces its damage by 25% for 2 turns.",
	SKILLSLASH = "Slash",
	SKILLSLASHDESCRIPT = "Deals %d Weapon damage to all targets in nearby column. Requires a weapon equipped.",
	SKILLMINORHEAL = "Minor Heal",
	SKILLMINORHEALDESCRIPT = "Restore %d health of the target.",
	SKILLCONCENTRATE = "Concentrate",
	SKILLCONCENTRATEDESCRIPT = "Restore %d mana for self.",
	SKILLFIRESTORM = "Fire Storm",
	SKILLFIRESTORMDESCRIPT = "Deals %d fire damage to all enemies.",
	SKILLSTRONGSHOT = "Strong Shot",
	SKILLSTRONGSHOTDESCRIPT = "Deals %d Weapon damage to target enemy and stuns for 1 turn. Requires a bow equipped.",
	SKILLARROWSHOWER = "Arrow Shower",
	SKILLARROWSHOWERDESCRIPT = "Deals %d Weapon damage to all enemies.",
	SKILLTACKLE = "Tackle",
	SKILLTACKLEDESCRIPT = "Deals %d Physical damage and stuns target for 1 turn.",
	SKILLCRIPPLE = "Cripple",
	SKILLCRIPPLEDESCRIPT = "Deals %d Weapon damage and reduces target's damage by 33%% for 3 turns.",
	SKILLCOMBOATTACK = "Combo Attack",
	SKILLCOMBOATTACKDESCRIPT = "Deals 3 consecutive hits for %d Weapon damage to target. ",
	SKILLDOUBLEATTACK = "Double Attack",
	SKILLDOUBLEATTACKDESCRIPT= "Attacks for %d damage twice.",
	
	
	#Upgrades
	UPGRADEPREVBONUS = "Current bonus",
	UPGRADENEXTBONUS = "Unlock bonus",
	BRIDGEUPGRADE = "Bridge",
	UPGRADEBRIDGEDESCRIPT = "Reinforce the bridge leading to the outer lands. Currently it barely allows locals move in and out, but you are afraid it might prove to dangerous for you to cross as is.",
	UPGRADEBRIDGEBONUS = "Unlocks exploration",
	MINEUPGRADE = "Mine",
	UPGRADEMINEDESCRIPT = "The old mine should still be rich in resources, but will require some work on it. ",
	UPGRADEMINEBONUS = "Allows production of ores.",
	FARMUPGRADE = "Farm",
	UPGRADEFARMDESCRIPT = "The farm allows cultivation of various plant fibers, useful for crafting. ",
	UPGRADEFARMBONUS = "Allows production of cloth",
	HOUSESUPGRADE = "Worker Barracks",
	UPGRADEHOUSESDESCRIPT = "Living quarters for your workers. ",
	UPGRADHOUSEBONUS1 = "Hosts up to 4 workers",
	UPGRADHOUSEBONUS2 = "Hosts up to 8 workers",
	BLACKSMITHUPGRADE = "Blacksmith",
	UPGRADEBLACKSMITHDESCRIPT = "Upgrade of Ember's forge will allow the production of new gear.",
	UPGRADEBLACKSMITHBONUS1 = "Unlocks Headgear",
	UPGRADEBLACKSMITHBONUS2 = "Unlocks footgear",
	LUMBERMILLUPGRADE = "Lumber mill",
	UPGRADELUMBERMILLDESCRIPT = "Provides a room for more Lumber Harvesters.",
	UPGRADELUMBERMILLBONUS = "Increases the number of workers allowed in same time to 4. ",
	
	#traitdescriptions
	TRAITBEASTBONUSDAMAGE = "Deals 20% more damage to animals",
	TRAITBEASTBONUSRESIST = "Takes 20% less damage from animals",
	TRAITBEASTBONUSEXP = "Receive 15% more Experience after combat",
	TRAITBONUSHIT = "+10 Hit Rate",
	TRAITBONUSEVASION = "+10 Evasion",
	TRAITBONUSEVASIONPLUS = "+15 Evasion",
	TRAITBONUSCRIT = "+10% Critical Strike Chance",
	TRAITBONUSRESIST = "+10 To all elemental resists",
	TRAITBONUSARMOR = "+5 Armor",
	TRAITBONUSSPEED = "+10 Speed",
	TRAITBONUSHPMAX = "+25 Maximum Health",
	TRAITBONUSREGEN = "Regenerates 5% Health in the end of each turn",
	TRAITDODGEDEBUFF = "On hit: Reduces Enemy's evasion by 10 for 2 turns",
	TRAITGROUPARMOR = "+10 Armor to all characters in same row",
	TRAITDOUBLEHEAL = "When heals an ally, Caster also heals for 50% of effect",
	TRAITSPEEDONDAMAGE = "+20 Speed for 2 turns after taking damage",
	TRAITSPELLCRITBONUS = "Restores Spell's mana cost on Spell critical",
	TRAITSPEEDDEBUFF = "Reduces Speed and Evasion by 10 when hitting an enemy (stacks up to 2 times)",
	TRAITBOWEXTRADAMAGE = "After dealing a finishing blow, your next attack deals 100% more damage",
	TRAITCRITARMORIGNORE = "Critical strikes ignore target's Armor",
	TRAITDODGEGROUP = "+10 Speed to all characters on the same column",
	TRAITRESISTDEBUFF = "On hit reduces all target resists for 15 for 1 turn",
	TRAITFIREDAMAGEBONUS = "20% Extra Fire damage to skills",
	
	TAKEGOLDBUTTON = "Take 100 Gold",
	TAKEGOLDBUTTONTOOLTIP = "Refuse all traits and receive 100 gold",
	
	
	
	TOOLTIPBASEEXP = "Character's unspent experience. Can be used to unlock classes.",
	TOOLTIPOBEDIENCE = "Obedience represents the character's willingness to work for you. If both obedience and fear drop too low, the character might stop following orders or even escape. Obedience is gained by praises and rewards. ",
	TOOLTIPFEAR = "Fear represents the character's awe towards you and your orders. If both obedience and fear drop too low, the character might stop following orders or even escape. Fear is gained from punishments and abusive behavior. ",
	TOOLTIPLUST = "Lust increases with time and allows the use of specific skills. Lust can be a powerful control and resource tool when approached correctly.",
	TOOLTIPENERGY = "Energy is restored during sleep and is required for task productions. When character is forced to work with no energy left, they accomodate Exhaustion. ",
	TOOLTIPFATIGUE = "Fatigue increases with time and dissipates with entertaining activities. When unmanaged may cause performance penalty.",
	TOOLTIPEXHAUSTION = "Exhaustion grows when character is forced to work with no energy left. Exhaustion causes penalty to maximum health and production, and can lead to fatal cause if not taken care of for a long time.",
	TOOLTIPLOYAL = "Loyalty represents character's willingness to follow master's orders even they neither obedient, nor fearful. It grows with time and stops servants from escaping. ",
	
	TOOLTIPPHYSICS = "Physicals represent character's muscles and reflexes. The higher it is, the more effective combat and manual labor tasks are. Grows with physical labor. ",
	TOOLTIPWITS = "Wits represent character's mind quickness and intelligence. High Wits are mandatory for stronger Mage classes and crafters. ",
	TOOLTIPCHARM = "Charm represents character's appeal and appearance. High Charm makes social oriented works and skills a lot more effective. ",
	TOOLTIPSEXUAL = "Sexuals represent character's skills in body pleasures. High Sexuals make sexual skill and tasks a lot more effective. Sexuals also increase Lust cap. ",
	
	TOOLTIPGROWTHFACTOR = "Growth factor represents how easy it is for the character to acquire a new class. The higher it is, the more classes you can take until soft cap limit.",
	TOOLTIPPHYSICSFACTOR = "Body factor represents physical potential of the character. It limits Physical growth and influences melee combat.",
	TOOLTIPMAGICFACTOR = "Magic factor represents character's magic affinity. The higher it is, the more mana you have and the stronger magic classes you can unlock. Also influences spell effects and damage. ",
	TOOLTIPTAMEFACTOR = "Tame factor represents how easy is to befriend the character. The higher it is, the slower Obedience decays. ", 
	TOOLTIPBRAVEFACTOR = "Brave factor represents how hard is to keep character in Fear. The higher it is, the quicker Fear decays. ",
	TOOLTIPWITSFACTOR = "Wits factor represents character's mind potential. It limits Wits growth.",
	TOOLTIPCHARMFACTOR = "Charm factor represents character's appeal potential. It limits Charm growth.",
	TOOLTIPSEXUALSFACTOR = "Sex factor represents character's sex development potential. It limits Sexuals growth.",
	
	
	
	JOBHUNTING = "Hunting",
	JOBHUNTINGDESCRIPT = "",
	JOBWOODCUTTING = "Wood Cutting",
	JOBWOODCUTTINGDESCRIPT = "",
	JOBFISHING = "Fishing",
	JOBFISHINGDESCRIPT = "",
	JOBMINING = "Mining",
	JOBMININGDESCRIPT = "",
	JOBPROSTITUTION = "Prostitution",
	JOBPROSTITUTIONDESCRIPT = "",
	JOBMARKET = "Market",
	JOBMARKETDESCRIPT = "",
	JOBFORGE = "Forge",
	JOBFORGEDESCRIPT = "",
	JOBALCHEMY = "Alchemy",
	JOBALCHEMYDESCRIPT = "",
	
	
	
	RACEHUMAN = "Human",
	RACEHUMANDESCRIPT = "",
	RACEHUMANADJ = "Human",
	RACEELF = "Elf",
	RACEELFDESCRIPT = "",
	RACEELFADJ = "Elven",
	RACEDARKELF = "Dark Elf",
	RACEDARKELFDESCRIPT = "",
	RACEDARKELFADJ = "Dark Elven",
	RACEDROW = "Drow",
	RACEDROWDESCRIPT = "",
	RACEDROWADJ = "Drow",
	RACEORC = "Orc",
	RACEORCDESCRIPT = "",
	RACEORCADJ = "Orc",
	RACEGOBLIN = "Goblin",
	RACEGOBLINDESCRIPT = "",
	RACEGOBLINADJ = "Goblin",
	RACEDWARF = "Dwarf",
	RACEDWARFDESCRIPT = "",
	RACEDWARFADJ = "Dwarven",
	RACEGNOME = "Gnome",
	RACEGNOMEDESCRIPT = "",
	RACEGNOMEADJ = "Gnome",
	RACEFAIRY = "Fairy",
	RACEFAIRYDESCRIPT = "",
	RACEFAIRYADJ = "Fairy",
	RACEDRYAD = "Dryad",
	RACEDRYADDESCRIPT = "",
	RACEDRYADADJ = "Dryad",
	RACEDEMON = "Demon",
	RACEDEMONDESCRIPT = "",
	RACEDEMONADJ = "Demon",
	RACESERAPH = "Seraph",
	RACESERAPHDESCRIPT = "",
	RACESERAPHADJ = "Seraph",
	RACEDRAGONKIN = "Dragonkin",
	RACEDRAGONKINDESCRIPT = "",
	RACEDRAGONKINADJ = "Dragonkin",
	RACECENTAUR = "Centaur",
	RACECENTAURDESCRIPT = "",
	RACECENTAURADJ = "Centaur",
	RACETAURUS = "Taurus",
	RACETAURUSDESCRIPT = "",
	RACETAURUSADJ = "Taurus",
	RACEHARPY = "Harpy",
	RACEHARPYDESCRIPT = "",
	RACEHARPYADJ = "Harpy",
	RACESLIME = "Slime",
	RACESLIMEDESCRIPT = "",
	RACESLIMEADJ = "Slime",
	RACELAMIA = "Lamia",
	RACELAMIADESCRIPT = "",
	RACELAMIAADJ = "Lamia",
	RACEARACHNA = "Arachna",
	RACEARACHNADESCRIPT = "",
	RACEARACHNAADJ = "Arachna",
	RACESCYLLA = "Scylla",
	RACESCYLLADESCRIPT = "",
	RACESCYLLAADJ = "Scylla",
	RACENEREID = "Nereid",
	RACENEREIDDESCRIPT = "",
	RACENEREIDADJ = "Nereid",
	
	RACEBEASTKINCAT = "Beast Cat",
	RACEBEASTKINCATDESCRIPT = "",
	RACEBEASTKINCATADJ = "Beast Cat",
	RACEBEASTKINWOLF = "Beast Wolf",
	RACEBEASTKINWOLFDESCRIPT = "",
	RACEBEASTKINWOLFADJ = "Beast Wolf",
	RACEBEASTKINFOX = "Beast Fox",
	RACEBEASTKINFOXDESCRIPT = "",
	RACEBEASTKINFOXADJ = "Beast Fox",
	RACEBEASTKINBUNNY = "Beast Bunny",
	RACEBEASTKINBUNNYDESCRIPT = "",
	RACEBEASTKINBUNNYADJ = "Beast Bunny",
	RACEBEASTKINTANUKI = "Beast Tanuki",
	RACEBEASTKINTANUKIDESCRIPT = "",
	RACEBEASTKINTANUKIADJ = "Beast Tanuki",
	
	RACEHALFKINCAT = "Half-Breed Cat",
	RACEHALFKINCATDESCRIPT = "",
	RACEHALFKINCATADJ = "Half-Breed Cat",
	RACEHALFKINWOLF = "Half-Breed Wolf",
	RACEHALFKINWOLFDESCRIPT = "",
	RACEHALFKINWOLFADJ = "Half-Breed Wolf",
	RACEHALFKINFOX = "Half-Breed Fox",
	RACEHALFKINFOXDESCRIPT = "",
	RACEHALFKINFOXADJ = "Half-Breed Fox",
	RACEHALFKINBUNNY = "Half-Breed Bunny",
	RACEHALFKINBUNNYDESCRIPT = "",
	RACEHALFKINBUNNYADJ = "Half-Breed Bunny",
	RACEHALFKINTANUKI = "Half-Breed Tanuki",
	RACEHALFKINTANUKIDESCRIPT = "",
	RACEHALFKINTANUKIADJ = "Half-Breed Tanuki",
	
	SKILLPRAISE = "Praise",
	SKILLPRAISEDESCRIPT = "A basic tool for obedience improval. Increases obedience slightly.",
	SKILLWARN = "Warn",
	SKILLWARNDESCRIPT = "A basic tool for fear instigation. Increases fear slightly.",
	SKILLPUNISH = "Punish",
	SKILLPUNISHDESCRIPT = "Hit them very hard. Increases fear.",
	SKILLREWARD = "Reward",
	SKILLREWARDESCRIPT = "Buying their respect might seem line an easy solution... as long as you have enough coin. Increases obedience greatly.",
	SKILLREWARDSEX = "Reward with sex",
	SKILLREWARDSEXDESCRIPT = "Give them some attention as your goodwill... As long as they seek for it. Increases obedience greatly. Can only be used on lustful targets.",
	SKILLSEDUCE = "Seduce",
	SKILLSEDUCEDESCRIPT = "By pushing right buttons you can not only make them horny, but also follow your orders. Maximizes lust and increases obedience. Can be resisted",
	SKILLGREATSEDUCE = "Great Seduce",
	SKILLGREATSEDUCEDESCRIPT = "A dangerous art which can make victim instantaneously fall in love. Maximizes lust, obedience and boost loyalty. Can be resisted.",
	SKILLDRAIN = "Drain",
	SKILLDRAINDESCRIPT = "Restores some fatigue, mana and energy by draining it from target.",
	SKILLSERVE = "Serve",
	SKILLSERVEDESCRIPT = "Help them out and make them feel relaxed while at it. Improves target's obedience and reduces fatigue. ",
	SKILLDISCIPLINE = "Discipline",
	SKILLDISCIPLINEDESCRIPT = "Boosts target's manual labor performance. ",
	SKILLSEDATE = "Sedate",
	SKILLSEDATEDESCRIPT = "Puts target's mind at ease. Improves Obedience",
	SKILLFEAR = "Fear",
	SKILLFEARDESCRIPT = "Strikes fear into target's mind.",
	SKILLINNERVATE = "Innervate",
	SKILLINNERVATEDESCRIPT = "Restores target's energy.",
	SKILLSHACKLE = "Shackle",
	SKILLSHACKLEDESCRIPT = "Creates a magic shackles around target. As long as they persist, it will be unable to escape. Shackles can be dispelled with time if target's magic resistance is high. ",
	SKILLGREATSHACKLE = "Great Shackle",
	SKILLGREATSHACKLEDESCRIPT = "Creates a stronger version of magical shackles which are a lot harder to break.",
	SKILLMINDCONTROL = "Mind Control",
	SKILLMINDCONTROLDESCRIPT = "Overwhelms target's mind forcing a nearly complete submission. Can be resisted with powerful mind. ",
	
	PROFMASTER = "Master",
	PROFMASTERALT = "Mistress",
	PROFMASTERDESCRIPT = "The sole ruler of domain. $His power strike fear and respect even in those who are only joined recently.\n\nPraises and punishments twice as effective.",
	PROFRULER = "Ruler",
	PROFRULERDESCRIPT = "You decided to step up from being only a $master. ",
	PROFDIRECTOR = "Director",
	PROFDIRECTORDESCRIPT = "Director can issue a higher tier discipline on the servants in name of the master. ",
	PROFSADIST = "Sadist",
	PROFSADISTDESCRIPT = "Some people find it pleasant to relieve in pain of others. ",
	PROFWATCHDOG = "Watchdog",
	PROFWATCHDOGDESCRIPT = "The servants, who proven their loyal to master are allowed to act in his name to instigate obedience of others.",
	PROFHEADGIRL = "Headgirl",
	PROFHEADGIRLALT = "Headman",
	PROFHEADGIRLDESCRIPT = "The servant with higher authority is allowed to direct multiple lower servants at once.\n\nPraises and punishements 1.5 times as effective",
	PROFTRAINER = "Trainer",
	PROFTRAINERDESCRIPT = "Trainers can dramatically change the attitude of even very rebellious slave. ",
	PROFWORKER = "Worker",
	PROFWORKERDESCRIPT = "Workers are great manual laborers for your everyday needs. You won't need them to gather resources, but they will do it much faster. \n\nManual labor tasks efficieny +50%.",
	PROFFOREMAN = "Foreman",
	PROFFOREMANDESCRIPT = "A seasoned worker can not only show higher proficiency, but also boost productivity of other workers.\n\nManual labor tasks efficieny +33%.",
	PROFHUNTER = "Hunter",
	PROFHUNTERDESCRIPT = "Hunters specialize in tracking and killing the game. \n\nIncreases Hunting productivity by 50%. Allows to use Bows.",
	PROFSMITH = "Blacksmith",
	PROFSMITHDESCRIPT = "Smiths are mandatory when dealing with metalcrafting. \n\nAllows to craft metal items.",
	PROFCHEF = "Chef",
	PROFCHEFDESCRIPT = "A skilled cook is always a valuable addition to a growing group. \n\nCooking efficiency +50%.",
	PROFATTENDANT = "Attendant",
	PROFATTENDANTDESCRIPT = "Sometimes it's very valuable to have someone packed with nice stuff and free time on their hands.\n\nMost items can be used instantly in combat.",
	PROFALCHEMIST = "Alchemist",
	PROFALCHEMISTDESCRIPT = "Alchemists specialize in brewing processes which is invaluable for steady potion supplies. \n\nPotion brewing efficiency +200%.",
	PROFCATTLE = "Cattle",
	PROFCATTLEDESCRIPT = "Some people are just not cut out for anything better...\n\nIncreases farm task efficiency by 50%.",
	PROFBREEDER = "Breeder",
	PROFBREEDERDESCRIPT = "When you really want to emphasize on their purpose. \n\nIncreases farm task efficiency by additional 50%. Pregnancies last 50% less.",
	PROFHARLOT = "Harlot",
	PROFHARLOTDESCRIPT = "The eldest profession might not seem as much, but so far it's been always in demand.\n\nProstitution tasks are 50% more efficient.",
	PROFGEISHA = "Geisha",
	PROFGEISHADESCRIPT = "",
	PROFDANCER = "Dancer",
	PROFDANCERDESCRIPT = "Dancers can entice with their looks and moves. Effective for entertainement but not for the clumsy. ",
	PROFSUCCUBUS = "Succubus",
	PROFSUCCUBUSALT = "Incubus",
	PROFSUCCUBUSDESCRIPT = "Being a sex fiend is a tiresome, but undeniably noble occupation.\n\nSexual Rewards are twice as effective. Fatigue is alleviated from sex.",
	PROFTRUE_SUCCUBUS = "True Succubus",
	PROFTRUE_SUCCUBUSALT = "True Incubus",
	PROFTRUE_SUCCUBUSDESCRIPT = "You've just embraced your real inner self.\n\nSexual Rewards are twice as effective. Fatigue is alleviated from sex.",
	PROFPET = "Pet",
	PROFPETDESCRIPT = "Apparently, giving up your personal rights is not the worst thing in the world, even if you have to wear rather dubious garment.\n\nSexual Rewards are 1.5 times as effective.",
	PROFPETBEAST = "Pet",
	PROFPETBEASTDESCRIPT = "Deep inside you always just wished for nothing but a good master.\n\nSexual Rewards are 1.5 times as effective.",
	PROFSEXTOY = "Sex toy",
	PROFSEXTOYDESCRIPT = "The art of being an object of desire for others.\n\nSexual Rewards are twice as effective. Prostitution efficiency +50%.",
	PROFFIGHTER = "Fighter",
	PROFFIGHTERDESCRIPT = "You've had a dream of becoming a skilled adventurer. This might be a good first step. \n\nAllows the use of weapon and armor.",
	PROFKNIGHT = "Knight",
	PROFKNIGHTDESCRIPT = "A noble fighter ready to serve his master.",
	PROFAPPRENTICE = "Apprentice",
	PROFAPPRENTICEDESCRIPT = "After spending a good amount of time at the libraries you finally managed to show some magic potential.",
	PROFHEALER = "Healer",
	PROFHEALERDESCRIPT = "Focusing on defensive magic you managed to develop the tools suitable for this task, as well as your body.",
	PROFCASTER = "Caster",
	PROFCASTERDESCRIPT = "Long periods of practice have finally paid back. You've managed to sieze a greater power of arcane.",
	PROFDOMINATOR = "Dominator",
	PROFDOMINATORDESCRIPT = "You've always prefered a sly approach to a flashy one. There's no better solution for conflicts, than forcing others to do what you want. ",
	PROFBLOODMAGE = "Blood Mage",
	PROFBLOODMAGEDESCRIPT = "",
	
	PROFMAID = "Maid",
	PROFMAIDALT = "Butler",
	PROFMAIDDESCRIPT = "A trained servant not only knows their place but also is better to the eye.",
	PROFDRAGONKNIGHT = "Dragon Knight",
	PROFDRAGONKNIGHTDESCRIPT = "The dragon blood flowing in their veins allow them become a fearsome warriors resistant to fire.",
	PROFBERSERKER = "Berserker",
	PROFBERSERKERDESCRIPT = "",
	PROFDRUID = "Druid",
	PROFDRUIDDESCRIPT = "",
	PROFVALKYRIE = "Valkyrie",
	PROFVALKYRIEDESCRIPT = "",
	PROFSOULEATER = "Soul Eater",
	PROFSOULEATERDESCRIPT = "",
	PROFNECROMANCER = "Necromancer",
	PROFNECROMANCERDESCRIPT = "",
	PROFARCHER = "Archer",
	PROFARCHERDESCRIPT = "",
	PROFSNIPER = "Sniper",
	PROFSNIPERDESCRIPT = "",
	PROFROGUE = "Rogue",
	PROFROGUEDESCRIPT = "",
	PROFASSASSIN = "Assassin",
	PROFASSASSINDESCRIPT = "",
	
}
