	MSLMCONTEXT_OPEN_CLASS_TAB = "Class & Skills",
	MSLMCONTEXT_OPEN_SIBLINGS_TAB = "Training & Rules",
	MSLMCONTEXT_OPEN_CUSTOMIZATION_TAB = "Customization",
	MSLMCONTEXT_OPEN_OCCUPATION = "Occupation",
