extends Reference

# GENERATED by doll2_catalogue_build.gd - DO NOT EDIT.
# Semantics for the Doll 2 Spine export: groups, parts and axis values.
# Change doll2_overrides.gd and rebuild instead of editing this file.
# Mesh, vertex, UV and animation data stay in the Spine JSON.

const SCHEMA_VERSION = 2

const SOURCE = {
	"atlas": "Doll2_spine4.2_female.atlas",
	"attachment_count": 664,
	"bone_count": 271,
	"contract": "doll2_v1",
	"skeleton": "Doll2_spine4.2_female.json",
	"skeleton_hash": "D+tm6YqZvdA",
	"slot_count": 73,
	"spine_version": "4.2.43",
}

const SLOT_ORDER = [
	"animal_body",
	"weapon_back",
	"wings",
	"hairs_back",
	"tails",
	"equip_back",
	"hand_left",
	"equip_hand_left",
	"arm_left",
	"race_arm_left",
	"equip_arm_left",
	"shoulder_left",
	"race_shoulder_left",
	"equip_shoulder_left",
	"hand_right",
	"equip_hand_right",
	"arm_right",
	"race_arm_right",
	"equip_arm_right",
	"shoulder_right",
	"race_shoulder_right",
	"equip_shoulder_right",
	"torso",
	"equip_collar",
	"torso_nipples_mask",
	"leg_left",
	"race_leg_left",
	"equip_leg_left",
	"leg_right",
	"race_leg_right",
	"equip_leg_right",
	"pelvis",
	"belly",
	"equip_torso",
	"breasts_beastkin_many",
	"beastkin_torso_many_nipples",
	"race_pelvis",
	"animal_frontbody",
	"testicle",
	"equip_pelvis",
	"equip_belly",
	"pregnancy_belly",
	"race_torso_lower",
	"breasts_beastkin_pregnancy",
	"beastkin_pregnancy_nipple",
	"tatoos",
	"dick",
	"equip_pregnancy_low",
	"equip_pregnancy_up",
	"weapon_belt",
	"breasts",
	"breasts_beastkin",
	"breast_nipples",
	"race_torso",
	"equip_breasts",
	"hairs_assist",
	"head_skull",
	"head",
	"sclera",
	"eyes",
	"eyes_hearts",
	"race_head",
	"face",
	"hairs_base",
	"ears",
	"lips",
	"eyebrows",
	"noses",
	"blush",
	"hairs_fringe",
	"equip_masks",
	"equip_head",
	"horns",
]

const DRAW_ORDER = [
	"animal_body",
	"weapon_back",
	"wings",
	"hairs_back",
	"tails",
	"equip_back",
	"hand_left",
	"equip_hand_left",
	"arm_left",
	"race_arm_left",
	"equip_arm_left",
	"shoulder_left",
	"race_shoulder_left",
	"equip_shoulder_left",
	"hand_right",
	"equip_hand_right",
	"arm_right",
	"race_arm_right",
	"equip_arm_right",
	"shoulder_right",
	"race_shoulder_right",
	"equip_shoulder_right",
	"torso",
	"equip_collar",
	"torso_nipples_mask",
	"leg_left",
	"race_leg_left",
	"equip_leg_left",
	"leg_right",
	"race_leg_right",
	"equip_leg_right",
	"pelvis",
	"belly",
	"tatoos",
	"race_torso_lower",
	"race_torso",
	"race_pelvis",
	"equip_torso",
	"breasts_beastkin_many",
	"beastkin_torso_many_nipples",
	"animal_frontbody",
	"testicle",
	"dick",
	"equip_pelvis",
	"equip_belly",
	"pregnancy_belly",
	"breasts_beastkin_pregnancy",
	"beastkin_pregnancy_nipple",
	"equip_pregnancy_low",
	"equip_pregnancy_up",
	"weapon_belt",
	"breasts",
	"breasts_beastkin",
	"breast_nipples",
	"equip_breasts",
	"hairs_assist",
	"head_skull",
	"head",
	"sclera",
	"eyes",
	"eyes_hearts",
	"race_head",
	"face",
	"ears",
	"hairs_base",
	"lips",
	"eyebrows",
	"noses",
	"blush",
	"hairs_fringe",
	"equip_masks",
	"equip_head",
	"horns",
]

const DRAW_ORDER_FIXES = [
	{
		"before": "equip_torso",
		"slot": "tatoos",
	},
	{
		"before": "equip_pelvis",
		"slot": "dick",
	},
	{
		"before": "hairs_base",
		"slot": "ears",
	},
	{
		"before": "equip_torso",
		"slot": "race_torso_lower",
	},
	{
		"before": "equip_torso",
		"slot": "race_torso",
	},
	{
		"before": "equip_torso",
		"slot": "race_pelvis",
	},
]

const GROUP_ORDER = [
	"body",
	"head",
	"face",
	"eyes",
	"eyebrows",
	"eyes_effect",
	"blush",
	"nose",
	"lips",
	"ears",
	"hair",
	"hair_back",
	"hair_assist",
	"horns",
	"wings",
	"tails",
	"animal_body",
	"race_overlay",
	"face_markings",
	"genitals",
	"tattoo",
	"outfit",
	"outfit_legs",
	"outfit_hands",
	"collar",
	"headgear",
	"mask",
	"weapon_belt",
	"weapon_back",
]

const AXES = {
	"belly_shape": {
		"default": "default",
		"label": "DOLL2_PREVIEW_BELLY_SHAPE",
		"values": ["default", "muscle"],
	},
	"hand_pose": {
		"default": "1",
		"label": "DOLL2_PREVIEW_HAND_POSE",
		"values": ["1", "2", "3"],
	},
	"legs": {
		"default": "default",
		"label": "DOLL2_PREVIEW_LEGS",
		"values": ["default", "orc"],
	},
	"many_tits": {
		"default": "none",
		"label": "DOLL2_PREVIEW_MANY_TITS",
		"values": ["none", "4", "6"],
	},
	"pregnancy": {
		"default": "none",
		"label": "DOLL2_PREVIEW_PREGNANCY",
		"values": ["none", "mid", "big"],
	},
	"tits_size": {
		"default": "large",
		"label": "DOLL2_PREVIEW_BREAST_SIZE",
		"values": ["flat", "small", "normal", "large", "big"],
	},
}

const FIXED_SLOTS = {
	"sclera": "sklera",
}

const COLOR_CHANNELS = {
	"animal": {
		"anchor": "animal_body",
		"coverage": false,
		"gear": false,
		"slots": ["animal_body", "animal_frontbody"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": true,
	},
	"collar": {
		"anchor": "collar",
		"coverage": false,
		"gear": true,
		"slots": ["equip_collar"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": true,
	},
	"ears": {
		"anchor": "ears",
		"coverage": false,
		"gear": false,
		"slots": ["ears"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": false,
	},
	"eyebrows": {
		"anchor": "eyebrows",
		"coverage": false,
		"gear": false,
		"slots": ["eyebrows"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": false,
	},
	"eyes": {
		"anchor": "eyes",
		"coverage": false,
		"gear": false,
		"slots": ["eyes", "eyes_hearts"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": false,
	},
	"face_markings": {
		"anchor": "face_markings",
		"coverage": false,
		"gear": false,
		"slots": ["race_head"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": false,
	},
	"hair": {
		"anchor": "hair",
		"coverage": false,
		"gear": false,
		"slots": ["hairs_base", "hairs_fringe"],
		"two_tone": true,
		"zone_defaults": [],
		"zones": false,
	},
	"hair_assist": {
		"anchor": "hair_assist",
		"coverage": false,
		"gear": false,
		"slots": ["hairs_assist"],
		"two_tone": true,
		"zone_defaults": [],
		"zones": false,
	},
	"hair_back": {
		"anchor": "hair_back",
		"coverage": false,
		"gear": false,
		"slots": ["hairs_back"],
		"two_tone": true,
		"zone_defaults": [],
		"zones": false,
	},
	"headgear": {
		"anchor": "headgear",
		"coverage": false,
		"gear": true,
		"slots": ["equip_head"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": true,
	},
	"horns": {
		"anchor": "horns",
		"coverage": false,
		"gear": false,
		"slots": ["horns"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": false,
	},
	"lips": {
		"anchor": "lips",
		"coverage": false,
		"gear": false,
		"slots": ["lips"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": false,
	},
	"mask": {
		"anchor": "mask",
		"coverage": false,
		"gear": true,
		"slots": ["equip_masks"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": true,
	},
	"nipples": {
		"anchor": "body",
		"coverage": false,
		"gear": false,
		"slots": [
			"beastkin_pregnancy_nipple",
			"beastkin_torso_many_nipples",
			"breast_nipples",
			"torso_nipples_mask",
		],
		"two_tone": false,
		"zone_defaults": [],
		"zones": false,
	},
	"outfit": {
		"anchor": "outfit",
		"coverage": false,
		"gear": true,
		"slots": [
			"equip_arm_left",
			"equip_arm_right",
			"equip_back",
			"equip_belly",
			"equip_breasts",
			"equip_hand_left",
			"equip_hand_right",
			"equip_pregnancy_low",
			"equip_pregnancy_up",
			"equip_shoulder_left",
			"equip_shoulder_right",
			"equip_torso",
		],
		"two_tone": false,
		"zone_defaults": [],
		"zones": true,
	},
	"outfit_lower": {
		"anchor": "outfit",
		"coverage": false,
		"gear": true,
		"slots": ["equip_leg_left", "equip_leg_right", "equip_pelvis"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": true,
	},
	"race": {
		"anchor": "race_overlay",
		"coverage": false,
		"gear": false,
		"slots": [
			"race_arm_left",
			"race_arm_right",
			"race_leg_left",
			"race_leg_right",
			"race_pelvis",
			"race_shoulder_left",
			"race_shoulder_right",
			"race_torso",
			"race_torso_lower",
		],
		"two_tone": false,
		"zone_defaults": [],
		"zones": false,
	},
	"skin": {
		"anchor": "body",
		"coverage": true,
		"gear": false,
		"slots": [
			"arm_left",
			"arm_right",
			"belly",
			"breasts",
			"breasts_beastkin",
			"breasts_beastkin_many",
			"breasts_beastkin_pregnancy",
			"dick",
			"face",
			"hand_left",
			"hand_right",
			"head",
			"head_skull",
			"leg_left",
			"leg_right",
			"noses",
			"pelvis",
			"pregnancy_belly",
			"shoulder_left",
			"shoulder_right",
			"testicle",
			"torso",
		],
		"two_tone": false,
		"zone_defaults": [],
		"zones": false,
	},
	"tail": {
		"anchor": "tails",
		"coverage": false,
		"gear": false,
		"slots": ["tails"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": false,
	},
	"tattoo": {
		"anchor": "tattoo",
		"coverage": false,
		"gear": false,
		"slots": ["tatoos"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": false,
	},
	"weapon": {
		"anchor": "weapon_belt",
		"coverage": false,
		"gear": true,
		"slots": ["weapon_back", "weapon_belt"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": true,
	},
	"wings": {
		"anchor": "wings",
		"coverage": false,
		"gear": false,
		"slots": ["wings"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": true,
	},
}

const SLOT_COLORS = {
	"animal_body": "animal",
	"animal_frontbody": "animal",
	"arm_left": "skin",
	"arm_right": "skin",
	"beastkin_pregnancy_nipple": "nipples",
	"beastkin_torso_many_nipples": "nipples",
	"belly": "skin",
	"breast_nipples": "nipples",
	"breasts": "skin",
	"breasts_beastkin": "skin",
	"breasts_beastkin_many": "skin",
	"breasts_beastkin_pregnancy": "skin",
	"dick": "skin",
	"ears": "ears",
	"equip_arm_left": "outfit",
	"equip_arm_right": "outfit",
	"equip_back": "outfit",
	"equip_belly": "outfit",
	"equip_breasts": "outfit",
	"equip_collar": "collar",
	"equip_hand_left": "outfit",
	"equip_hand_right": "outfit",
	"equip_head": "headgear",
	"equip_leg_left": "outfit_lower",
	"equip_leg_right": "outfit_lower",
	"equip_masks": "mask",
	"equip_pelvis": "outfit_lower",
	"equip_pregnancy_low": "outfit",
	"equip_pregnancy_up": "outfit",
	"equip_shoulder_left": "outfit",
	"equip_shoulder_right": "outfit",
	"equip_torso": "outfit",
	"eyebrows": "eyebrows",
	"eyes": "eyes",
	"eyes_hearts": "eyes",
	"face": "skin",
	"hairs_assist": "hair_assist",
	"hairs_back": "hair_back",
	"hairs_base": "hair",
	"hairs_fringe": "hair",
	"hand_left": "skin",
	"hand_right": "skin",
	"head": "skin",
	"head_skull": "skin",
	"horns": "horns",
	"leg_left": "skin",
	"leg_right": "skin",
	"lips": "lips",
	"noses": "skin",
	"pelvis": "skin",
	"pregnancy_belly": "skin",
	"race_arm_left": "race",
	"race_arm_right": "race",
	"race_head": "face_markings",
	"race_leg_left": "race",
	"race_leg_right": "race",
	"race_pelvis": "race",
	"race_shoulder_left": "race",
	"race_shoulder_right": "race",
	"race_torso": "race",
	"race_torso_lower": "race",
	"shoulder_left": "skin",
	"shoulder_right": "skin",
	"tails": "tail",
	"tatoos": "tattoo",
	"testicle": "skin",
	"torso": "skin",
	"torso_nipples_mask": "nipples",
	"weapon_back": "weapon",
	"weapon_belt": "weapon",
	"wings": "wings",
}

const ZONE_HUES = [299, 90, 156]

const ZONE_DISTANCE = [20, 32, 26]

const ZONE_DEFAULTS = [
	Color(0.482353, 0.517647, 0.564706, 1),
	Color(0.435294, 0.317647, 0.2, 1),
	Color(0.552941, 0.231373, 0.231373, 1),
]

const GROUPS = {
	"animal_body": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_ANIMAL_BODY",
		"optional": true,
		"order": 15,
		"parts": ["arachna_body", "kentaur_body", "lamia_body", "scylla_body"],
		"slots": ["animal_body", "animal_frontbody"],
	},
	"blush": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_BLUSH",
		"optional": true,
		"order": 5,
		"parts": ["blush"],
		"slots": ["blush"],
	},
	"body": {
		"default": "body_female_base",
		"kind": "set",
		"label": "DOLL2_PREVIEW_BODY",
		"optional": false,
		"order": 0,
		"parts": ["body_female_base", "body_female_beastkin"],
		"slots": [
			"arm_left",
			"arm_right",
			"beastkin_pregnancy_nipple",
			"beastkin_torso_many_nipples",
			"belly",
			"breast_nipples",
			"breasts",
			"breasts_beastkin",
			"breasts_beastkin_many",
			"breasts_beastkin_pregnancy",
			"hand_left",
			"hand_right",
			"leg_left",
			"leg_right",
			"pelvis",
			"pregnancy_belly",
			"shoulder_left",
			"shoulder_right",
			"torso",
			"torso_nipples_mask",
		],
	},
	"collar": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_COLLAR",
		"optional": true,
		"order": 23,
		"parts": [
			"collar_bell",
			"collar_heart",
			"collar_leather",
			"collar_metallic",
			"collar_playboy",
			"collar_steel",
		],
		"slots": ["equip_collar"],
	},
	"ears": {
		"default": "ears_human",
		"kind": "options",
		"label": "DOLL2_PREVIEW_EARS",
		"optional": true,
		"order": 7,
		"parts": [
			"ears_cat",
			"ears_elven",
			"ears_elven2",
			"ears_fox_n1",
			"ears_fox_n2",
			"ears_fox_n3",
			"ears_fox_n4",
			"ears_goblin",
			"ears_human",
			"ears_mouse",
			"ears_nereid",
			"ears_orc",
			"ears_rabbit",
			"ears_rabbit2",
			"ears_rabbit3",
			"ears_tanuk",
			"ears_taurus",
			"ears_wolf",
		],
		"slots": ["ears"],
	},
	"eyebrows": {
		"default": "eyebrows1",
		"kind": "options",
		"label": "DOLL2_PREVIEW_EYEBROWS",
		"optional": true,
		"order": 4,
		"parts": [
			"eyebrows1",
			"eyebrows2",
			"eyebrows3",
			"eyebrows4",
			"eyebrows5",
			"eyebrows_m1",
			"eyebrows_m2",
			"eyebrows_m3",
		],
		"slots": ["eyebrows"],
	},
	"eyes": {
		"default": "eyes1",
		"kind": "options",
		"label": "DOLL2_PREVIEW_EYES",
		"optional": false,
		"order": 3,
		"parts": ["eyes1", "eyes2", "eyes3", "eyes5", "eyes_m5"],
		"slots": ["eyes"],
	},
	"eyes_effect": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_EYES_EFFECT",
		"optional": true,
		"order": 4,
		"parts": ["eyes_hearts"],
		"slots": ["eyes_hearts"],
	},
	"face": {
		"default": "face7",
		"kind": "options",
		"label": "DOLL2_PREVIEW_FACE",
		"optional": false,
		"order": 2,
		"parts": [
			"beastkin_face10",
			"beastkin_face6",
			"beastkin_face7",
			"beastkin_face8",
			"beastkin_face9",
			"beastkin_face_m1",
			"beastkin_face_m2",
			"beastkin_face_m3",
			"beastkin_face_m4",
			"beastkin_face_m5",
			"face10",
			"face6",
			"face7",
			"face8",
			"face9",
			"face_m1",
			"face_m2",
			"face_m3",
			"face_m4",
			"face_m5",
		],
		"slots": ["face"],
	},
	"face_markings": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_FACE_MARKINGS",
		"optional": true,
		"order": 17,
		"parts": ["head_dragon_mask", "head_dragon_mask_2", "kobold_head_kobold", "kobold_head_mask1"],
		"slots": ["race_head"],
	},
	"genitals": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_GENITALS",
		"optional": true,
		"order": 18,
		"parts": ["Dick_furry_up", "Dick_horse_up", "Dick_human_up"],
		"slots": ["dick", "testicle"],
	},
	"hair": {
		"default": "hair_base_straight",
		"kind": "options",
		"label": "DOLL2_PREVIEW_HAIR",
		"optional": true,
		"order": 8,
		"parts": [
			"hair_base_back",
			"hair_base_braids",
			"hair_base_default",
			"hair_base_disheveled",
			"hair_base_fringe",
			"hair_base_fringe_2",
			"hair_base_kare",
			"hair_base_parting",
			"hair_base_slave",
			"hair_base_straight",
			"hair_base_undercut",
			"hairs_base_dopple",
		],
		"slots": ["hairs_base", "hairs_fringe"],
	},
	"hair_assist": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_HAIR_ACCESSORY",
		"optional": true,
		"order": 11,
		"parts": [
			"braid",
			"hair_assist_twin_tails",
			"hair_assist_twin_tails_2",
			"hair_spiral",
			"pigtails",
			"ponytail",
			"twin_braids",
			"twin_tails_3",
		],
		"slots": ["hairs_assist"],
	},
	"hair_back": {
		"default": "hair_back_straight",
		"kind": "options",
		"label": "DOLL2_PREVIEW_HAIR_BACK",
		"optional": true,
		"order": 10,
		"parts": [
			"hair_back_care",
			"hair_back_double_tail_long",
			"hair_back_ponytail_long",
			"hair_back_straight",
			"hair_back_verylong1",
			"hair_back_wawe",
		],
		"slots": ["hairs_back"],
	},
	"head": {
		"default": "head_chin_default",
		"kind": "options",
		"label": "DOLL2_PREVIEW_HEAD",
		"optional": false,
		"order": 1,
		"parts": [
			"beastkin_chin_cat",
			"beastkin_chin_fox",
			"beastkin_chin_rabbit",
			"beastkin_chin_tanuki",
			"beastkin_chin_wolf",
			"beastkin_head_muzzle_1",
			"beastkin_head_muzzle_2",
			"beastkin_head_muzzle_3",
			"head_chin_curve",
			"head_chin_curve_kobold",
			"head_chin_default",
			"head_chin_kobold2",
			"head_chin_long_skinny",
			"head_chin_muscle",
			"head_chin_short",
			"head_chin_small_c",
		],
		"slots": ["head", "head_skull"],
	},
	"headgear": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_HEADGEAR",
		"optional": true,
		"order": 24,
		"parts": [
			"Petsuit_cat",
			"Petsuit_rabbit3",
			"hair_armor_maid",
			"hair_armor_playboy",
			"hair_armor_waitress",
		],
		"slots": ["equip_head"],
	},
	"horns": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_HORNS",
		"optional": true,
		"order": 12,
		"parts": [
			"Horn_straight_diagonal",
			"Horn_straight_top",
			"horn_curve_down",
			"horn_curve_top",
			"horn_curve_up",
			"horn_dragon2",
			"horn_seraph_fibule",
			"horn_spiral_2",
		],
		"slots": ["horns"],
	},
	"lips": {
		"default": "lips1",
		"kind": "options",
		"label": "DOLL2_PREVIEW_LIPS",
		"optional": true,
		"order": 6,
		"parts": [
			"beastkin_lips_cry",
			"beastkin_lips_open",
			"beastkin_lips_smile",
			"lips1",
			"lips2",
			"lips3",
			"lips4",
			"lips5",
			"lips_beast",
			"lips_m1",
			"lips_m2",
			"lips_m3",
			"lips_m4",
			"lips_orc",
			"lips_orc_1",
			"lips_orc_2",
			"lips_orc_3",
			"lips_s1",
			"lips_s2",
		],
		"slots": ["lips"],
	},
	"mask": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_MASK",
		"optional": true,
		"order": 25,
		"parts": ["facemask1", "facemask2"],
		"slots": ["equip_masks"],
	},
	"nose": {
		"default": "nose_default",
		"kind": "options",
		"label": "DOLL2_PREVIEW_NOSE",
		"optional": true,
		"order": 5,
		"parts": [
			"nose_default",
			"nose_dwarf",
			"nose_feature",
			"nose_kobold",
			"nose_kobold_2",
			"nose_point",
			"nose_small",
			"nose_straight",
		],
		"slots": ["noses"],
	},
	"outfit": {
		"default": "",
		"kind": "set",
		"label": "DOLL2_PREVIEW_OUTFIT",
		"optional": true,
		"order": 20,
		"parts": [
			"outfit_cloth",
			"outfit_cloth3",
			"outfit_gipure1",
			"outfit_gipure2",
			"outfit_jacket",
			"outfit_latex",
			"outfit_leather",
			"outfit_leather2",
			"outfit_maid",
			"outfit_petsuit",
			"outfit_plate",
			"outfit_plate2",
			"outfit_playboy",
			"outfit_slave",
			"outfit_smith",
			"outfit_tentacle",
			"outfit_underwear1",
			"outfit_underwear2",
			"outfit_waitress",
		],
		"slots": [
			"equip_arm_left",
			"equip_arm_right",
			"equip_back",
			"equip_belly",
			"equip_breasts",
			"equip_hand_left",
			"equip_hand_right",
			"equip_leg_left",
			"equip_leg_right",
			"equip_pelvis",
			"equip_pregnancy_low",
			"equip_pregnancy_up",
			"equip_shoulder_left",
			"equip_shoulder_right",
			"equip_torso",
		],
	},
	"outfit_hands": {
		"default": "",
		"kind": "set",
		"label": "DOLL2_PREVIEW_OUTFIT_HANDS",
		"optional": true,
		"order": 22,
		"parts": [
			"outfit_latex_hands",
			"outfit_maid_hands",
			"outfit_petsuit_hands",
			"outfit_playboy_hands",
		],
		"slots": ["equip_hand_left", "equip_hand_right"],
	},
	"outfit_legs": {
		"default": "",
		"kind": "set",
		"label": "DOLL2_PREVIEW_OUTFIT_LEGS",
		"optional": true,
		"order": 21,
		"parts": [
			"outfit_cloth3_legs",
			"outfit_cloth_legs",
			"outfit_gipure1_legs",
			"outfit_gipure2_legs",
			"outfit_jacket_legs",
			"outfit_latex_legs",
			"outfit_leather2_legs",
			"outfit_leather_legs",
			"outfit_maid_legs",
			"outfit_petsuit_legs",
			"outfit_plate2_legs",
			"outfit_plate_legs",
			"outfit_playboy_legs",
			"outfit_slave_legs",
			"outfit_smith_legs",
			"outfit_tentacle_legs",
			"outfit_underwear1_legs",
			"outfit_underwear2_legs",
			"outfit_waitress_legs",
		],
		"slots": ["equip_leg_left", "equip_leg_right", "equip_pelvis"],
	},
	"race_overlay": {
		"default": "",
		"kind": "set",
		"label": "DOLL2_PREVIEW_RACE_OVERLAY",
		"optional": true,
		"order": 16,
		"parts": [
			"race_dragon",
			"race_dragon_scales",
			"race_dragon_scales2",
			"race_dryad",
			"race_kobold",
			"race_kobold_spots",
			"race_nereid",
			"race_slime",
		],
		"slots": [
			"race_arm_left",
			"race_arm_right",
			"race_leg_left",
			"race_leg_right",
			"race_pelvis",
			"race_shoulder_left",
			"race_shoulder_right",
			"race_torso",
			"race_torso_lower",
		],
	},
	"tails": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_TAILS",
		"optional": true,
		"order": 14,
		"parts": [
			"tail_cat",
			"tail_demon",
			"tail_dragon",
			"tail_dragon2",
			"tail_fox",
			"tail_fox_2",
			"tail_fox_3",
			"tail_kobold",
			"tail_mouse",
			"tail_nereid",
			"tail_tanuk",
			"tail_wolf",
		],
		"slots": ["tails"],
	},
	"tattoo": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_TATTOO",
		"optional": true,
		"order": 19,
		"parts": [
			"tatoo_womb1",
			"tatoo_womb10",
			"tatoo_womb2",
			"tatoo_womb3",
			"tatoo_womb4",
			"tatoo_womb5",
			"tatoo_womb6",
			"tatoo_womb7",
			"tatoo_womb8",
			"tatoo_womb9",
		],
		"slots": ["tatoos"],
	},
	"weapon_back": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_WEAPON_BACK",
		"optional": true,
		"order": 27,
		"parts": [
			"weapon_back_axe1",
			"weapon_back_axe2",
			"weapon_back_bow",
			"weapon_back_bow2",
			"weapon_back_crossbow1",
			"weapon_back_crossbow2",
			"weapon_back_mace2",
			"weapon_back_spear",
			"weapon_back_spear2",
			"weapon_back_stick",
			"weapon_back_stick2",
		],
		"slots": ["weapon_back"],
	},
	"weapon_belt": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_WEAPON_BELT",
		"optional": true,
		"order": 26,
		"parts": [
			"weapon_belt_bat",
			"weapon_belt_dagger",
			"weapon_belt_dagger2",
			"weapon_belt_mace",
			"weapon_belt_sword",
			"weapon_belt_sword2",
		],
		"slots": ["weapon_belt"],
	},
	"wings": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_WINGS",
		"optional": true,
		"order": 13,
		"parts": ["Wings_dragon", "Wings_fairy", "Wings_seraph", "wings_demon", "wings_harpia"],
		"slots": ["wings"],
	},
}

const PARTS = {
	"Dick_furry_up": {
		"folders": ["13_dicks"],
		"group": "genitals",
		"slots": {
			"dick": "dick_furry_up",
			"testicle": "testicle_furry",
		},
		"zones": [0],
	},
	"Dick_horse_up": {
		"folders": ["13_dicks"],
		"group": "genitals",
		"slots": {
			"dick": "dick_horse_up__body_female_beastkin",
			"testicle": "testicle_furry",
		},
		"zones": [0],
	},
	"Dick_human_up": {
		"folders": ["13_dicks"],
		"group": "genitals",
		"slots": {
			"dick": "dick_horse_up",
			"testicle": "testicle_human",
		},
	},
	"Horn_straight_diagonal": {
		"folders": ["08_horns"],
		"group": "horns",
		"slots": {
			"horns": "horn_straight_diagonal",
		},
	},
	"Horn_straight_top": {
		"folders": ["08_horns"],
		"group": "horns",
		"slots": {
			"horns": "horn_straight_top",
		},
	},
	"Petsuit_cat": {
		"folders": ["151_armory_acces_petsuit"],
		"group": "headgear",
		"slots": {
			"equip_head": "petsuit_cat",
		},
		"zones": [0],
	},
	"Petsuit_rabbit3": {
		"folders": ["151_armory_acces_petsuit"],
		"group": "headgear",
		"slots": {
			"equip_head": "petsuit_rabbit3",
		},
		"zones": [0],
	},
	"Wings_dragon": {
		"folders": ["09_wings"],
		"group": "wings",
		"slots": {
			"wings": "wings_dragon",
		},
	},
	"Wings_fairy": {
		"folders": ["09_wings"],
		"group": "wings",
		"slots": {
			"wings": "wings_fairy",
		},
		"zones": [2],
	},
	"Wings_seraph": {
		"folders": ["09_wings"],
		"group": "wings",
		"slots": {
			"wings": "wings_seraph",
		},
		"zones": [0],
	},
	"arachna_body": {
		"folders": ["14_animals_body"],
		"group": "animal_body",
		"hides": [
			"leg_left",
			"leg_right",
			"equip_leg_left",
			"equip_leg_right",
			"race_leg_left",
			"race_leg_right",
			"dick",
			"testicle",
			"pelvis",
			"equip_pelvis",
			"race_pelvis",
		],
		"slots": {
			"animal_body": "arachna_body",
			"animal_frontbody": "arachna_helicere",
		},
	},
	"beastkin_chin_cat": {
		"display": "Muzzle: cat",
		"folders": ["16_beastkin_heads_new"],
		"group": "head",
		"slots": {
			"head": "beastkin_chin_cat",
			"head_skull": "beastkin_skull",
		},
		"tags": ["beastkin"],
		"zones": [0],
	},
	"beastkin_chin_fox": {
		"display": "Muzzle: fox",
		"folders": ["16_beastkin_heads_new"],
		"group": "head",
		"slots": {
			"head": "beastkin_chin_fox",
			"head_skull": "beastkin_skull",
		},
		"tags": ["beastkin"],
		"zones": [0],
	},
	"beastkin_chin_rabbit": {
		"display": "Muzzle: rabbit",
		"folders": ["16_beastkin_heads_new"],
		"group": "head",
		"slots": {
			"head": "beastkin_chin_rabbit",
			"head_skull": "beastkin_skull",
		},
		"tags": ["beastkin"],
		"zones": [0],
	},
	"beastkin_chin_tanuki": {
		"display": "Muzzle: tanuki",
		"folders": ["16_beastkin_heads_new"],
		"group": "head",
		"slots": {
			"head": "beastkin_chin_tanuki",
			"head_skull": "beastkin_skull",
		},
		"tags": ["beastkin"],
		"zones": [0],
	},
	"beastkin_chin_wolf": {
		"display": "Muzzle: wolf",
		"folders": ["16_beastkin_heads_new"],
		"group": "head",
		"slots": {
			"head": "beastkin_chin_wolf",
			"head_skull": "beastkin_skull",
		},
		"tags": ["beastkin"],
		"zones": [0],
	},
	"beastkin_face10": {
		"folders": ["17_beastkin_faces"],
		"group": "face",
		"slots": {
			"face": "17_beastkin_faces/beastkin_face10",
		},
		"tags": ["beastkin"],
		"zones": [0],
	},
	"beastkin_face6": {
		"folders": ["17_beastkin_faces"],
		"group": "face",
		"slots": {
			"face": "17_beastkin_faces/beastkin_face6",
		},
		"tags": ["beastkin"],
	},
	"beastkin_face7": {
		"folders": ["17_beastkin_faces"],
		"group": "face",
		"slots": {
			"face": "17_beastkin_faces/beastkin_face7",
		},
		"tags": ["beastkin"],
	},
	"beastkin_face8": {
		"folders": ["17_beastkin_faces"],
		"group": "face",
		"slots": {
			"face": "17_beastkin_faces/beastkin_face8",
		},
		"tags": ["beastkin"],
	},
	"beastkin_face9": {
		"folders": ["17_beastkin_faces"],
		"group": "face",
		"slots": {
			"face": "17_beastkin_faces/beastkin_face9",
		},
		"tags": ["beastkin"],
	},
	"beastkin_face_m1": {
		"folders": ["17_beastkin_faces"],
		"group": "face",
		"slots": {
			"face": "beastkin_face_m1",
		},
		"tags": ["beastkin"],
	},
	"beastkin_face_m2": {
		"folders": ["17_beastkin_faces"],
		"group": "face",
		"slots": {
			"face": "beastkin_face_m2",
		},
		"tags": ["beastkin"],
	},
	"beastkin_face_m3": {
		"folders": ["17_beastkin_faces"],
		"group": "face",
		"slots": {
			"face": "beastkin_face_m3",
		},
		"tags": ["beastkin"],
	},
	"beastkin_face_m4": {
		"folders": ["17_beastkin_faces"],
		"group": "face",
		"slots": {
			"face": "beastkin_face_m4",
		},
		"tags": ["beastkin"],
	},
	"beastkin_face_m5": {
		"folders": ["17_beastkin_faces"],
		"group": "face",
		"slots": {
			"face": "beastkin_face_m5",
		},
		"tags": ["beastkin"],
	},
	"beastkin_head_muzzle_1": {
		"display": "Muzzle: 1",
		"folders": ["16_beastkin_heads"],
		"group": "head",
		"slots": {
			"head": "16_beastkin_heads/beastkin_head_muzzle_1",
			"head_skull": "beastkin_skull",
		},
		"tags": ["beastkin"],
		"zones": [0],
	},
	"beastkin_head_muzzle_2": {
		"display": "Muzzle: 2",
		"folders": ["16_beastkin_heads"],
		"group": "head",
		"slots": {
			"head": "16_beastkin_heads/beastkin_head_muzzle_2",
			"head_skull": "beastkin_skull",
		},
		"tags": ["beastkin"],
		"zones": [0],
	},
	"beastkin_head_muzzle_3": {
		"display": "Muzzle: 3",
		"folders": ["16_beastkin_heads"],
		"group": "head",
		"slots": {
			"head": "16_beastkin_heads/beastkin_head_muzzle_3",
			"head_skull": "beastkin_skull",
		},
		"tags": ["beastkin"],
		"zones": [0],
	},
	"beastkin_lips_cry": {
		"folders": ["17_beastkin_lips"],
		"group": "lips",
		"slots": {
			"lips": "beastkin_lips_cry",
		},
		"tags": ["beastkin"],
	},
	"beastkin_lips_open": {
		"folders": ["17_beastkin_lips"],
		"group": "lips",
		"slots": {
			"lips": "beastkin_lips_open__body_female_beastkin",
		},
		"tags": ["beastkin"],
	},
	"beastkin_lips_smile": {
		"folders": ["17_beastkin_lips"],
		"group": "lips",
		"slots": {
			"lips": "beastkin_lips_smile",
		},
		"tags": ["beastkin"],
	},
	"blush": {
		"folders": ["01_heads"],
		"group": "blush",
		"slots": {
			"blush": "01_heads/blush",
		},
	},
	"body_female_base": {
		"display": "Female base body",
		"extra_options": {
			"hand_left": ["00_body_nude_female/HandL1_orc", "00_body_nude_female/HandL3_orc"],
			"hand_right": ["00_body_nude_female/HandR1_orc", "00_body_nude_female/HandR3_orc"],
		},
		"folders": ["00_body_nude_female"],
		"group": "body",
		"slots": {
			"arm_left": "arml1",
			"arm_right": "armr1",
			"belly": {
				"axis": "belly_shape",
				"options": {
					"default": "default_belly",
					"muscle": "00_body_nude_female/default_belly_muscle",
				},
			},
			"breast_nipples": {
				"axis": "tits_size",
				"options": {
					"big": "tits_nipples_big",
					"large": "tits_nipples_large",
					"normal": "tits_nipples_normal",
					"small": "tits_nipples_small",
				},
			},
			"breasts": {
				"axis": "tits_size",
				"options": {
					"big": "tits_big",
					"large": "tits_large",
					"normal": "tits_normal",
					"small": "tits_small",
				},
			},
			"hand_left": {
				"axis": "hand_pose",
				"options": {
					"1": "handl1",
					"2": "handl2",
					"3": "handl3",
				},
			},
			"hand_right": {
				"axis": "hand_pose",
				"options": {
					"1": "handr1",
					"2": "handr2",
					"3": "handr3",
				},
			},
			"leg_left": {
				"axis": "legs",
				"options": {
					"default": "legl",
					"orc": "00_body_nude_female/legl_orc",
				},
			},
			"leg_right": {
				"axis": "legs",
				"options": {
					"default": "legr",
					"orc": "00_body_nude_female/legr_orc",
				},
			},
			"pelvis": "pelvis",
			"pregnancy_belly": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_belly_big",
					"mid": "pregnancy_belly_mid",
				},
			},
			"shoulder_left": "shoulderl",
			"shoulder_right": "shoulderr",
			"torso": "torso",
			"torso_nipples_mask": "torso_nipples_mask",
		},
	},
	"body_female_beastkin": {
		"display": "Female beastkin body",
		"extra_options": {
			"breast_nipples": ["beastkin_nipples_large", "beastkin_tits_nipples"],
			"breasts_beastkin": ["beastkin_tits1"],
		},
		"folders": ["15_beastkin_body_nude"],
		"group": "body",
		"slots": {
			"arm_left": "beastkin_arml1",
			"arm_right": "beastkin_armr1",
			"beastkin_pregnancy_nipple": {
				"axis": "pregnancy",
				"options": {
					"big": "beastkin_pregnancy_nipple_big",
					"mid": "beastkin_pregnancy_nipple_mid",
				},
			},
			"beastkin_torso_many_nipples": {
				"axis": "many_tits",
				"options": {
					"4": "beastkin_torso_many_nipples4",
					"6": "beastkin_torso_many_nipples6",
				},
			},
			"belly": {
				"axis": "belly_shape",
				"options": {
					"default": "beastkin_belly1",
					"muscle": "15_beastkin_body_nude/beastkin_belly1_muscle",
				},
			},
			"breast_nipples": {
				"axis": "tits_size",
				"options": {
					"big": "beastkin_tits_nipples_big",
					"large": "beastkin_tits_nipples_large",
					"normal": "tits_nipples_normal",
					"small": "beastkin_tits_nipples_small__body_female_beastkin",
				},
			},
			"breasts_beastkin": {
				"axis": "tits_size",
				"options": {
					"big": "beastkin_tits_big",
					"large": "beastkin_tits_large",
					"normal": "beastkin_tits_normal",
					"small": "beastkin_tits_small",
				},
			},
			"breasts_beastkin_many": {
				"axis": "many_tits",
				"options": {
					"4": "beastkin_titsmany_small4",
					"6": "beastkin_titsmany_small6",
				},
			},
			"breasts_beastkin_pregnancy": {
				"axis": "pregnancy",
				"options": {
					"big": "beastkin_pregnancy_tits_big",
					"mid": "beastkin_pregnancy_tits_mid",
				},
			},
			"hand_left": {
				"axis": "hand_pose",
				"options": {
					"1": "beastkin_handl1",
					"2": "beastkin_handl2",
					"3": "beastkin_handl3",
				},
			},
			"hand_right": {
				"axis": "hand_pose",
				"options": {
					"1": "beastkin_handr1",
					"2": "beastkin_handr2",
					"3": "beastkin_handr3",
				},
			},
			"leg_left": "beastkin_legl1",
			"leg_right": "beastkin_legr1",
			"pelvis": "beastkin_pelvis1",
			"pregnancy_belly": {
				"axis": "pregnancy",
				"options": {
					"big": "beastkin_pregnancy_belly_big1",
					"mid": "beastkin_pregnancy_belly_mid1",
				},
			},
			"shoulder_left": "beastkin_shoulderl",
			"shoulder_right": "beastkin_shoulderr",
			"torso": "beastkin_torso",
			"torso_nipples_mask": "beastkin_torso_nipples_mask",
		},
		"tags": ["beastkin"],
		"zones": [0],
	},
	"braid": {
		"folders": ["05_hairs_assist"],
		"group": "hair_assist",
		"slots": {
			"hairs_assist": "braid",
		},
		"zones": [0],
	},
	"collar_bell": {
		"folders": ["150_armory_acces_collars"],
		"group": "collar",
		"slots": {
			"equip_collar": "collar_bell",
		},
		"zones": [0, 1],
	},
	"collar_heart": {
		"folders": ["150_armory_acces_collars"],
		"group": "collar",
		"slots": {
			"equip_collar": "collar_heart",
		},
		"zones": [0, 1],
	},
	"collar_leather": {
		"folders": ["150_armory_acces_collars"],
		"group": "collar",
		"slots": {
			"equip_collar": "collar_leather",
		},
		"zones": [0, 1],
	},
	"collar_metallic": {
		"folders": ["150_armory_acces_collars"],
		"group": "collar",
		"slots": {
			"equip_collar": "collar_metallic",
		},
		"zones": [0, 1],
	},
	"collar_playboy": {
		"folders": ["112_armory_set_playboy_female"],
		"group": "collar",
		"slots": {
			"equip_collar": "collar_playboy",
		},
		"zones": [0, 1],
	},
	"collar_steel": {
		"folders": ["150_armory_acces_collars"],
		"group": "collar",
		"slots": {
			"equip_collar": "collar_steel",
		},
		"zones": [0],
	},
	"ears_cat": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_cat",
		},
		"zones": [0],
	},
	"ears_elven": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_elven",
		},
	},
	"ears_elven2": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_elven2",
		},
	},
	"ears_fox_n1": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_fox_n1",
		},
		"zones": [0],
	},
	"ears_fox_n2": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_fox_n2",
		},
		"zones": [0],
	},
	"ears_fox_n3": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_fox_n3",
		},
		"zones": [0],
	},
	"ears_fox_n4": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_fox_n4",
		},
		"zones": [0],
	},
	"ears_goblin": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_goblin",
		},
	},
	"ears_human": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_human",
		},
	},
	"ears_mouse": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_mouse",
		},
		"zones": [0],
	},
	"ears_nereid": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_nereid",
		},
		"zones": [0],
	},
	"ears_orc": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_orc",
		},
	},
	"ears_rabbit": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_rabbit",
		},
		"zones": [0],
	},
	"ears_rabbit2": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_rabbit2",
		},
		"zones": [0],
	},
	"ears_rabbit3": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_rabbit3",
		},
		"zones": [0],
	},
	"ears_tanuk": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_tanuk",
		},
		"zones": [0],
	},
	"ears_taurus": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_taurus",
		},
		"zones": [0],
	},
	"ears_wolf": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_wolf",
		},
		"zones": [0],
	},
	"eyebrows1": {
		"folders": ["11_eyebrows"],
		"group": "eyebrows",
		"slots": {
			"eyebrows": "eyebrows1",
		},
	},
	"eyebrows2": {
		"folders": ["11_eyebrows"],
		"group": "eyebrows",
		"slots": {
			"eyebrows": "eyebrows2",
		},
	},
	"eyebrows3": {
		"folders": ["11_eyebrows"],
		"group": "eyebrows",
		"slots": {
			"eyebrows": "eyebrows3",
		},
	},
	"eyebrows4": {
		"folders": ["11_eyebrows"],
		"group": "eyebrows",
		"slots": {
			"eyebrows": "eyebrows4",
		},
	},
	"eyebrows5": {
		"folders": ["11_eyebrows"],
		"group": "eyebrows",
		"slots": {
			"eyebrows": "eyebrows5",
		},
	},
	"eyebrows_m1": {
		"folders": ["11_eyebrows"],
		"group": "eyebrows",
		"slots": {
			"eyebrows": "eyebrows_m1",
		},
	},
	"eyebrows_m2": {
		"folders": ["11_eyebrows"],
		"group": "eyebrows",
		"slots": {
			"eyebrows": "eyebrows_m2",
		},
	},
	"eyebrows_m3": {
		"folders": ["11_eyebrows"],
		"group": "eyebrows",
		"slots": {
			"eyebrows": "eyebrows_m3",
		},
	},
	"eyes1": {
		"folders": ["10_eyes"],
		"group": "eyes",
		"slots": {
			"eyes": "eyes1",
		},
	},
	"eyes2": {
		"folders": ["10_eyes"],
		"group": "eyes",
		"slots": {
			"eyes": "eyes2",
		},
	},
	"eyes3": {
		"folders": ["10_eyes"],
		"group": "eyes",
		"slots": {
			"eyes": "eyes3",
		},
	},
	"eyes5": {
		"folders": ["10_eyes"],
		"group": "eyes",
		"slots": {
			"eyes": "eyes5",
		},
	},
	"eyes_hearts": {
		"folders": ["10_eyes"],
		"group": "eyes_effect",
		"slots": {
			"eyes_hearts": "10_eyes/eyes_hearts",
		},
	},
	"eyes_m5": {
		"folders": ["10_eyes"],
		"group": "eyes",
		"slots": {
			"eyes": "eyes_m5",
		},
	},
	"face10": {
		"folders": ["02_faces"],
		"group": "face",
		"slots": {
			"face": "02_faces/face10",
		},
	},
	"face6": {
		"folders": ["02_faces"],
		"group": "face",
		"slots": {
			"face": "02_faces/face6",
		},
	},
	"face7": {
		"folders": ["02_faces"],
		"group": "face",
		"slots": {
			"face": "02_faces/face7",
		},
	},
	"face8": {
		"folders": ["02_faces"],
		"group": "face",
		"slots": {
			"face": "02_faces/face8",
		},
	},
	"face9": {
		"folders": ["02_faces"],
		"group": "face",
		"slots": {
			"face": "02_faces/face9",
		},
	},
	"face_m1": {
		"folders": ["02_faces"],
		"group": "face",
		"slots": {
			"face": "face_m1",
		},
	},
	"face_m2": {
		"folders": ["02_faces"],
		"group": "face",
		"slots": {
			"face": "face_m2",
		},
	},
	"face_m3": {
		"folders": ["02_faces"],
		"group": "face",
		"slots": {
			"face": "face_m3",
		},
	},
	"face_m4": {
		"folders": ["02_faces"],
		"group": "face",
		"slots": {
			"face": "face_m4",
		},
	},
	"face_m5": {
		"folders": ["02_faces"],
		"group": "face",
		"slots": {
			"face": "face_m5",
		},
	},
	"facemask1": {
		"folders": ["25_head_masks"],
		"group": "mask",
		"slots": {
			"equip_masks": "facemask1",
		},
	},
	"facemask2": {
		"folders": ["25_head_masks"],
		"group": "mask",
		"slots": {
			"equip_masks": "facemask2",
		},
	},
	"hair_armor_maid": {
		"folders": ["99_armory_set_maidu"],
		"group": "headgear",
		"slots": {
			"equip_head": "hair_armor_maid",
		},
	},
	"hair_armor_playboy": {
		"folders": ["112_armory_set_playboy_female"],
		"group": "headgear",
		"slots": {
			"equip_head": "hair_armor_playboy",
		},
		"zones": [0],
	},
	"hair_armor_waitress": {
		"folders": ["109_armory_set_waitress_female"],
		"group": "headgear",
		"slots": {
			"equip_head": "hair_armor_waitress",
		},
		"zones": [0, 1],
	},
	"hair_assist_twin_tails": {
		"folders": ["05_hairs_assist"],
		"group": "hair_assist",
		"slots": {
			"hairs_assist": "hair_assist_twin_tails",
		},
		"zones": [0],
	},
	"hair_assist_twin_tails_2": {
		"folders": ["05_hairs_assist"],
		"group": "hair_assist",
		"slots": {
			"hairs_assist": "hair_assist_twin_tails 2",
		},
		"zones": [0],
	},
	"hair_back_care": {
		"folders": ["06_hairs_back"],
		"group": "hair_back",
		"slots": {
			"hairs_back": "hair_back_care",
		},
		"zones": [0],
	},
	"hair_back_double_tail_long": {
		"folders": ["06_hairs_back"],
		"group": "hair_back",
		"slots": {
			"hairs_back": "hair_back_double_tail_long",
		},
		"zones": [0],
	},
	"hair_back_ponytail_long": {
		"folders": ["06_hairs_back"],
		"group": "hair_back",
		"slots": {
			"hairs_back": "hair_back_ponytail_long",
		},
		"zones": [0],
	},
	"hair_back_straight": {
		"folders": ["06_hairs_back"],
		"group": "hair_back",
		"slots": {
			"hairs_back": "hair_back_straight",
		},
		"zones": [0],
	},
	"hair_back_verylong1": {
		"folders": ["06_hairs_back"],
		"group": "hair_back",
		"slots": {
			"hairs_back": "hair_back_verylong1",
		},
		"zones": [0],
	},
	"hair_back_wawe": {
		"folders": ["06_hairs_back"],
		"group": "hair_back",
		"slots": {
			"hairs_back": "hair_back_wawe",
		},
		"zones": [0],
	},
	"hair_base_back": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hair_base_back",
		},
		"zones": [0],
	},
	"hair_base_braids": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hair_base_braids",
		},
		"zones": [0],
	},
	"hair_base_default": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hair_base_default",
			"hairs_fringe": "hair_fringe_default",
		},
		"zones": [0],
	},
	"hair_base_disheveled": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "04_hairs_base/hair_base_disheveled",
			"hairs_fringe": "04_hairs_fringe/hair_fringe_disheveled",
		},
		"zones": [0],
	},
	"hair_base_fringe": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hair_base_fringe",
			"hairs_fringe": "hair_fringe_fringe",
		},
		"zones": [0],
	},
	"hair_base_fringe_2": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hair_base_fringe 2",
		},
		"zones": [0],
	},
	"hair_base_kare": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hair_base_kare",
			"hairs_fringe": "hair_fringe_kare",
		},
		"zones": [0],
	},
	"hair_base_parting": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hair_base_parting",
		},
		"zones": [0],
	},
	"hair_base_slave": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hair_base_slave",
		},
	},
	"hair_base_straight": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hair_base_straight",
			"hairs_fringe": "hair_fringe_straight",
		},
		"zones": [0],
	},
	"hair_base_undercut": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hair_base_undercut",
		},
		"zones": [0],
	},
	"hair_spiral": {
		"folders": ["05_hairs_assist"],
		"group": "hair_assist",
		"slots": {
			"hairs_assist": "05_hairs_assist/hair_spiral",
		},
		"zones": [0],
	},
	"hairs_base_dopple": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "04_hairs_base/hairs_base_dopple",
			"hairs_fringe": "hairs_fringe_dopple",
		},
		"zones": [0],
	},
	"head_chin_curve": {
		"display": "Chin: curved",
		"folders": ["01_heads"],
		"group": "head",
		"slots": {
			"head": "head_chin_curve",
			"head_skull": "head_skull",
		},
	},
	"head_chin_curve_kobold": {
		"display": "Chin: curved kobold",
		"folders": ["01_heads"],
		"group": "head",
		"slots": {
			"head": "head_chin_curve_kobold",
			"head_skull": "head_skull",
		},
	},
	"head_chin_default": {
		"display": "Chin: default",
		"folders": ["01_heads"],
		"group": "head",
		"slots": {
			"head": "head_chin_default",
			"head_skull": "head_skull",
		},
	},
	"head_chin_kobold2": {
		"display": "Chin: kobold 2",
		"folders": ["01_heads"],
		"group": "head",
		"slots": {
			"head": "head_chin_kobold2",
			"head_skull": "head_skull",
		},
	},
	"head_chin_long_skinny": {
		"display": "Chin: long skinny",
		"folders": ["01_heads"],
		"group": "head",
		"slots": {
			"head": "head_chin_long_skinny",
			"head_skull": "head_skull",
		},
	},
	"head_chin_muscle": {
		"display": "Chin: muscular",
		"folders": ["01_heads"],
		"group": "head",
		"slots": {
			"head": "head_chin_muscle",
			"head_skull": "head_skull",
		},
	},
	"head_chin_short": {
		"display": "Chin: short",
		"folders": ["01_heads"],
		"group": "head",
		"slots": {
			"head": "head_chin_short",
			"head_skull": "head_skull",
		},
	},
	"head_chin_small_c": {
		"display": "Chin: small curved",
		"folders": ["01_heads"],
		"group": "head",
		"slots": {
			"head": "head_chin_small_c",
			"head_skull": "head_skull",
		},
	},
	"head_dragon_mask": {
		"display": "Dragon cheek scales",
		"folders": ["23_dragon_female"],
		"group": "face_markings",
		"slots": {
			"race_head": "head_dragon_mask",
		},
	},
	"head_dragon_mask_2": {
		"display": "Dragon cheek scales 2",
		"folders": ["23_dragon_female"],
		"group": "face_markings",
		"slots": {
			"race_head": "head_dragon_mask 2",
		},
	},
	"horn_curve_down": {
		"folders": ["08_horns"],
		"group": "horns",
		"slots": {
			"horns": "horn_curve_down",
		},
	},
	"horn_curve_top": {
		"folders": ["08_horns"],
		"group": "horns",
		"slots": {
			"horns": "horn_curve_top",
		},
	},
	"horn_curve_up": {
		"folders": ["08_horns"],
		"group": "horns",
		"slots": {
			"horns": "horn_curve_up",
		},
	},
	"horn_dragon2": {
		"folders": ["08_horns"],
		"group": "horns",
		"slots": {
			"horns": "horn_dragon2",
		},
	},
	"horn_seraph_fibule": {
		"folders": ["08_horns"],
		"group": "horns",
		"slots": {
			"horns": "horn_seraph_fibule",
		},
		"zones": [0],
	},
	"horn_spiral_2": {
		"folders": ["08_horns"],
		"group": "horns",
		"slots": {
			"horns": "horn_spiral 2",
		},
	},
	"kentaur_body": {
		"folders": ["14_animals_body"],
		"group": "animal_body",
		"hides": [
			"leg_left",
			"leg_right",
			"equip_leg_left",
			"equip_leg_right",
			"race_leg_left",
			"race_leg_right",
			"dick",
			"testicle",
		],
		"slots": {
			"animal_body": "kentaur_body",
		},
	},
	"kobold_head_kobold": {
		"display": "Kobold spots",
		"folders": ["24_kobold_female"],
		"group": "face_markings",
		"slots": {
			"race_head": "kobold_head_kobold",
		},
	},
	"kobold_head_mask1": {
		"display": "Kobold cheek plates",
		"folders": ["24_kobold_female"],
		"group": "face_markings",
		"slots": {
			"race_head": "kobold_head_mask1",
		},
	},
	"lamia_body": {
		"folders": ["14_animals_body"],
		"group": "animal_body",
		"hides": [
			"leg_left",
			"leg_right",
			"equip_leg_left",
			"equip_leg_right",
			"race_leg_left",
			"race_leg_right",
			"dick",
			"testicle",
		],
		"slots": {
			"animal_body": "lamia_body",
		},
	},
	"lips1": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips1",
		},
	},
	"lips2": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips2",
		},
	},
	"lips3": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips3",
		},
	},
	"lips4": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips4",
		},
	},
	"lips5": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips5",
		},
		"zones": [0],
	},
	"lips_beast": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips_beast__body_female_beastkin",
		},
	},
	"lips_m1": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips_m1",
		},
	},
	"lips_m2": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips_m2",
		},
	},
	"lips_m3": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips_m3",
		},
	},
	"lips_m4": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips_m4",
		},
	},
	"lips_orc": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips_orc",
		},
	},
	"lips_orc_1": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips_orc 1",
		},
	},
	"lips_orc_2": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips_orc 2",
		},
	},
	"lips_orc_3": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips_orc 3",
		},
	},
	"lips_s1": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "12_lips/lips_s1",
		},
	},
	"lips_s2": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "12_lips/lips_s2",
		},
	},
	"nose_default": {
		"folders": ["03_noses"],
		"group": "nose",
		"slots": {
			"noses": "nose_default",
		},
	},
	"nose_dwarf": {
		"folders": ["03_noses"],
		"group": "nose",
		"slots": {
			"noses": "nose_dwarf",
		},
	},
	"nose_feature": {
		"folders": ["03_noses"],
		"group": "nose",
		"slots": {
			"noses": "03_noses/nose_feature",
		},
	},
	"nose_kobold": {
		"folders": ["03_noses"],
		"group": "nose",
		"slots": {
			"noses": "nose_kobold",
		},
	},
	"nose_kobold_2": {
		"folders": ["03_noses"],
		"group": "nose",
		"slots": {
			"noses": "nose_kobold_2",
		},
	},
	"nose_point": {
		"folders": ["03_noses"],
		"group": "nose",
		"slots": {
			"noses": "03_noses/nose_point",
		},
	},
	"nose_small": {
		"folders": ["03_noses"],
		"group": "nose",
		"slots": {
			"noses": "nose_small",
		},
	},
	"nose_straight": {
		"folders": ["03_noses"],
		"group": "nose",
		"slots": {
			"noses": "nose_straight",
		},
	},
	"outfit_cloth": {
		"display": "Cloth set",
		"folders": ["101_armory_set_cloth_female"],
		"group": "outfit",
		"slots": {
			"equip_back": "raincoat_cloth2",
			"equip_belly": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_cloth2_big",
					"mid": "pregnancy_cloth2_small",
				},
			},
			"equip_breasts": {
				"axis": "tits_size",
				"options": {
					"big": "tits_cloth2_big",
					"flat": "tits_cloth2_flat",
					"large": "tits_cloth2_large",
					"normal": "tits_cloth2_normal",
					"small": "tits_cloth2_small",
				},
			},
			"equip_pelvis": "pelvis_armor_cloth2",
			"equip_pregnancy_low": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_cloth2_big",
					"mid": "pregnancy_cloth2_small",
				},
			},
			"equip_pregnancy_up": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_cloth2_big",
					"mid": "pregnancy_cloth2_small",
				},
			},
			"equip_shoulder_left": "shoulder_armorl_cloth2",
			"equip_shoulder_right": "shoulder_armorr_cloth2",
			"equip_torso": "torso_armor_cloth2",
		},
		"zones": [0, 1],
	},
	"outfit_cloth3": {
		"display": "Cloth set 3",
		"folders": ["101_armory_set_cloth3_female"],
		"group": "outfit",
		"slots": {
			"equip_arm_left": "arm_armorl_cloth",
			"equip_arm_right": "arm_armorr_cloth",
			"equip_back": "raincoat_cloth",
			"equip_belly": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_cloth_big",
					"mid": "pregnancy_cloth_small",
				},
			},
			"equip_breasts": {
				"axis": "tits_size",
				"options": {
					"big": "tits_cloth_big",
					"large": "tits_cloth_large",
					"normal": "tits_cloth_normal",
					"small": "tits_cloth3_small",
				},
			},
			"equip_leg_left": "legl_armor_cloth",
			"equip_leg_right": "legr_armor_cloth",
			"equip_pelvis": "pelvis_armor_cloth",
			"equip_pregnancy_low": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_cloth3_big",
					"mid": "pregnancy_cloth3_small",
				},
			},
			"equip_pregnancy_up": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_cloth3_big",
					"mid": "pregnancy_cloth3_small",
				},
			},
			"equip_shoulder_left": "shoulder_armorl_cloth",
			"equip_shoulder_right": "shoulder_armorr_cloth",
			"equip_torso": "torso_armor_cloth",
		},
		"zones": [0, 1, 2],
	},
	"outfit_cloth3_legs": {
		"display": "Cloth set 3 (legs)",
		"folders": ["101_armory_set_cloth3_female"],
		"group": "outfit_legs",
		"slots": {
			"equip_leg_left": "legl_armor_cloth",
			"equip_leg_right": "legr_armor_cloth",
			"equip_pelvis": "pelvis_armor_cloth",
		},
		"zones": [0, 1, 2],
	},
	"outfit_cloth_legs": {
		"display": "Cloth set (legs)",
		"folders": ["101_armory_set_cloth_female"],
		"group": "outfit_legs",
		"slots": {
			"equip_pelvis": "pelvis_armor_cloth2",
		},
		"zones": [0, 1],
	},
	"outfit_gipure1": {
		"display": "Gipure set 1",
		"folders": ["105_armory_set_gipure1_female"],
		"group": "outfit",
		"slots": {
			"equip_belly": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_gipure1_big",
					"mid": "pregnancy_gipure1_small",
				},
			},
			"equip_breasts": {
				"axis": "tits_size",
				"options": {
					"big": "tits_gipure1_big",
					"flat": "tits_gipure1_0",
					"large": "tits_gipure1_large",
					"normal": "tits_gipure1_normal",
					"small": "tits_gipure1_small",
				},
			},
			"equip_leg_left": "legl_armor_gipure1",
			"equip_leg_right": "legr_armor_gipure1",
			"equip_pelvis": "pelvis_armor_gipure1",
			"equip_pregnancy_low": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_gipure1_big",
					"mid": "pregnancy_gipure1_small",
				},
			},
			"equip_pregnancy_up": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_gipure1_big",
					"mid": "pregnancy_gipure1_small",
				},
			},
			"equip_torso": "torso_armor_gipure1",
		},
		"zones": [0],
	},
	"outfit_gipure1_legs": {
		"display": "Gipure set 1 (legs)",
		"folders": ["105_armory_set_gipure1_female"],
		"group": "outfit_legs",
		"slots": {
			"equip_leg_left": "legl_armor_gipure1",
			"equip_leg_right": "legr_armor_gipure1",
			"equip_pelvis": "pelvis_armor_gipure1",
		},
		"zones": [0],
	},
	"outfit_gipure2": {
		"display": "Gipure set 2",
		"folders": ["106_armory_set_gipure2_female"],
		"group": "outfit",
		"slots": {
			"equip_belly": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_gipure2_big",
					"mid": "pregnancy_gipure2_small",
				},
			},
			"equip_breasts": {
				"axis": "tits_size",
				"options": {
					"big": "tits_gipure2_big",
					"flat": "tits_gipure2_o",
					"large": "tits_gipure2_large",
					"normal": "tits_gipure2_normal",
					"small": "tits_gipure2_small",
				},
			},
			"equip_pelvis": "pelvis_armor_gipure2",
			"equip_pregnancy_low": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_gipure2_big",
					"mid": "pregnancy_gipure2_small",
				},
			},
			"equip_pregnancy_up": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_gipure2_big",
					"mid": "pregnancy_gipure2_small",
				},
			},
			"equip_torso": "tirso_armor_gipure2",
		},
		"zones": [0],
	},
	"outfit_gipure2_legs": {
		"display": "Gipure set 2 (legs)",
		"folders": ["106_armory_set_gipure2_female"],
		"group": "outfit_legs",
		"slots": {
			"equip_pelvis": "pelvis_armor_gipure2",
		},
		"zones": [0],
	},
	"outfit_jacket": {
		"display": "Jacket set",
		"folders": ["107_armory_set_jacket_female"],
		"group": "outfit",
		"slots": {
			"equip_belly": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_jacket_big",
					"mid": "pregnancy_jacket_mid",
				},
			},
			"equip_breasts": {
				"axis": "tits_size",
				"options": {
					"big": "tits_jacket_big",
					"large": "tits_jacket_large",
					"normal": "tits_jacket_normal",
					"small": "tits_jacket_small",
				},
			},
			"equip_leg_left": "legl_armor_jacket",
			"equip_leg_right": "legr_armor_jacket",
			"equip_pelvis": "pelvis_armor_jacket",
			"equip_pregnancy_low": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_jacket_big",
					"mid": "pregnancy_jacket_small",
				},
			},
			"equip_pregnancy_up": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_jacket_big",
					"mid": "pregnancy_jacket_small",
				},
			},
			"equip_torso": "torso_armor_jacket",
		},
		"zones": [0, 1],
	},
	"outfit_jacket_legs": {
		"display": "Jacket set (legs)",
		"folders": ["107_armory_set_jacket_female"],
		"group": "outfit_legs",
		"slots": {
			"equip_leg_left": "legl_armor_jacket",
			"equip_leg_right": "legr_armor_jacket",
			"equip_pelvis": "pelvis_armor_jacket",
		},
		"zones": [0, 1],
	},
	"outfit_latex": {
		"display": "Latex set",
		"folders": ["108_armory_set_latex_female"],
		"group": "outfit",
		"slots": {
			"equip_arm_left": "arm_armorl_latex",
			"equip_arm_right": "arm_armorr_latex",
			"equip_belly": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_latex_big",
					"mid": "pregnancy_latex_mid",
					"none": "belly_armor_latex",
				},
			},
			"equip_breasts": {
				"axis": "tits_size",
				"options": {
					"big": "tits_latex_big",
					"large": "tits_large_latex",
					"normal": "tits_normal_latex",
					"small": "tits_small_latex",
				},
			},
			"equip_hand_left": {
				"axis": "hand_pose",
				"options": {
					"1": "handl1_armor_latex",
					"2": "handl2_latex2",
					"3": "handl_armor_latex3",
				},
			},
			"equip_hand_right": {
				"axis": "hand_pose",
				"options": {
					"1": "handr1_latex",
					"2": "handr2_latex2",
					"3": "handr_armor_latex3",
				},
			},
			"equip_leg_left": "legl_armor_latex",
			"equip_leg_right": "legr_armor_latex",
			"equip_pelvis": "pelvis_armor_latex",
			"equip_pregnancy_low": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_latex_big",
					"mid": "pregnancy_latex_small",
				},
			},
			"equip_pregnancy_up": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_latex_big",
					"mid": "pregnancy_latex_small",
				},
			},
			"equip_shoulder_left": "shoulder_armorl_latex",
			"equip_shoulder_right": "shoulder_armorr_latex",
			"equip_torso": "torso_armor_latex",
		},
	},
	"outfit_latex_hands": {
		"display": "Latex set (hands)",
		"folders": ["108_armory_set_latex_female"],
		"group": "outfit_hands",
		"slots": {
			"equip_hand_left": {
				"axis": "hand_pose",
				"options": {
					"1": "handl1_armor_latex",
					"2": "handl2_latex2",
					"3": "handl_armor_latex3",
				},
			},
			"equip_hand_right": {
				"axis": "hand_pose",
				"options": {
					"1": "handr1_latex",
					"2": "handr2_latex2",
					"3": "handr_armor_latex3",
				},
			},
		},
	},
	"outfit_latex_legs": {
		"display": "Latex set (legs)",
		"folders": ["108_armory_set_latex_female"],
		"group": "outfit_legs",
		"slots": {
			"equip_leg_left": "legl_armor_latex",
			"equip_leg_right": "legr_armor_latex",
			"equip_pelvis": "pelvis_armor_latex",
		},
	},
	"outfit_leather": {
		"display": "Leather set",
		"folders": ["102_armory_set_leather_female"],
		"group": "outfit",
		"slots": {
			"equip_arm_left": "arm_armorl_leather",
			"equip_arm_right": "arm_armorr_leather",
			"equip_back": "equip_back",
			"equip_belly": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_skin_leather",
					"mid": "pregnancy_skin_small",
				},
			},
			"equip_breasts": {
				"axis": "tits_size",
				"options": {
					"big": "tits_leather_big",
					"flat": "tits_leather_0",
					"large": "tits_leather_large",
					"normal": "tits_leather_normal",
					"small": "tits_leather_small",
				},
			},
			"equip_leg_left": "legl_armor_leather",
			"equip_leg_right": "legr_armor_leather",
			"equip_pelvis": "pelvis_armor_leather",
			"equip_pregnancy_low": {
				"axis": "pregnancy",
				"options": {
					"mid": "pregnancy_leather_small",
					"none": "pregnancy_leather_big",
				},
			},
			"equip_pregnancy_up": {
				"axis": "pregnancy",
				"options": {
					"mid": "pregnancy_leather_small",
					"none": "pregnancy_leather_big",
				},
			},
			"equip_torso": "torso_armor_leather",
		},
		"zones": [0, 1],
	},
	"outfit_leather2": {
		"display": "Leather set 2",
		"folders": ["102_armory_set_leather2_female"],
		"group": "outfit",
		"slots": {
			"equip_arm_left": "arm_armorl_leather2",
			"equip_arm_right": "arm_armorr_leather2",
			"equip_back": "raincoat_leather2",
			"equip_belly": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_leather2_big",
					"mid": "pregnancy_leather2_small",
				},
			},
			"equip_breasts": {
				"axis": "tits_size",
				"options": {
					"big": "tits_leather2_big",
					"flat": "tits_leather_2",
					"large": "tits_leather2_large",
					"normal": "tits_leather2_normal",
					"small": "tits_leather_2 small",
				},
			},
			"equip_leg_left": "legl_armor_leather2",
			"equip_leg_right": "legr_armor_leather2",
			"equip_pelvis": "pelvis_armor_leather2",
			"equip_pregnancy_low": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_leather2_big",
					"mid": "pregnancy_leather2_small",
				},
			},
			"equip_pregnancy_up": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_leather2_big",
					"mid": "pregnancy_leather2_small",
				},
			},
			"equip_shoulder_left": "shoulder_armorl_leather2",
			"equip_shoulder_right": "shoulder_armorr_leather2",
			"equip_torso": "torso_armor_leather2",
		},
		"zones": [0, 1, 2],
	},
	"outfit_leather2_legs": {
		"display": "Leather set 2 (legs)",
		"folders": ["102_armory_set_leather2_female"],
		"group": "outfit_legs",
		"slots": {
			"equip_leg_left": "legl_armor_leather2",
			"equip_leg_right": "legr_armor_leather2",
			"equip_pelvis": "pelvis_armor_leather2",
		},
		"zones": [0, 1, 2],
	},
	"outfit_leather_legs": {
		"display": "Leather set (legs)",
		"folders": ["102_armory_set_leather_female"],
		"group": "outfit_legs",
		"slots": {
			"equip_leg_left": "legl_armor_leather",
			"equip_leg_right": "legr_armor_leather",
			"equip_pelvis": "pelvis_armor_leather",
		},
		"zones": [0, 1],
	},
	"outfit_maid": {
		"display": "Maid set",
		"folders": ["99_armory_set_maidu"],
		"group": "outfit",
		"slots": {
			"equip_arm_left": "arm_armorl1",
			"equip_arm_right": "arm_armorr1",
			"equip_belly": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_maidu_big",
					"mid": "pregnancy_maidu_small",
					"none": "belly_maidu",
				},
			},
			"equip_breasts": {
				"axis": "tits_size",
				"options": {
					"big": "tits_armor1_big",
					"large": "tits_armor1_large",
					"normal": "tits_armor1_normal",
					"small": "tits_armor1_small",
				},
			},
			"equip_hand_left": {
				"axis": "hand_pose",
				"options": {
					"1": "hand1_armorl1",
					"2": "hand2_armorl2",
					"3": "hand_armorl3",
				},
			},
			"equip_hand_right": {
				"axis": "hand_pose",
				"options": {
					"1": "hand1_armorr1",
					"2": "hand2_armorr2",
					"3": "hand_armorr3",
				},
			},
			"equip_leg_left": "legl_armor1",
			"equip_leg_right": "legr_armor1",
			"equip_pelvis": "pelvis_armor_maidu",
			"equip_pregnancy_low": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_maidu_big",
					"mid": "pregnancy_maidu_small",
				},
			},
			"equip_pregnancy_up": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_maidu_big",
					"mid": "pregnancy_maidu_small",
				},
			},
			"equip_shoulder_left": "shoulder_armorl1",
			"equip_shoulder_right": "shoulder_armorr1",
			"equip_torso": "torso_armor_maidu",
		},
		"unpainted": true,
	},
	"outfit_maid_hands": {
		"display": "Maid set (hands)",
		"folders": ["99_armory_set_maidu"],
		"group": "outfit_hands",
		"slots": {
			"equip_hand_left": {
				"axis": "hand_pose",
				"options": {
					"1": "hand1_armorl1",
					"2": "hand2_armorl2",
					"3": "hand_armorl3",
				},
			},
			"equip_hand_right": {
				"axis": "hand_pose",
				"options": {
					"1": "hand1_armorr1",
					"2": "hand2_armorr2",
					"3": "hand_armorr3",
				},
			},
		},
	},
	"outfit_maid_legs": {
		"display": "Maid set (legs)",
		"folders": ["99_armory_set_maidu"],
		"group": "outfit_legs",
		"slots": {
			"equip_leg_left": "legl_armor1",
			"equip_leg_right": "legr_armor1",
			"equip_pelvis": "pelvis_armor_maidu",
		},
	},
	"outfit_petsuit": {
		"display": "Pet suit accessories",
		"folders": ["151_armory_acces_petsuit"],
		"group": "outfit",
		"slots": {
			"equip_hand_left": "hand2_petsuitl3",
			"equip_hand_right": "hand2_petsuitr3",
			"equip_leg_left": "151_armory_acces_petsuit/Petsuit_legl",
			"equip_leg_right": "151_armory_acces_petsuit/Petsuit_legr",
		},
		"zones": [0],
	},
	"outfit_petsuit_hands": {
		"display": "Pet suit accessories (hands)",
		"folders": ["151_armory_acces_petsuit"],
		"group": "outfit_hands",
		"slots": {
			"equip_hand_left": "hand2_petsuitl3",
			"equip_hand_right": "hand2_petsuitr3",
		},
		"zones": [0],
	},
	"outfit_petsuit_legs": {
		"display": "Pet suit accessories (legs)",
		"folders": ["151_armory_acces_petsuit"],
		"group": "outfit_legs",
		"slots": {
			"equip_leg_left": "151_armory_acces_petsuit/Petsuit_legl",
			"equip_leg_right": "151_armory_acces_petsuit/Petsuit_legr",
		},
		"zones": [0],
	},
	"outfit_plate": {
		"display": "Plate set",
		"folders": ["103_armory_set_plate_female"],
		"group": "outfit",
		"slots": {
			"equip_arm_left": "arm_armorl_plate",
			"equip_arm_right": "arm_armorr_plate",
			"equip_back": "raincoat_cloth2__103_armory_set_plate_female",
			"equip_belly": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_plate_big",
					"mid": "pregnancy_plate_small",
				},
			},
			"equip_breasts": {
				"axis": "tits_size",
				"options": {
					"big": "tits_plate_big",
					"flat": "tits_plate_0",
					"large": "tits_plate_large",
					"normal": "tits_plate_normal",
					"small": "tits_plate_small",
				},
			},
			"equip_leg_left": "legl_armor_plate",
			"equip_leg_right": "legr_armor_plate",
			"equip_pelvis": "pelvis_armor_plate",
			"equip_pregnancy_low": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_plate_big",
					"mid": "pregnancy_plate_small",
				},
			},
			"equip_pregnancy_up": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_plate_big",
					"mid": "pregnancy_plate_small",
				},
			},
			"equip_torso": "torso_armor_plate",
		},
		"zones": [0, 1, 2],
	},
	"outfit_plate2": {
		"display": "Plate set 2",
		"folders": ["103_armory_set_plate2_female"],
		"group": "outfit",
		"slots": {
			"equip_arm_left": "arm_armorl_plate2",
			"equip_arm_right": "arm_armorr_plate2",
			"equip_back": "raincoat_plate2",
			"equip_belly": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_plate2_big",
					"mid": "pregnancy_plate2_small",
				},
			},
			"equip_breasts": {
				"axis": "tits_size",
				"options": {
					"big": "tits_plate2_big",
					"flat": "tits_plate_2",
					"large": "tits_plate2_large",
					"normal": "tits_plate2_normal",
					"small": "tits_plate2_small",
				},
			},
			"equip_leg_left": "legl_armor_plate2",
			"equip_leg_right": "legr_armor_plate2",
			"equip_pelvis": "pelvis_armor_plate2",
			"equip_pregnancy_low": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_plate2_big",
					"mid": "pregnancy_plate2_small",
				},
			},
			"equip_pregnancy_up": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_plate2_big",
					"mid": "pregnancy_plate2_small",
				},
			},
			"equip_shoulder_left": "shoulder_armorl_plate2",
			"equip_shoulder_right": "shoulder_armorr_plate2",
			"equip_torso": "torso_armor_plate2",
		},
		"zones": [0, 1, 2],
	},
	"outfit_plate2_legs": {
		"display": "Plate set 2 (legs)",
		"folders": ["103_armory_set_plate2_female"],
		"group": "outfit_legs",
		"slots": {
			"equip_leg_left": "legl_armor_plate2",
			"equip_leg_right": "legr_armor_plate2",
			"equip_pelvis": "pelvis_armor_plate2",
		},
		"zones": [0, 1, 2],
	},
	"outfit_plate_legs": {
		"display": "Plate set (legs)",
		"folders": ["103_armory_set_plate_female"],
		"group": "outfit_legs",
		"slots": {
			"equip_leg_left": "legl_armor_plate",
			"equip_leg_right": "legr_armor_plate",
			"equip_pelvis": "pelvis_armor_plate",
		},
		"zones": [0, 1, 2],
	},
	"outfit_playboy": {
		"display": "Playboy set",
		"extra_options": {
			"equip_pelvis": ["112_armory_set_playboy_female/pelvis_armor_playboy"],
		},
		"folders": ["112_armory_set_playboy_female"],
		"group": "outfit",
		"slots": {
			"equip_arm_left": "arml1_armorl_playboy",
			"equip_arm_right": "armr1_armorr_playboy",
			"equip_belly": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_playboy_big",
					"mid": "pregnancy_playboy_mid",
				},
			},
			"equip_breasts": {
				"axis": "tits_size",
				"options": {
					"big": "tits_playboy_big",
					"large": "tits_playboy_large",
					"normal": "tits_playboy_normal",
					"small": "tits_playboy_small",
				},
			},
			"equip_hand_left": {
				"axis": "hand_pose",
				"options": {
					"1": "handl1_playboy",
					"2": "handl2_playboy",
					"3": "handl3_playboy",
				},
			},
			"equip_hand_right": {
				"axis": "hand_pose",
				"options": {
					"1": "handr1_playboy",
					"2": "handr2_playboy",
					"3": "handr3_playboy",
				},
			},
			"equip_leg_left": "legl_armor_playboy",
			"equip_leg_right": "legr_armor_playboy",
			"equip_pelvis": "pelvis_armor_playboy",
			"equip_pregnancy_low": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_playboy_big",
					"mid": "pregnancy_playboy_small",
				},
			},
			"equip_pregnancy_up": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_playboy_big",
					"mid": "pregnancy_playboy_small",
				},
			},
			"equip_shoulder_left": "shoulder_armorl_playboy",
			"equip_shoulder_right": "shoulder_armorr_playboy",
			"equip_torso": "torso_armor_playboy",
		},
		"zones": [0, 1],
	},
	"outfit_playboy_hands": {
		"display": "Playboy set (hands)",
		"folders": ["112_armory_set_playboy_female"],
		"group": "outfit_hands",
		"slots": {
			"equip_hand_left": {
				"axis": "hand_pose",
				"options": {
					"1": "handl1_playboy",
					"2": "handl2_playboy",
					"3": "handl3_playboy",
				},
			},
			"equip_hand_right": {
				"axis": "hand_pose",
				"options": {
					"1": "handr1_playboy",
					"2": "handr2_playboy",
					"3": "handr3_playboy",
				},
			},
		},
		"zones": [0],
	},
	"outfit_playboy_legs": {
		"display": "Playboy set (legs)",
		"folders": ["112_armory_set_playboy_female"],
		"group": "outfit_legs",
		"slots": {
			"equip_leg_left": "legl_armor_playboy",
			"equip_leg_right": "legr_armor_playboy",
			"equip_pelvis": "pelvis_armor_playboy",
		},
		"zones": [0, 1],
	},
	"outfit_slave": {
		"display": "Slave set",
		"folders": ["104_armory_set_slave_female"],
		"group": "outfit",
		"slots": {
			"equip_belly": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_slave_big",
					"mid": "pregnancy_slave_mid",
				},
			},
			"equip_breasts": {
				"axis": "tits_size",
				"options": {
					"big": "tits_slave_big",
					"flat": "tits_slave_0",
					"large": "tits_slave_large",
					"normal": "tits_slave_normal",
					"small": "tits_slave_small",
				},
			},
			"equip_pelvis": "pelvis_armor_slave",
			"equip_pregnancy_low": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_slave_big",
					"mid": "pregnancy_slave_small",
				},
			},
			"equip_pregnancy_up": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_slave_big",
					"mid": "pregnancy_slave_small",
				},
			},
		},
		"zones": [0],
	},
	"outfit_slave_legs": {
		"display": "Slave set (legs)",
		"folders": ["104_armory_set_slave_female"],
		"group": "outfit_legs",
		"slots": {
			"equip_pelvis": "pelvis_armor_slave",
		},
		"zones": [0],
	},
	"outfit_smith": {
		"display": "Smith set",
		"folders": ["110_armory_set_smith_female"],
		"group": "outfit",
		"slots": {
			"equip_arm_left": "arm_armorl_smith",
			"equip_arm_right": "arm_armorr_smith",
			"equip_belly": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_smith_big",
					"mid": "pregnancy_smith_mid",
				},
			},
			"equip_breasts": {
				"axis": "tits_size",
				"options": {
					"big": "tits_smith_big",
					"large": "tits_smith_large",
					"normal": "tits_smith_normal",
					"small": "tits_smith_small",
				},
			},
			"equip_leg_left": "legl_armor_smith",
			"equip_leg_right": "legr_armor_smith",
			"equip_pelvis": "pelvis_armor_smith",
			"equip_pregnancy_low": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_smith_big",
					"mid": "pregnancy_smith_small",
				},
			},
			"equip_pregnancy_up": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_smith_big",
					"mid": "pregnancy_smith_small",
				},
			},
			"equip_torso": "torso_armor_smith",
		},
		"zones": [0, 1],
	},
	"outfit_smith_legs": {
		"display": "Smith set (legs)",
		"folders": ["110_armory_set_smith_female"],
		"group": "outfit_legs",
		"slots": {
			"equip_leg_left": "legl_armor_smith",
			"equip_leg_right": "legr_armor_smith",
			"equip_pelvis": "pelvis_armor_smith",
		},
		"zones": [0, 1],
	},
	"outfit_tentacle": {
		"display": "Tentacle set",
		"folders": ["111_armory_set_tentackle_female"],
		"group": "outfit",
		"slots": {
			"equip_belly": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_tentackle_big",
					"mid": "pregnancy_belly_mid",
					"none": "belly_armor_tentackle",
				},
			},
			"equip_breasts": {
				"axis": "tits_size",
				"options": {
					"big": "tits_tentacle_big",
					"large": "tits_tentackle_large",
					"normal": "tits_tentackle_normal",
					"small": "tits_small_tentackle",
				},
			},
			"equip_pelvis": "pelvis_armor_tentackle",
			"equip_pregnancy_low": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_tentackle_big",
					"mid": "pregnancy_tentackle_small",
				},
			},
			"equip_pregnancy_up": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_tentackle_big",
					"mid": "pregnancy_tentackle_small",
				},
			},
			"equip_torso": "torso_armor_tentackle",
		},
		"zones": [0, 1],
	},
	"outfit_tentacle_legs": {
		"display": "Tentacle set (legs)",
		"folders": ["111_armory_set_tentackle_female"],
		"group": "outfit_legs",
		"slots": {
			"equip_pelvis": "pelvis_armor_tentackle",
		},
		"zones": [0, 1],
	},
	"outfit_underwear1": {
		"display": "Underwear set 1",
		"folders": ["113_armory_set_underwear1"],
		"group": "outfit",
		"slots": {
			"equip_belly": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_underwear1_big",
					"mid": "pregnancy_underwear1_small",
				},
			},
			"equip_breasts": {
				"axis": "tits_size",
				"options": {
					"big": "tits_underwear1_big",
					"flat": "tits_underwear1_0",
					"large": "tits_underwear1_large",
					"normal": "tits_underwear1_normal",
					"small": "tits_underwear1_small",
				},
			},
			"equip_pelvis": "pelvis_armor_underwear1",
			"equip_pregnancy_low": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_underwear1_big",
					"mid": "pregnancy_underwear1_small",
				},
			},
			"equip_pregnancy_up": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_underwear1_big",
					"mid": "pregnancy_underwear1_small",
				},
			},
		},
		"zones": [0, 1],
	},
	"outfit_underwear1_legs": {
		"display": "Underwear set 1 (legs)",
		"folders": ["113_armory_set_underwear1"],
		"group": "outfit_legs",
		"slots": {
			"equip_pelvis": "pelvis_armor_underwear1",
		},
		"zones": [0, 1],
	},
	"outfit_underwear2": {
		"display": "Underwear set 2",
		"folders": ["113_armory_set_underwear2"],
		"group": "outfit",
		"slots": {
			"equip_arm_left": "arml_underwear2",
			"equip_arm_right": "armr_underwear2",
			"equip_belly": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_underwear2_big",
					"mid": "pregnancy_underwear2_small",
				},
			},
			"equip_breasts": {
				"axis": "tits_size",
				"options": {
					"big": "tits_underwear2_big",
					"flat": "tits_underwear2_0",
					"large": "tits_underwear2_large",
					"normal": "tits_underwear2_normal",
					"small": "tits_underwear2_small",
				},
			},
			"equip_leg_left": "legl_underwear2",
			"equip_leg_right": "legr_armor_underwear2",
			"equip_pelvis": "pelvis_armor_underwear2",
			"equip_pregnancy_low": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_underwear2_big",
					"mid": "pregnancy_underwear2_small",
				},
			},
			"equip_pregnancy_up": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_underwear2_big",
					"mid": "pregnancy_underwear2_small",
				},
			},
			"equip_shoulder_left": "shoulderl_underwear2",
			"equip_shoulder_right": "shoulderr_underwear2",
			"equip_torso": "torso_underwear2",
		},
		"zones": [0],
	},
	"outfit_underwear2_legs": {
		"display": "Underwear set 2 (legs)",
		"folders": ["113_armory_set_underwear2"],
		"group": "outfit_legs",
		"slots": {
			"equip_leg_left": "legl_underwear2",
			"equip_leg_right": "legr_armor_underwear2",
			"equip_pelvis": "pelvis_armor_underwear2",
		},
		"zones": [0],
	},
	"outfit_waitress": {
		"display": "Waitress set",
		"folders": ["109_armory_set_waitress_female"],
		"group": "outfit",
		"slots": {
			"equip_back": "waitress_back",
			"equip_belly": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_waitress_big",
					"mid": "pregnancy_waitress_mid",
				},
			},
			"equip_breasts": {
				"axis": "tits_size",
				"options": {
					"big": "tits_waitress_big",
					"large": "tits_waitress_large",
					"normal": "tits_waitress_normal",
					"small": "tits_waitress_small",
				},
			},
			"equip_pelvis": "pelvis_armor_waitress",
			"equip_pregnancy_low": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_waitress_big",
					"mid": "pregnancy_waitress_small",
				},
			},
			"equip_pregnancy_up": {
				"axis": "pregnancy",
				"options": {
					"big": "pregnancy_waitress_big",
					"mid": "pregnancy_waitress_small",
				},
			},
			"equip_shoulder_left": "shoulder_armorl_waitress",
			"equip_shoulder_right": "shoulder_armorr_waitress",
			"equip_torso": "torso_armor_waitress",
		},
		"zones": [0, 1],
	},
	"outfit_waitress_legs": {
		"display": "Waitress set (legs)",
		"folders": ["109_armory_set_waitress_female"],
		"group": "outfit_legs",
		"slots": {
			"equip_pelvis": "pelvis_armor_waitress",
		},
		"zones": [0, 1],
	},
	"pigtails": {
		"folders": ["05_hairs_assist"],
		"group": "hair_assist",
		"slots": {
			"hairs_assist": "pigtails",
		},
		"zones": [0],
	},
	"ponytail": {
		"folders": ["05_hairs_assist"],
		"group": "hair_assist",
		"slots": {
			"hairs_assist": "ponytail",
		},
		"zones": [0],
	},
	"race_dragon": {
		"display": "Dragon",
		"folders": ["23_dragon_female"],
		"group": "race_overlay",
		"slots": {
			"race_arm_left": "dragon_arml",
			"race_arm_right": "dragon_armr",
			"race_leg_left": "dragon_legl",
			"race_leg_right": "dragon_legr",
			"race_pelvis": "dragon_pelvis",
			"race_shoulder_left": "dragon_shoulderl",
			"race_shoulder_right": "dragon_shoulderr",
			"race_torso": "dragon_body",
		},
	},
	"race_dragon_scales": {
		"display": "Dragon (scales)",
		"folders": ["23_dragon_female"],
		"group": "race_overlay",
		"slots": {
			"race_arm_left": "dragon_arml",
			"race_arm_right": "dragon_armr",
			"race_leg_left": "dragon_legl 2",
			"race_leg_right": "dragon_legr 2",
			"race_pelvis": "dragon_pelvis 2",
			"race_shoulder_left": "dragon_shoulderl",
			"race_shoulder_right": "dragon_shoulderr",
			"race_torso": "dragon_body 2",
		},
	},
	"race_dragon_scales2": {
		"display": "Dragon (scales 2)",
		"folders": ["23_dragon_female"],
		"group": "race_overlay",
		"slots": {
			"race_arm_left": "dragon_arml",
			"race_arm_right": "dragon_armr",
			"race_leg_left": "dragon_legl",
			"race_leg_right": "dragon_legr",
			"race_pelvis": "dragon_pelvis",
			"race_shoulder_left": "dragon_shoulderl",
			"race_shoulder_right": "dragon_shoulderr",
			"race_torso": "dragon_body3",
		},
	},
	"race_dryad": {
		"display": "Dryad",
		"folders": ["20_dryad"],
		"group": "race_overlay",
		"slots": {
			"race_leg_right": "dryad_legr",
			"race_shoulder_left": "dryad_shoulderl",
			"race_shoulder_right": "dryad_shoulderr",
			"race_torso": "dryad_body",
		},
		"zones": [1],
	},
	"race_kobold": {
		"display": "Kobold",
		"folders": ["24_kobold_female"],
		"group": "race_overlay",
		"slots": {
			"race_arm_left": "kobold_arml1",
			"race_arm_right": "kobold_armr2",
			"race_leg_left": "kobold_legl",
			"race_leg_right": "kobold_legr",
			"race_pelvis": "kobold_pelvis2",
			"race_shoulder_left": "kobold_shoulderl1",
			"race_shoulder_right": "kobold_shoulderr1",
			"race_torso": "kobold_body1_1",
			"race_torso_lower": "kobold_body2_1",
		},
	},
	"race_kobold_spots": {
		"display": "Kobold (spots)",
		"folders": ["24_kobold_female"],
		"group": "race_overlay",
		"slots": {
			"race_arm_left": "kobold_arml2",
			"race_arm_right": "kobold_armr2",
			"race_leg_left": "kobold_legl2",
			"race_leg_right": "kobold_legr2",
			"race_pelvis": "kobold_pelvis2",
			"race_shoulder_left": "kobold_shoulderl2",
			"race_shoulder_right": "kobold_shoulderr2",
			"race_torso": "kobold_body1_2",
			"race_torso_lower": "kobold_body2_2",
		},
	},
	"race_nereid": {
		"display": "Nereid",
		"folders": ["21_nereid"],
		"group": "race_overlay",
		"slots": {
			"race_arm_left": "nereid_arml",
			"race_arm_right": "nereid_armr",
			"race_leg_left": "nereid_legl",
			"race_leg_right": "nereid_legr",
		},
	},
	"race_slime": {
		"display": "Slime",
		"folders": ["22_slime"],
		"group": "race_overlay",
		"slots": {
			"race_arm_left": "slime_arml",
			"race_arm_right": "slime_armr",
			"race_leg_left": "slime_legl",
			"race_leg_right": "slime_legr",
			"race_pelvis": "slime_pelvis",
			"race_torso": "slime_body",
		},
	},
	"scylla_body": {
		"folders": ["14_animals_body"],
		"group": "animal_body",
		"hides": [
			"leg_left",
			"leg_right",
			"equip_leg_left",
			"equip_leg_right",
			"race_leg_left",
			"race_leg_right",
			"dick",
			"testicle",
		],
		"slots": {
			"animal_body": "scylla_body",
		},
	},
	"tail_cat": {
		"folders": ["07_tails"],
		"group": "tails",
		"slots": {
			"tails": "tail_cat",
		},
	},
	"tail_demon": {
		"folders": ["07_tails"],
		"group": "tails",
		"slots": {
			"tails": "tail_demon",
		},
	},
	"tail_dragon": {
		"folders": ["07_tails"],
		"group": "tails",
		"slots": {
			"tails": "tail_dragon",
		},
	},
	"tail_dragon2": {
		"folders": ["07_tails"],
		"group": "tails",
		"slots": {
			"tails": "tail_dragon2",
		},
	},
	"tail_fox": {
		"folders": ["07_tails"],
		"group": "tails",
		"slots": {
			"tails": "tail_fox",
		},
		"zones": [0],
	},
	"tail_fox_2": {
		"folders": ["07_tails"],
		"group": "tails",
		"slots": {
			"tails": "07_tails/tail_fox_2",
		},
		"zones": [0],
	},
	"tail_fox_3": {
		"folders": ["07_tails"],
		"group": "tails",
		"slots": {
			"tails": "07_tails/tail_fox_3",
		},
		"zones": [0],
	},
	"tail_kobold": {
		"folders": ["07_tails"],
		"group": "tails",
		"slots": {
			"tails": "tail_kobold",
		},
	},
	"tail_mouse": {
		"folders": ["07_tails"],
		"group": "tails",
		"slots": {
			"tails": "tail_mouse",
		},
	},
	"tail_nereid": {
		"folders": ["07_tails"],
		"group": "tails",
		"slots": {
			"tails": "tail_nereid",
		},
	},
	"tail_tanuk": {
		"folders": ["07_tails"],
		"group": "tails",
		"slots": {
			"tails": "tail_tanuk",
		},
	},
	"tail_wolf": {
		"folders": ["07_tails"],
		"group": "tails",
		"slots": {
			"tails": "tail_wolf",
		},
	},
	"tatoo_womb1": {
		"folders": ["97_tatoos"],
		"group": "tattoo",
		"slots": {
			"tatoos": "tatoo_womb1",
		},
	},
	"tatoo_womb10": {
		"folders": ["97_tatoos"],
		"group": "tattoo",
		"slots": {
			"tatoos": "tatoo_womb10",
		},
	},
	"tatoo_womb2": {
		"folders": ["97_tatoos"],
		"group": "tattoo",
		"slots": {
			"tatoos": "tatoo_womb2",
		},
	},
	"tatoo_womb3": {
		"folders": ["97_tatoos"],
		"group": "tattoo",
		"slots": {
			"tatoos": "tatoo_womb3",
		},
	},
	"tatoo_womb4": {
		"folders": ["97_tatoos"],
		"group": "tattoo",
		"slots": {
			"tatoos": "tatoo_womb4",
		},
	},
	"tatoo_womb5": {
		"folders": ["97_tatoos"],
		"group": "tattoo",
		"slots": {
			"tatoos": "tatoo_womb5",
		},
	},
	"tatoo_womb6": {
		"folders": ["97_tatoos"],
		"group": "tattoo",
		"slots": {
			"tatoos": "tatoo_womb6",
		},
	},
	"tatoo_womb7": {
		"folders": ["97_tatoos"],
		"group": "tattoo",
		"slots": {
			"tatoos": "tatoo_womb7",
		},
	},
	"tatoo_womb8": {
		"folders": ["97_tatoos"],
		"group": "tattoo",
		"slots": {
			"tatoos": "tatoo_womb8",
		},
	},
	"tatoo_womb9": {
		"folders": ["97_tatoos"],
		"group": "tattoo",
		"slots": {
			"tatoos": "tatoo_womb9",
		},
	},
	"twin_braids": {
		"folders": ["05_hairs_assist"],
		"group": "hair_assist",
		"slots": {
			"hairs_assist": "twin braids",
		},
		"zones": [0],
	},
	"twin_tails_3": {
		"folders": ["05_hairs_assist"],
		"group": "hair_assist",
		"slots": {
			"hairs_assist": "twin_tails 3",
		},
		"zones": [0],
	},
	"weapon_back_axe1": {
		"folders": ["201_weapon_back"],
		"group": "weapon_back",
		"slots": {
			"weapon_back": "weapon_back_axe1",
		},
		"zones": [0, 1],
	},
	"weapon_back_axe2": {
		"folders": ["201_weapon_back"],
		"group": "weapon_back",
		"slots": {
			"weapon_back": "weapon_back_axe2",
		},
		"zones": [0, 1, 2],
	},
	"weapon_back_bow": {
		"folders": ["201_weapon_back"],
		"group": "weapon_back",
		"slots": {
			"weapon_back": "weapon_back_bow",
		},
		"zones": [0, 1],
	},
	"weapon_back_bow2": {
		"folders": ["201_weapon_back"],
		"group": "weapon_back",
		"slots": {
			"weapon_back": "weapon_back_bow2",
		},
		"zones": [0, 1],
	},
	"weapon_back_crossbow1": {
		"folders": ["201_weapon_back"],
		"group": "weapon_back",
		"slots": {
			"weapon_back": "weapon_back_crossbow1",
		},
		"zones": [0, 1],
	},
	"weapon_back_crossbow2": {
		"folders": ["201_weapon_back"],
		"group": "weapon_back",
		"slots": {
			"weapon_back": "weapon_back_crossbow2",
		},
		"zones": [0, 1, 2],
	},
	"weapon_back_mace2": {
		"folders": ["201_weapon_back"],
		"group": "weapon_back",
		"slots": {
			"weapon_back": "weapon_back_mace2",
		},
		"zones": [0, 1, 2],
	},
	"weapon_back_spear": {
		"folders": ["201_weapon_back"],
		"group": "weapon_back",
		"slots": {
			"weapon_back": "weapon_back_spear",
		},
		"zones": [0, 1],
	},
	"weapon_back_spear2": {
		"folders": ["201_weapon_back"],
		"group": "weapon_back",
		"slots": {
			"weapon_back": "weapon_back_spear2",
		},
		"zones": [0, 1],
	},
	"weapon_back_stick": {
		"folders": ["201_weapon_back"],
		"group": "weapon_back",
		"slots": {
			"weapon_back": "weapon_back_stick",
		},
		"zones": [0, 1],
	},
	"weapon_back_stick2": {
		"folders": ["201_weapon_back"],
		"group": "weapon_back",
		"slots": {
			"weapon_back": "weapon_back_stick2",
		},
		"zones": [0, 1],
	},
	"weapon_belt_bat": {
		"folders": ["200_weapon_belt"],
		"group": "weapon_belt",
		"slots": {
			"weapon_belt": "weapon_belt_bat",
		},
		"zones": [0, 1],
	},
	"weapon_belt_dagger": {
		"folders": ["200_weapon_belt"],
		"group": "weapon_belt",
		"slots": {
			"weapon_belt": "weapon_belt_dagger",
		},
		"zones": [0, 1],
	},
	"weapon_belt_dagger2": {
		"folders": ["200_weapon_belt"],
		"group": "weapon_belt",
		"slots": {
			"weapon_belt": "weapon_belt_dagger2",
		},
		"zones": [0, 1],
	},
	"weapon_belt_mace": {
		"folders": ["200_weapon_belt"],
		"group": "weapon_belt",
		"slots": {
			"weapon_belt": "weapon_belt_mace",
		},
		"zones": [0, 1],
	},
	"weapon_belt_sword": {
		"folders": ["200_weapon_belt"],
		"group": "weapon_belt",
		"slots": {
			"weapon_belt": "weapon_belt_sword",
		},
		"zones": [0, 1],
	},
	"weapon_belt_sword2": {
		"folders": ["200_weapon_belt"],
		"group": "weapon_belt",
		"slots": {
			"weapon_belt": "weapon_belt_sword2",
		},
		"zones": [0, 1],
	},
	"wings_demon": {
		"folders": ["09_wings"],
		"group": "wings",
		"slots": {
			"wings": "wings_demon",
		},
	},
	"wings_harpia": {
		"folders": ["09_wings"],
		"group": "wings",
		"hides": [
			"arm_left",
			"arm_right",
			"hand_left",
			"hand_right",
			"equip_arm_left",
			"equip_arm_right",
			"equip_hand_left",
			"equip_hand_right",
			"race_arm_left",
			"race_arm_right",
		],
		"slots": {
			"wings": "wings_harpia",
		},
		"zones": [0],
	},
}

const PRESETS = {
	"arachna": {
		"animal_body": "arachna_body",
	},
	"cat": {
		"ears": "ears_cat",
		"tails": "tail_cat",
	},
	"demon": {
		"horns": "horn_curve_up",
		"tails": "tail_demon",
		"wings": "wings_demon",
	},
	"dragon": {
		"face_markings": "head_dragon_mask",
		"horns": "horn_dragon2",
		"race_overlay": "race_dragon",
		"tails": "tail_dragon",
		"wings": "Wings_dragon",
	},
	"dryad": {
		"race_overlay": "race_dryad",
	},
	"elf": {
		"ears": "ears_elven",
	},
	"fairy": {
		"wings": "Wings_fairy",
	},
	"fox": {
		"ears": "ears_fox_n1",
		"tails": "tail_fox",
	},
	"goblin": {
		"ears": "ears_goblin",
	},
	"harpia": {
		"wings": "wings_harpia",
	},
	"kentaur": {
		"animal_body": "kentaur_body",
	},
	"kobold": {
		"face_markings": "kobold_head_kobold",
		"nose": "nose_kobold",
		"race_overlay": "race_kobold",
		"tails": "tail_kobold",
	},
	"lamia": {
		"animal_body": "lamia_body",
	},
	"mouse": {
		"ears": "ears_mouse",
		"tails": "tail_mouse",
	},
	"nereid": {
		"ears": "ears_nereid",
		"race_overlay": "race_nereid",
		"tails": "tail_nereid",
	},
	"orc": {
		"ears": "ears_orc",
		"lips": "lips_orc",
	},
	"rabbit": {
		"ears": "ears_rabbit",
	},
	"scylla": {
		"animal_body": "scylla_body",
	},
	"seraph": {
		"horns": "horn_seraph_fibule",
		"wings": "Wings_seraph",
	},
	"slime": {
		"race_overlay": "race_slime",
	},
	"tanuki": {
		"ears": "ears_tanuk",
		"tails": "tail_tanuk",
	},
	"wolf": {
		"ears": "ears_wolf",
		"tails": "tail_wolf",
	},
}

const ALIASES = {
	"breast_nipples": {
		"beastkin_tits_nipples__body_female_beastkin": "beastkin_tits_nipples",
		"beastkin_tits_nipples_big__body_female_beastkin": "beastkin_tits_nipples_big",
		"beastkin_tits_nipples_small": "tits_nipples_normal",
		"beastkin_tits_nipples_small__2": "beastkin_tits_nipples_small__body_female_beastkin",
	},
	"dick": {
		"dick_furry_up__body_female_beastkin": "dick_furry_up",
		"dick_human_up": "dick_horse_up",
		"dick_human_up__body_female_base": "dick_horse_up",
	},
	"equip_breasts": {
		"flat": "tits_cloth3_small",
		"tits_jacket_small__107_armory_set_jacket_female": "tits_jacket_small",
	},
	"horns": {
		"horn_seraph_fibule__seraph": "horn_seraph_fibule",
		"horns": "horn_dragon2",
	},
	"lips": {
		"beastkin_lips_open": "lips_m1",
		"lips_beast": "lips_m1",
	},
	"noses": {
		"nose_kobold_2__spots": "nose_kobold_2",
	},
	"testicle": {
		"testicle_furry__body_female_beastkin": "testicle_furry",
		"testicle_human__body_female_base": "testicle_human",
	},
	"torso": {
		"torso__body_female_base": "torso",
	},
}

const UNCATEGORIZED = {}

