extends Reference

# GENERATED by doll2_catalogue_build.gd - DO NOT EDIT.
# Semantics for the Doll 2 Spine export: groups, parts and axis values.
# Change doll2_overrides.gd and rebuild instead of editing this file.
# Mesh, vertex, UV and animation data stay in the Spine JSON.

const SCHEMA_VERSION = 2

const SOURCE = {
	"atlas": "Doll2_spine4.2_male.atlas",
	"attachment_count": 446,
	"bone_count": 251,
	"contract": "doll2_male_v1",
	"skeleton": "Doll2_spine4.2_male.json",
	"skeleton_hash": "9Ahy+gO8fto",
	"slot_count": 58,
	"spine_version": "4.2.43",
}

const SLOT_ORDER = [
	"animal_body",
	"weapon_back",
	"wings",
	"hairs_back",
	"hairs_assist",
	"tails",
	"equip_back",
	"hand_left",
	"arm_left",
	"race_arm_left",
	"shoulder_left",
	"race_shoulder_left",
	"hand_right",
	"arm_right",
	"race_arm_right",
	"shoulder_right",
	"race_shoulder_right",
	"leg_left",
	"leg_right",
	"pelvis",
	"equip_collar",
	"race_leg_left",
	"equip_leg_left",
	"race_leg_right",
	"equip_leg_right",
	"torso",
	"nipples",
	"race_torso_lower",
	"race_torso",
	"race_pelvis",
	"animal_frontbody",
	"testicle",
	"dick",
	"tatoos",
	"equip_hand_left",
	"equip_hand_right",
	"equip_arm_left",
	"equip_arm_right",
	"equip_shoulder_left",
	"equip_shoulder_right",
	"equip_pelvis",
	"equip_torso",
	"weapon_belt",
	"head_skull",
	"head",
	"hairs_base",
	"sclera",
	"eyes",
	"face",
	"ears",
	"noses",
	"race_head",
	"equip_masks",
	"hairs_fringe",
	"equip_head",
	"horns",
	"eyebrows",
	"lips",
]

const DRAW_ORDER = [
	"animal_body",
	"weapon_back",
	"wings",
	"hairs_back",
	"hairs_assist",
	"tails",
	"equip_back",
	"hand_left",
	"arm_left",
	"race_arm_left",
	"shoulder_left",
	"race_shoulder_left",
	"hand_right",
	"arm_right",
	"race_arm_right",
	"shoulder_right",
	"race_shoulder_right",
	"leg_left",
	"leg_right",
	"pelvis",
	"equip_collar",
	"race_leg_left",
	"equip_leg_left",
	"race_leg_right",
	"equip_leg_right",
	"torso",
	"nipples",
	"race_torso_lower",
	"race_torso",
	"race_pelvis",
	"animal_frontbody",
	"testicle",
	"dick",
	"tatoos",
	"equip_hand_left",
	"equip_hand_right",
	"equip_arm_left",
	"equip_arm_right",
	"equip_shoulder_left",
	"equip_shoulder_right",
	"equip_pelvis",
	"equip_torso",
	"weapon_belt",
	"head_skull",
	"head",
	"hairs_base",
	"sclera",
	"eyes",
	"face",
	"ears",
	"noses",
	"race_head",
	"equip_masks",
	"hairs_fringe",
	"equip_head",
	"horns",
	"eyebrows",
	"lips",
]

const DRAW_ORDER_FIXES = [
	{
		"before": "equip_torso",
		"slot": "tatoos",
	},
	{
		"before": "equip_pelvis",
		"slot": "dick",
	},
]

const GROUP_ORDER = [
	"body",
	"head",
	"face",
	"eyes",
	"eyebrows",
	"nose",
	"lips",
	"ears",
	"hair",
	"hair_back",
	"hair_assist",
	"horns",
	"wings",
	"tails",
	"animal_body",
	"race_overlay",
	"face_markings",
	"genitals",
	"tattoo",
	"outfit",
	"collar",
	"headgear",
	"mask",
	"weapon_belt",
	"weapon_back",
]

const AXES = {
	"body_shape": {
		"default": "male",
		"label": "DOLL2_PREVIEW_BODY_SHAPE",
		"values": ["male", "femboy"],
	},
	"hand_pose": {
		"default": "1",
		"label": "DOLL2_PREVIEW_HAND_POSE",
		"values": ["1", "2", "3"],
	},
}

const FIXED_SLOTS = {
	"sclera": "sklera",
}

const COLOR_CHANNELS = {
	"animal": {
		"anchor": "animal_body",
		"coverage": false,
		"gear": false,
		"slots": ["animal_body", "animal_frontbody"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": true,
	},
	"collar": {
		"anchor": "collar",
		"coverage": false,
		"gear": true,
		"slots": ["equip_collar"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": true,
	},
	"ears": {
		"anchor": "ears",
		"coverage": false,
		"gear": false,
		"slots": ["ears"],
		"two_tone": false,
		"zone_defaults": [
			Color(0.603922, 0.482353, 0.372549, 1),
			Color(0.85098, 0.635294, 0.635294, 1),
			Color(1, 1, 1, 1),
		],
		"zones": true,
	},
	"eyebrows": {
		"anchor": "eyebrows",
		"coverage": false,
		"gear": false,
		"slots": ["eyebrows"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": false,
	},
	"eyes": {
		"anchor": "eyes",
		"coverage": false,
		"gear": false,
		"slots": ["eyes"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": false,
	},
	"face_markings": {
		"anchor": "face_markings",
		"coverage": false,
		"gear": false,
		"slots": ["race_head"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": false,
	},
	"hair": {
		"anchor": "hair",
		"coverage": false,
		"gear": false,
		"slots": ["hairs_base", "hairs_fringe"],
		"two_tone": true,
		"zone_defaults": [],
		"zones": false,
	},
	"hair_assist": {
		"anchor": "hair_assist",
		"coverage": false,
		"gear": false,
		"slots": ["hairs_assist"],
		"two_tone": true,
		"zone_defaults": [],
		"zones": false,
	},
	"hair_back": {
		"anchor": "hair_back",
		"coverage": false,
		"gear": false,
		"slots": ["hairs_back"],
		"two_tone": true,
		"zone_defaults": [],
		"zones": false,
	},
	"headgear": {
		"anchor": "headgear",
		"coverage": false,
		"gear": true,
		"slots": ["equip_head"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": true,
	},
	"horns": {
		"anchor": "horns",
		"coverage": false,
		"gear": false,
		"slots": ["horns"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": false,
	},
	"lips": {
		"anchor": "lips",
		"coverage": false,
		"gear": false,
		"slots": ["lips"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": false,
	},
	"mask": {
		"anchor": "mask",
		"coverage": false,
		"gear": true,
		"slots": ["equip_masks"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": true,
	},
	"outfit": {
		"anchor": "outfit",
		"coverage": false,
		"gear": true,
		"slots": [
			"equip_arm_left",
			"equip_arm_right",
			"equip_back",
			"equip_hand_left",
			"equip_hand_right",
			"equip_leg_left",
			"equip_leg_right",
			"equip_pelvis",
			"equip_shoulder_left",
			"equip_shoulder_right",
			"equip_torso",
		],
		"two_tone": false,
		"zone_defaults": [],
		"zones": true,
	},
	"race": {
		"anchor": "race_overlay",
		"coverage": false,
		"gear": false,
		"slots": [
			"race_arm_left",
			"race_arm_right",
			"race_leg_left",
			"race_leg_right",
			"race_pelvis",
			"race_shoulder_left",
			"race_shoulder_right",
			"race_torso",
			"race_torso_lower",
		],
		"two_tone": false,
		"zone_defaults": [],
		"zones": false,
	},
	"skin": {
		"anchor": "body",
		"coverage": true,
		"gear": false,
		"slots": [
			"arm_left",
			"arm_right",
			"dick",
			"face",
			"hand_left",
			"hand_right",
			"head",
			"head_skull",
			"leg_left",
			"leg_right",
			"nipples",
			"noses",
			"pelvis",
			"shoulder_left",
			"shoulder_right",
			"testicle",
			"torso",
		],
		"two_tone": false,
		"zone_defaults": [],
		"zones": false,
	},
	"tail": {
		"anchor": "tails",
		"coverage": false,
		"gear": false,
		"slots": ["tails"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": false,
	},
	"tattoo": {
		"anchor": "tattoo",
		"coverage": false,
		"gear": false,
		"slots": ["tatoos"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": false,
	},
	"weapon": {
		"anchor": "weapon_belt",
		"coverage": false,
		"gear": true,
		"slots": ["weapon_back", "weapon_belt"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": true,
	},
	"wings": {
		"anchor": "wings",
		"coverage": false,
		"gear": false,
		"slots": ["wings"],
		"two_tone": false,
		"zone_defaults": [],
		"zones": true,
	},
}

const SLOT_COLORS = {
	"animal_body": "animal",
	"animal_frontbody": "animal",
	"arm_left": "skin",
	"arm_right": "skin",
	"dick": "skin",
	"ears": "ears",
	"equip_arm_left": "outfit",
	"equip_arm_right": "outfit",
	"equip_back": "outfit",
	"equip_collar": "collar",
	"equip_hand_left": "outfit",
	"equip_hand_right": "outfit",
	"equip_head": "headgear",
	"equip_leg_left": "outfit",
	"equip_leg_right": "outfit",
	"equip_masks": "mask",
	"equip_pelvis": "outfit",
	"equip_shoulder_left": "outfit",
	"equip_shoulder_right": "outfit",
	"equip_torso": "outfit",
	"eyebrows": "eyebrows",
	"eyes": "eyes",
	"face": "skin",
	"hairs_assist": "hair_assist",
	"hairs_back": "hair_back",
	"hairs_base": "hair",
	"hairs_fringe": "hair",
	"hand_left": "skin",
	"hand_right": "skin",
	"head": "skin",
	"head_skull": "skin",
	"horns": "horns",
	"leg_left": "skin",
	"leg_right": "skin",
	"lips": "lips",
	"nipples": "skin",
	"noses": "skin",
	"pelvis": "skin",
	"race_arm_left": "race",
	"race_arm_right": "race",
	"race_head": "face_markings",
	"race_leg_left": "race",
	"race_leg_right": "race",
	"race_pelvis": "race",
	"race_shoulder_left": "race",
	"race_shoulder_right": "race",
	"race_torso": "race",
	"race_torso_lower": "race",
	"shoulder_left": "skin",
	"shoulder_right": "skin",
	"tails": "tail",
	"tatoos": "tattoo",
	"testicle": "skin",
	"torso": "skin",
	"weapon_back": "weapon",
	"weapon_belt": "weapon",
	"wings": "wings",
}

const ZONE_HUES = [299, 90, 156]

const ZONE_DISTANCE = [15, 32, 26]

const ZONE_DEFAULTS = [
	Color(0.603922, 0.65098, 0.705882, 1),
	Color(0.435294, 0.317647, 0.2, 1),
	Color(0.552941, 0.231373, 0.231373, 1),
]

const GROUPS = {
	"animal_body": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_ANIMAL_BODY",
		"optional": true,
		"order": 15,
		"parts": ["arachna_body", "kentaur_body", "lamia_body", "scylla_body"],
		"slots": ["animal_body", "animal_frontbody"],
	},
	"body": {
		"default": "body_male_base",
		"kind": "set",
		"label": "DOLL2_PREVIEW_BODY",
		"optional": false,
		"order": 0,
		"parts": ["body_male_base", "body_male_beastkin", "body_male_femboy"],
		"slots": [
			"arm_left",
			"arm_right",
			"hand_left",
			"hand_right",
			"leg_left",
			"leg_right",
			"nipples",
			"pelvis",
			"shoulder_left",
			"shoulder_right",
			"torso",
		],
	},
	"collar": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_COLLAR",
		"optional": true,
		"order": 21,
		"parts": [
			"collar_bell_big",
			"collar_bell_small",
			"collar_heart_big",
			"collar_heart_small",
			"collar_leather_big",
			"collar_leather_small",
			"collar_metallic_big",
			"collar_metallic_small",
			"collar_steel_big",
			"collar_steel_small",
		],
		"slots": ["equip_collar"],
	},
	"ears": {
		"default": "ears_human",
		"kind": "options",
		"label": "DOLL2_PREVIEW_EARS",
		"optional": true,
		"order": 7,
		"parts": [
			"ears_cat",
			"ears_elven",
			"ears_fox",
			"ears_goblin",
			"ears_human",
			"ears_mouse",
			"ears_nereid",
			"ears_orc",
			"ears_rabbit",
			"ears_rabbit2",
			"ears_rabbit3",
			"ears_tanuk",
			"ears_taurus",
			"ears_wolf",
		],
		"slots": ["ears"],
	},
	"eyebrows": {
		"default": "eyebrows1",
		"kind": "options",
		"label": "DOLL2_PREVIEW_EYEBROWS",
		"optional": true,
		"order": 4,
		"parts": [
			"eyebrows1",
			"eyebrows2",
			"eyebrows3",
			"eyebrows4",
			"eyebrows5",
			"eyebrows_m1",
			"eyebrows_m2",
			"eyebrows_m3",
		],
		"slots": ["eyebrows"],
	},
	"eyes": {
		"default": "eyes_m5",
		"kind": "options",
		"label": "DOLL2_PREVIEW_EYES",
		"optional": false,
		"order": 3,
		"parts": [
			"eyes1",
			"eyes2",
			"eyes3",
			"eyes4",
			"eyes5",
			"eyes_m1",
			"eyes_m2",
			"eyes_m3",
			"eyes_m4",
			"eyes_m5",
		],
		"slots": ["eyes"],
	},
	"face": {
		"default": "face3",
		"kind": "options",
		"label": "DOLL2_PREVIEW_FACE",
		"optional": false,
		"order": 2,
		"parts": [
			"beastkin_face1",
			"beastkin_face2",
			"beastkin_face3",
			"beastkin_face4",
			"beastkin_face5",
			"beastkin_face6",
			"beastkin_face7",
			"beastkin_face8",
			"beastkin_face_m1",
			"beastkin_face_m2",
			"beastkin_face_m3",
			"beastkin_face_m4",
			"beastkin_face_m5",
			"face1",
			"face2",
			"face3",
			"face4",
			"face5",
			"face6",
			"face7",
			"face8",
			"face_m1",
			"face_m2",
			"face_m3",
			"face_m4",
			"face_m5",
		],
		"slots": ["face"],
	},
	"face_markings": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_FACE_MARKINGS",
		"optional": true,
		"order": 17,
		"parts": ["head_m_dragon", "head_m_dragon2", "kobold_head_kobold", "kobold_head_mask1"],
		"slots": ["race_head"],
	},
	"genitals": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_GENITALS",
		"optional": true,
		"order": 18,
		"parts": ["Dick_furry_up", "Dick_horse_up", "Dick_human_up"],
		"slots": ["dick", "testicle"],
	},
	"hair": {
		"default": "hair_base_straight",
		"kind": "options",
		"label": "DOLL2_PREVIEW_HAIR",
		"optional": true,
		"order": 8,
		"parts": [
			"hair_base_back",
			"hair_base_braids",
			"hair_base_default",
			"hair_base_dopple",
			"hair_base_fringe",
			"hair_base_fringe_2",
			"hair_base_irokez",
			"hair_base_kare",
			"hair_base_lamb",
			"hair_base_parting",
			"hair_base_slave",
			"hair_base_straight",
			"hair_base_undercut",
			"hairs_base_dopple",
			"hairs_base_irokez",
			"hairs_base_lion",
			"hairs_base_parting",
			"hairs_base_slave",
			"hairs_base_undercut",
		],
		"slots": ["hairs_base", "hairs_fringe"],
	},
	"hair_assist": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_HAIR_ACCESSORY",
		"optional": true,
		"order": 11,
		"parts": [
			"Twin_tails_2",
			"braid",
			"bun",
			"hair_assist_braid",
			"hair_assist_bun",
			"hair_assist_pigtails",
			"hair_assist_ponytail",
			"hair_assist_twin_tails",
			"hair_assist_twin_tails_2",
			"pigtails",
			"ponytail",
			"ponytail_2",
			"ponytail_3",
			"twin_braids",
			"twin_tails",
			"twin_tails_3",
		],
		"slots": ["hairs_assist"],
	},
	"hair_back": {
		"default": "hair_back_straight",
		"kind": "options",
		"label": "DOLL2_PREVIEW_HAIR_BACK",
		"optional": true,
		"order": 10,
		"parts": [
			"hair_back_care",
			"hair_back_dishevel",
			"hair_back_double_tail_long",
			"hair_back_ponytail_long",
			"hair_back_spiral",
			"hair_back_straight",
			"hair_back_twin_braids",
			"hair_back_verylong1",
			"hair_back_wawe",
		],
		"slots": ["hairs_back"],
	},
	"head": {
		"default": "head_chin_default",
		"kind": "options",
		"label": "DOLL2_PREVIEW_HEAD",
		"optional": false,
		"order": 1,
		"parts": [
			"beastkin_chin_cat",
			"beastkin_chin_fox",
			"beastkin_chin_rabbit",
			"beastkin_chin_tanuki",
			"beastkin_chin_wolf",
			"head_chin_curve",
			"head_chin_curve_kobold",
			"head_chin_default",
			"head_chin_kobold2",
			"head_chin_loli",
			"head_chin_long_skinny",
			"head_chin_male",
			"head_chin_muscle",
			"head_chin_short",
			"head_chin_small",
		],
		"slots": ["head", "head_skull"],
	},
	"headgear": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_HEADGEAR",
		"optional": true,
		"order": 22,
		"parts": [
			"Petsuit_cat",
			"Petsuit_rabbit3",
			"hair_armor_maid",
			"hair_armor_playboy",
			"hair_armor_waitress",
		],
		"slots": ["equip_head"],
	},
	"horns": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_HORNS",
		"optional": true,
		"order": 12,
		"parts": [
			"Horn_straight_diagonal",
			"Horn_straight_top",
			"horn_curve_down",
			"horn_curve_top",
			"horn_curve_up",
			"horn_dragon2",
			"horn_seraph_fibule",
			"horn_spiral_2",
		],
		"slots": ["horns"],
	},
	"lips": {
		"default": "lips1",
		"kind": "options",
		"label": "DOLL2_PREVIEW_LIPS",
		"optional": true,
		"order": 6,
		"parts": [
			"beastkin_lips_cry",
			"beastkin_lips_open",
			"beastkin_lips_smile",
			"lips1",
			"lips2",
			"lips3",
			"lips4",
			"lips5",
			"lips_beast",
			"lips_m1",
			"lips_m2",
			"lips_m3",
			"lips_m4",
			"lips_orc",
			"lips_orc_1",
			"lips_orc_2",
			"lips_orc_3",
		],
		"slots": ["lips"],
	},
	"mask": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_MASK",
		"optional": true,
		"order": 23,
		"parts": ["facemask1", "facemask2"],
		"slots": ["equip_masks"],
	},
	"nose": {
		"default": "nose_default",
		"kind": "options",
		"label": "DOLL2_PREVIEW_NOSE",
		"optional": true,
		"order": 5,
		"parts": [
			"nose_default",
			"nose_dwarf",
			"nose_kobold",
			"nose_kobold_2",
			"nose_small",
			"nose_straight",
		],
		"slots": ["noses"],
	},
	"outfit": {
		"default": "",
		"kind": "set",
		"label": "DOLL2_PREVIEW_OUTFIT",
		"optional": true,
		"order": 20,
		"parts": [
			"outfit_cloth",
			"outfit_cloth2",
			"outfit_cloth3",
			"outfit_jacket",
			"outfit_latex",
			"outfit_latex2",
			"outfit_leather",
			"outfit_leather2",
			"outfit_plate",
			"outfit_plate2",
			"outfit_servant",
			"outfit_slave",
			"outfit_smith",
			"outfit_tentacle",
			"outfit_waiter",
		],
		"slots": [
			"equip_arm_left",
			"equip_arm_right",
			"equip_back",
			"equip_hand_left",
			"equip_hand_right",
			"equip_leg_left",
			"equip_leg_right",
			"equip_pelvis",
			"equip_shoulder_left",
			"equip_shoulder_right",
			"equip_torso",
		],
	},
	"race_overlay": {
		"default": "",
		"kind": "set",
		"label": "DOLL2_PREVIEW_RACE_OVERLAY",
		"optional": true,
		"order": 16,
		"parts": [
			"race_dragon",
			"race_dragon_scales",
			"race_dragon_scales2",
			"race_dryad",
			"race_kobold",
			"race_kobold_spots",
			"race_nereid",
			"race_slime",
		],
		"slots": [
			"race_arm_left",
			"race_arm_right",
			"race_leg_left",
			"race_leg_right",
			"race_pelvis",
			"race_shoulder_left",
			"race_shoulder_right",
			"race_torso",
			"race_torso_lower",
		],
	},
	"tails": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_TAILS",
		"optional": true,
		"order": 14,
		"parts": [
			"tail_cat",
			"tail_demon",
			"tail_dragon",
			"tail_dragon2",
			"tail_fox",
			"tail_kobold",
			"tail_mouse",
			"tail_nereid",
			"tail_tanuk",
			"tail_wolf",
		],
		"slots": ["tails"],
	},
	"tattoo": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_TATTOO",
		"optional": true,
		"order": 19,
		"parts": [
			"tatoo_womb1",
			"tatoo_womb10",
			"tatoo_womb2",
			"tatoo_womb3",
			"tatoo_womb4",
			"tatoo_womb5",
			"tatoo_womb6",
			"tatoo_womb7",
			"tatoo_womb8",
			"tatoo_womb9",
		],
		"slots": ["tatoos"],
	},
	"weapon_back": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_WEAPON_BACK",
		"optional": true,
		"order": 25,
		"parts": [
			"weapon_back_axe1",
			"weapon_back_axe2",
			"weapon_back_bow",
			"weapon_back_bow2",
			"weapon_back_crossbow1",
			"weapon_back_crossbow2",
			"weapon_back_mace2",
			"weapon_back_spear",
			"weapon_back_spear2",
			"weapon_back_stick",
			"weapon_back_stick2",
		],
		"slots": ["weapon_back"],
	},
	"weapon_belt": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_WEAPON_BELT",
		"optional": true,
		"order": 24,
		"parts": [
			"weapon_belt_bat",
			"weapon_belt_dagger",
			"weapon_belt_dagger2",
			"weapon_belt_mace",
			"weapon_belt_sword",
			"weapon_belt_sword2",
		],
		"slots": ["weapon_belt"],
	},
	"wings": {
		"default": "",
		"kind": "options",
		"label": "DOLL2_PREVIEW_WINGS",
		"optional": true,
		"order": 13,
		"parts": ["Wings_dragon", "Wings_fairy", "Wings_seraph", "wings_demon", "wings_harpia"],
		"slots": ["wings"],
	},
}

const PARTS = {
	"Dick_furry_up": {
		"folders": ["13_dicks"],
		"group": "genitals",
		"slots": {
			"dick": "dick_furry_up",
			"testicle": "testicle_furry",
		},
	},
	"Dick_horse_up": {
		"folders": ["13_dicks"],
		"group": "genitals",
		"slots": {
			"dick": "dick_horse_up",
			"testicle": "testicle_furry",
		},
		"zones": [0, 1],
	},
	"Dick_human_up": {
		"folders": ["13_dicks"],
		"group": "genitals",
		"slots": {
			"dick": "dick_human_up",
			"testicle": "testicle_human",
		},
	},
	"Horn_straight_diagonal": {
		"folders": ["08_horns"],
		"group": "horns",
		"slots": {
			"horns": "horn_straight_diagonal",
		},
	},
	"Horn_straight_top": {
		"folders": ["08_horns"],
		"group": "horns",
		"slots": {
			"horns": "horn_straight_top",
		},
	},
	"Petsuit_cat": {
		"folders": ["151_armory_acces_petsuit"],
		"group": "headgear",
		"slots": {
			"equip_head": "petsuit_cat",
		},
	},
	"Petsuit_rabbit3": {
		"folders": ["151_armory_acces_petsuit"],
		"group": "headgear",
		"slots": {
			"equip_head": "petsuit_rabbit3",
		},
	},
	"Twin_tails_2": {
		"folders": ["05_hairs_assist"],
		"group": "hair_assist",
		"slots": {
			"hairs_assist": "twin_tails_2",
		},
	},
	"Wings_dragon": {
		"folders": ["09_wings"],
		"group": "wings",
		"slots": {
			"wings": "wings_dragon",
		},
	},
	"Wings_fairy": {
		"folders": ["09_wings"],
		"group": "wings",
		"slots": {
			"wings": "wings_fairy",
		},
		"zones": [2],
	},
	"Wings_seraph": {
		"folders": ["09_wings"],
		"group": "wings",
		"slots": {
			"wings": "wings_seraph",
		},
		"zones": [0],
	},
	"arachna_body": {
		"folders": ["14_animals_body"],
		"group": "animal_body",
		"hides": [
			"leg_left",
			"leg_right",
			"equip_leg_left",
			"equip_leg_right",
			"race_leg_left",
			"race_leg_right",
			"pelvis",
			"equip_pelvis",
			"race_pelvis",
		],
		"slots": {
			"animal_body": "arachna_body",
			"animal_frontbody": "arachna_helicere",
		},
	},
	"beastkin_chin_cat": {
		"display": "Muzzle: cat",
		"folders": ["16_beastkin_heads_new"],
		"group": "head",
		"slots": {
			"head": "beastkin_chin_cat",
			"head_skull": "beastkin_skull",
		},
		"tags": ["beastkin"],
	},
	"beastkin_chin_fox": {
		"display": "Muzzle: fox",
		"folders": ["16_beastkin_heads_new"],
		"group": "head",
		"slots": {
			"head": "beastkin_chin_fox",
			"head_skull": "beastkin_skull",
		},
		"tags": ["beastkin"],
	},
	"beastkin_chin_rabbit": {
		"display": "Muzzle: rabbit",
		"folders": ["16_beastkin_heads_new"],
		"group": "head",
		"slots": {
			"head": "beastkin_chin_rabbit",
			"head_skull": "beastkin_skull",
		},
		"tags": ["beastkin"],
	},
	"beastkin_chin_tanuki": {
		"display": "Muzzle: tanuki",
		"folders": ["16_beastkin_heads_new"],
		"group": "head",
		"slots": {
			"head": "beastkin_chin_tanuki",
			"head_skull": "beastkin_skull",
		},
		"tags": ["beastkin"],
	},
	"beastkin_chin_wolf": {
		"display": "Muzzle: wolf",
		"folders": ["16_beastkin_heads_new"],
		"group": "head",
		"slots": {
			"head": "beastkin_chin_wolf",
			"head_skull": "beastkin_skull",
		},
		"tags": ["beastkin"],
	},
	"beastkin_face1": {
		"folders": ["17_beastkin_faces"],
		"group": "face",
		"slots": {
			"face": "beastkin_face1",
		},
		"tags": ["beastkin"],
	},
	"beastkin_face2": {
		"folders": ["17_beastkin_faces"],
		"group": "face",
		"slots": {
			"face": "beastkin_face2",
		},
		"tags": ["beastkin"],
	},
	"beastkin_face3": {
		"folders": ["17_beastkin_faces"],
		"group": "face",
		"slots": {
			"face": "beastkin_face3",
		},
		"tags": ["beastkin"],
	},
	"beastkin_face4": {
		"folders": ["17_beastkin_faces"],
		"group": "face",
		"slots": {
			"face": "beastkin_face4",
		},
		"tags": ["beastkin"],
	},
	"beastkin_face5": {
		"folders": ["17_beastkin_faces"],
		"group": "face",
		"slots": {
			"face": "beastkin_face5",
		},
		"tags": ["beastkin"],
	},
	"beastkin_face6": {
		"folders": ["17_beastkin_faces"],
		"group": "face",
		"slots": {
			"face": "beastkin_face6",
		},
		"tags": ["beastkin"],
		"zones": [0],
	},
	"beastkin_face7": {
		"folders": ["17_beastkin_faces"],
		"group": "face",
		"slots": {
			"face": "beastkin_face7",
		},
		"tags": ["beastkin"],
	},
	"beastkin_face8": {
		"folders": ["17_beastkin_faces"],
		"group": "face",
		"slots": {
			"face": "beastkin_face8",
		},
		"tags": ["beastkin"],
	},
	"beastkin_face_m1": {
		"folders": ["17_beastkin_faces"],
		"group": "face",
		"slots": {
			"face": "beastkin_face_m1",
		},
		"tags": ["beastkin"],
	},
	"beastkin_face_m2": {
		"folders": ["17_beastkin_faces"],
		"group": "face",
		"slots": {
			"face": "beastkin_face_m2",
		},
		"tags": ["beastkin"],
	},
	"beastkin_face_m3": {
		"folders": ["17_beastkin_faces"],
		"group": "face",
		"slots": {
			"face": "beastkin_face_m3",
		},
		"tags": ["beastkin"],
	},
	"beastkin_face_m4": {
		"folders": ["17_beastkin_faces"],
		"group": "face",
		"slots": {
			"face": "beastkin_face_m4",
		},
		"tags": ["beastkin"],
	},
	"beastkin_face_m5": {
		"folders": ["17_beastkin_faces"],
		"group": "face",
		"slots": {
			"face": "beastkin_face_m5",
		},
		"tags": ["beastkin"],
	},
	"beastkin_lips_cry": {
		"folders": ["17_beastkin_lips"],
		"group": "lips",
		"slots": {
			"lips": "beastkin_lips_cry",
		},
		"tags": ["beastkin"],
	},
	"beastkin_lips_open": {
		"folders": ["17_beastkin_lips"],
		"group": "lips",
		"slots": {
			"lips": "beastkin_lips_open__body_female_beastkin",
		},
		"tags": ["beastkin"],
	},
	"beastkin_lips_smile": {
		"folders": ["17_beastkin_lips"],
		"group": "lips",
		"slots": {
			"lips": "beastkin_lips_smile",
		},
		"tags": ["beastkin"],
	},
	"body_male_base": {
		"display": "Male base body",
		"folders": ["01_body_nude_male"],
		"group": "body",
		"slots": {
			"arm_left": "arml1_m",
			"arm_right": "armr1_m",
			"hand_left": {
				"axis": "hand_pose",
				"options": {
					"1": "handl1_m",
					"2": "handl2_m",
				},
			},
			"hand_right": {
				"axis": "hand_pose",
				"options": {
					"1": "handr1_m",
					"2": "handr2_m",
				},
			},
			"leg_left": "legl_m",
			"leg_right": "legr_m",
			"nipples": "nipples_m",
			"pelvis": "pelvis_m",
			"shoulder_left": "shoulderl_m",
			"shoulder_right": "shoulderr_m",
			"torso": "torso_m",
		},
		"zones": [0, 1],
	},
	"body_male_beastkin": {
		"display": "Male beastkin body",
		"folders": ["15_beastkin_body_nude_male"],
		"group": "body",
		"slots": {
			"arm_left": "arml1_beastkin_m",
			"arm_right": "armr1_beastkin_m",
			"hand_left": {
				"axis": "hand_pose",
				"options": {
					"1": "handl1_beastkin_m",
					"2": "beastkin_handl2_m",
				},
			},
			"hand_right": {
				"axis": "hand_pose",
				"options": {
					"1": "handr1_beastkin_m",
					"2": "beastkin_handr2_m",
				},
			},
			"leg_left": "legl_beastkin_m",
			"leg_right": "legr_bestkin_m",
			"nipples": "nipples_beastkin_m",
			"pelvis": "pelvis_beastkin_m",
			"shoulder_left": "shoulderl_beastkin_m",
			"shoulder_right": "shoulderr_beastkin_m",
			"torso": "torso_bestkin_m",
		},
		"tags": ["beastkin"],
		"zones": [0, 1, 2],
	},
	"body_male_femboy": {
		"display": "Male femboy body",
		"folders": ["01_body_nude_male_femboy"],
		"group": "body",
		"slots": {
			"arm_left": "arml1_fb",
			"arm_right": "armr1_fb",
			"hand_left": {
				"axis": "hand_pose",
				"options": {
					"1": "handl1_fb",
					"2": "variant_2",
				},
			},
			"hand_right": {
				"axis": "hand_pose",
				"options": {
					"1": "handr1_fb",
					"2": "variant_2",
				},
			},
			"leg_left": "legl_m",
			"leg_right": "legr_m",
			"nipples": "nipples_m",
			"pelvis": "pelvis_fb",
			"shoulder_left": "shoulderl_fb",
			"shoulder_right": "shoulderr_fb",
			"torso": "torso_fb",
		},
		"zones": [0, 1],
	},
	"braid": {
		"folders": ["05_hairs_assist"],
		"group": "hair_assist",
		"slots": {
			"hairs_assist": "braid",
		},
		"zones": [0, 1],
	},
	"bun": {
		"folders": ["05_hairs_assist"],
		"group": "hair_assist",
		"slots": {
			"hairs_assist": "bun",
		},
	},
	"collar_bell_big": {
		"folders": ["126_armory_acces_collars_male"],
		"group": "collar",
		"slots": {
			"equip_collar": "collar_bell_big",
		},
		"zones": [0, 1],
	},
	"collar_bell_small": {
		"folders": ["126_armory_acces_collars_male"],
		"group": "collar",
		"slots": {
			"equip_collar": "collar_bell_small",
		},
		"zones": [0, 1],
	},
	"collar_heart_big": {
		"folders": ["126_armory_acces_collars_male"],
		"group": "collar",
		"slots": {
			"equip_collar": "collar_heart_big",
		},
		"zones": [0, 1],
	},
	"collar_heart_small": {
		"folders": ["126_armory_acces_collars_male"],
		"group": "collar",
		"slots": {
			"equip_collar": "collar_heart_small",
		},
		"zones": [0, 1],
	},
	"collar_leather_big": {
		"folders": ["126_armory_acces_collars_male"],
		"group": "collar",
		"slots": {
			"equip_collar": "collar_leather_big",
		},
		"zones": [0, 1],
	},
	"collar_leather_small": {
		"folders": ["126_armory_acces_collars_male"],
		"group": "collar",
		"slots": {
			"equip_collar": "collar_leather_small",
		},
		"zones": [0, 1],
	},
	"collar_metallic_big": {
		"folders": ["126_armory_acces_collars_male"],
		"group": "collar",
		"slots": {
			"equip_collar": "collar_metallic_big",
		},
		"zones": [0, 1],
	},
	"collar_metallic_small": {
		"folders": ["126_armory_acces_collars_male"],
		"group": "collar",
		"slots": {
			"equip_collar": "collar_metallic_small",
		},
		"zones": [0, 1],
	},
	"collar_steel_big": {
		"folders": ["126_armory_acces_collars_male"],
		"group": "collar",
		"slots": {
			"equip_collar": "collar_steel_big",
		},
		"zones": [0],
	},
	"collar_steel_small": {
		"folders": ["126_armory_acces_collars_male"],
		"group": "collar",
		"slots": {
			"equip_collar": "collar_steel_small",
		},
		"zones": [0],
	},
	"ears_cat": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_cat",
		},
		"zones": [1],
	},
	"ears_elven": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_elven",
		},
	},
	"ears_fox": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_fox",
		},
		"zones": [1],
	},
	"ears_goblin": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_goblin",
		},
	},
	"ears_human": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_human",
		},
	},
	"ears_mouse": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_mouse",
		},
		"zones": [1],
	},
	"ears_nereid": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_nereid",
		},
	},
	"ears_orc": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_orc",
		},
	},
	"ears_rabbit": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_rabbit",
		},
		"zones": [1],
	},
	"ears_rabbit2": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_rabbit2",
		},
	},
	"ears_rabbit3": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_rabbit3",
		},
		"zones": [1],
	},
	"ears_tanuk": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_tanuk",
		},
		"zones": [1],
	},
	"ears_taurus": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_taurus",
		},
		"zones": [1],
	},
	"ears_wolf": {
		"folders": ["03_ears"],
		"group": "ears",
		"slots": {
			"ears": "ears_wolf",
		},
		"zones": [1],
	},
	"eyebrows1": {
		"folders": ["11_eyebrows"],
		"group": "eyebrows",
		"slots": {
			"eyebrows": "eyebrows1",
		},
	},
	"eyebrows2": {
		"folders": ["11_eyebrows"],
		"group": "eyebrows",
		"slots": {
			"eyebrows": "eyebrows2",
		},
	},
	"eyebrows3": {
		"folders": ["11_eyebrows"],
		"group": "eyebrows",
		"slots": {
			"eyebrows": "eyebrows3",
		},
	},
	"eyebrows4": {
		"folders": ["11_eyebrows"],
		"group": "eyebrows",
		"slots": {
			"eyebrows": "eyebrows4",
		},
	},
	"eyebrows5": {
		"folders": ["11_eyebrows"],
		"group": "eyebrows",
		"slots": {
			"eyebrows": "eyebrows5",
		},
	},
	"eyebrows_m1": {
		"folders": ["11_eyebrows"],
		"group": "eyebrows",
		"slots": {
			"eyebrows": "eyebrows_m1",
		},
	},
	"eyebrows_m2": {
		"folders": ["11_eyebrows"],
		"group": "eyebrows",
		"slots": {
			"eyebrows": "eyebrows_m2",
		},
	},
	"eyebrows_m3": {
		"folders": ["11_eyebrows"],
		"group": "eyebrows",
		"slots": {
			"eyebrows": "eyebrows_m3",
		},
	},
	"eyes1": {
		"folders": ["10_eyes"],
		"group": "eyes",
		"slots": {
			"eyes": "eyes1",
		},
	},
	"eyes2": {
		"folders": ["10_eyes"],
		"group": "eyes",
		"slots": {
			"eyes": "eyes2",
		},
	},
	"eyes3": {
		"folders": ["10_eyes"],
		"group": "eyes",
		"slots": {
			"eyes": "eyes3",
		},
	},
	"eyes4": {
		"folders": ["10_eyes"],
		"group": "eyes",
		"slots": {
			"eyes": "eyes4",
		},
	},
	"eyes5": {
		"folders": ["10_eyes"],
		"group": "eyes",
		"slots": {
			"eyes": "eyes5",
		},
	},
	"eyes_m1": {
		"folders": ["10_eyes"],
		"group": "eyes",
		"slots": {
			"eyes": "eyes_m1",
		},
	},
	"eyes_m2": {
		"folders": ["10_eyes"],
		"group": "eyes",
		"slots": {
			"eyes": "eyes_m2",
		},
	},
	"eyes_m3": {
		"folders": ["10_eyes"],
		"group": "eyes",
		"slots": {
			"eyes": "eyes_m3",
		},
	},
	"eyes_m4": {
		"folders": ["10_eyes"],
		"group": "eyes",
		"slots": {
			"eyes": "eyes_m4",
		},
	},
	"eyes_m5": {
		"folders": ["10_eyes"],
		"group": "eyes",
		"slots": {
			"eyes": "eyes_m5",
		},
	},
	"face1": {
		"folders": ["02_faces"],
		"group": "face",
		"slots": {
			"face": "face1",
		},
	},
	"face2": {
		"folders": ["02_faces"],
		"group": "face",
		"slots": {
			"face": "face2",
		},
	},
	"face3": {
		"folders": ["02_faces"],
		"group": "face",
		"slots": {
			"face": "face3",
		},
	},
	"face4": {
		"folders": ["02_faces"],
		"group": "face",
		"slots": {
			"face": "face4",
		},
	},
	"face5": {
		"folders": ["02_faces"],
		"group": "face",
		"slots": {
			"face": "face5",
		},
	},
	"face6": {
		"folders": ["02_faces"],
		"group": "face",
		"slots": {
			"face": "face6",
		},
	},
	"face7": {
		"folders": ["02_faces"],
		"group": "face",
		"slots": {
			"face": "face7",
		},
	},
	"face8": {
		"folders": ["02_faces"],
		"group": "face",
		"slots": {
			"face": "face8",
		},
	},
	"face_m1": {
		"folders": ["02_faces"],
		"group": "face",
		"slots": {
			"face": "face_m1",
		},
	},
	"face_m2": {
		"folders": ["02_faces"],
		"group": "face",
		"slots": {
			"face": "face_m2",
		},
	},
	"face_m3": {
		"folders": ["02_faces"],
		"group": "face",
		"slots": {
			"face": "face_m3",
		},
	},
	"face_m4": {
		"folders": ["02_faces"],
		"group": "face",
		"slots": {
			"face": "face_m4",
		},
	},
	"face_m5": {
		"folders": ["02_faces"],
		"group": "face",
		"slots": {
			"face": "face_m5",
		},
	},
	"facemask1": {
		"folders": ["25_head_masks"],
		"group": "mask",
		"slots": {
			"equip_masks": "facemask1",
		},
		"zones": [0, 1],
	},
	"facemask2": {
		"folders": ["25_head_masks"],
		"group": "mask",
		"slots": {
			"equip_masks": "facemask2",
		},
		"zones": [0],
	},
	"hair_armor_maid": {
		"folders": ["99_armory_set_maidu"],
		"group": "headgear",
		"slots": {
			"equip_head": "hair_armor_maid",
		},
	},
	"hair_armor_playboy": {
		"folders": ["112_armory_set_playboy_female"],
		"group": "headgear",
		"slots": {
			"equip_head": "hair_armor_playboy",
		},
		"zones": [0],
	},
	"hair_armor_waitress": {
		"folders": ["109_armory_set_waitress_female"],
		"group": "headgear",
		"slots": {
			"equip_head": "hair_armor_waitress",
		},
		"zones": [0, 1],
	},
	"hair_assist_braid": {
		"folders": ["05_hairs_assist"],
		"group": "hair_assist",
		"slots": {
			"hairs_assist": "hair_assist_braid",
		},
		"zones": [0, 1],
	},
	"hair_assist_bun": {
		"folders": ["05_hairs_assist"],
		"group": "hair_assist",
		"slots": {
			"hairs_assist": "hair_assist_bun",
		},
	},
	"hair_assist_pigtails": {
		"folders": ["05_hairs_assist"],
		"group": "hair_assist",
		"slots": {
			"hairs_assist": "hair_assist_pigtails",
		},
	},
	"hair_assist_ponytail": {
		"folders": ["05_hairs_assist"],
		"group": "hair_assist",
		"slots": {
			"hairs_assist": "hair_assist_ponytail",
		},
		"zones": [0, 1],
	},
	"hair_assist_twin_tails": {
		"folders": ["05_hairs_assist"],
		"group": "hair_assist",
		"slots": {
			"hairs_assist": "hair_assist_twin_tails",
		},
	},
	"hair_assist_twin_tails_2": {
		"folders": ["05_hairs_assist"],
		"group": "hair_assist",
		"slots": {
			"hairs_assist": "hair_assist_twin_tails 2",
		},
	},
	"hair_back_care": {
		"folders": ["06_hairs_back"],
		"group": "hair_back",
		"slots": {
			"hairs_back": "hair_back_care",
		},
	},
	"hair_back_dishevel": {
		"folders": ["06_hairs_back"],
		"group": "hair_back",
		"slots": {
			"hairs_back": "hair_back_dishevel",
		},
	},
	"hair_back_double_tail_long": {
		"folders": ["06_hairs_back"],
		"group": "hair_back",
		"slots": {
			"hairs_back": "hair_back_double_tail_long",
		},
		"zones": [1],
	},
	"hair_back_ponytail_long": {
		"folders": ["06_hairs_back"],
		"group": "hair_back",
		"slots": {
			"hairs_back": "hair_back_ponytail_long",
		},
		"zones": [0, 1],
	},
	"hair_back_spiral": {
		"folders": ["06_hairs_back"],
		"group": "hair_back",
		"slots": {
			"hairs_back": "hair_back_spiral",
		},
	},
	"hair_back_straight": {
		"folders": ["06_hairs_back"],
		"group": "hair_back",
		"slots": {
			"hairs_back": "hair_back_straight",
		},
		"zones": [0],
	},
	"hair_back_twin_braids": {
		"folders": ["06_hairs_back"],
		"group": "hair_back",
		"slots": {
			"hairs_back": "hair_back_twin braids",
		},
	},
	"hair_back_verylong1": {
		"folders": ["06_hairs_back"],
		"group": "hair_back",
		"slots": {
			"hairs_back": "hair_back_verylong1",
		},
	},
	"hair_back_wawe": {
		"folders": ["06_hairs_back"],
		"group": "hair_back",
		"slots": {
			"hairs_back": "hair_back_wawe",
		},
	},
	"hair_base_back": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hair_base_back",
			"hairs_fringe": "hair_fringe_back",
		},
		"zones": [0],
	},
	"hair_base_braids": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hair_base_braids",
			"hairs_fringe": "hair_fringe_braids",
		},
		"zones": [0],
	},
	"hair_base_default": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hair_base_default",
			"hairs_fringe": "hair_fringe_default",
		},
		"zones": [0, 1],
	},
	"hair_base_dopple": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hair_base_dopple",
			"hairs_fringe": "hairs_fringe_dopple",
		},
	},
	"hair_base_fringe": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hair_base_fringe",
			"hairs_fringe": "hair_fringe_fringe",
		},
	},
	"hair_base_fringe_2": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hair_base_fringe 2",
		},
		"zones": [0, 1],
	},
	"hair_base_irokez": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hair_base_irokez",
			"hairs_fringe": "hairs_fringe_irokez",
		},
	},
	"hair_base_kare": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hair_base_kare",
			"hairs_fringe": "hair_fringe_kare",
		},
		"zones": [0],
	},
	"hair_base_lamb": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hair_base_lamb",
			"hairs_fringe": "hair_fringe_lamb",
		},
	},
	"hair_base_parting": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hair_base_parting",
			"hairs_fringe": "hairs_fringe_parting",
		},
	},
	"hair_base_slave": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hair_base_slave",
			"hairs_fringe": "hairs_fringe_slave",
		},
	},
	"hair_base_straight": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hair_base_straight",
			"hairs_fringe": "hair_fringe_straight",
		},
		"zones": [0],
	},
	"hair_base_undercut": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hair_base_undercut",
			"hairs_fringe": "hairs_fringe_undercut",
		},
	},
	"hairs_base_dopple": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hairs_base_dopple",
			"hairs_fringe": "hairs_fringe_dopple",
		},
	},
	"hairs_base_irokez": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hairs_base_irokez",
			"hairs_fringe": "hairs_fringe_irokez",
		},
	},
	"hairs_base_lion": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hairs_base_lion",
			"hairs_fringe": "hairs_fringe_lion",
		},
		"zones": [1],
	},
	"hairs_base_parting": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hairs_base_parting",
			"hairs_fringe": "hairs_fringe_parting",
		},
	},
	"hairs_base_slave": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hairs_base_slave",
			"hairs_fringe": "hairs_fringe_slave",
		},
	},
	"hairs_base_undercut": {
		"folders": ["04_hairs_base"],
		"group": "hair",
		"slots": {
			"hairs_base": "hairs_base_undercut",
			"hairs_fringe": "hairs_fringe_undercut",
		},
	},
	"head_chin_curve": {
		"display": "Chin: curved",
		"folders": ["01_heads"],
		"group": "head",
		"slots": {
			"head": "head_chin_curve",
			"head_skull": "head_skull",
		},
	},
	"head_chin_curve_kobold": {
		"display": "Chin: curved kobold",
		"folders": ["01_heads"],
		"group": "head",
		"slots": {
			"head": "head_chin_curve_kobold",
			"head_skull": "head_skull",
		},
	},
	"head_chin_default": {
		"display": "Chin: default",
		"folders": ["01_heads"],
		"group": "head",
		"slots": {
			"head": "head_chin_default",
			"head_skull": "head_skull",
		},
	},
	"head_chin_kobold2": {
		"display": "Chin: kobold 2",
		"folders": ["01_heads"],
		"group": "head",
		"slots": {
			"head": "head_chin_kobold2",
			"head_skull": "head_skull",
		},
	},
	"head_chin_loli": {
		"display": "Chin: loli",
		"folders": ["01_heads"],
		"group": "head",
		"slots": {
			"head": "head_chin_small_curve",
			"head_skull": "head_skull",
		},
	},
	"head_chin_long_skinny": {
		"display": "Chin: long skinny",
		"folders": ["01_heads"],
		"group": "head",
		"slots": {
			"head": "head_chin_long_skinny",
			"head_skull": "head_skull",
		},
	},
	"head_chin_male": {
		"display": "Chin: male",
		"folders": ["01_heads"],
		"group": "head",
		"slots": {
			"head": "head_chin_male",
			"head_skull": "head_skull",
		},
	},
	"head_chin_muscle": {
		"display": "Chin: muscular",
		"folders": ["01_heads"],
		"group": "head",
		"slots": {
			"head": "head_chin_muscle",
			"head_skull": "head_skull",
		},
	},
	"head_chin_short": {
		"display": "Chin: short",
		"folders": ["01_heads"],
		"group": "head",
		"slots": {
			"head": "head_chin_short",
			"head_skull": "head_skull",
		},
	},
	"head_chin_small": {
		"display": "Chin: small",
		"folders": ["01_heads"],
		"group": "head",
		"slots": {
			"head": "head_chin_small",
			"head_skull": "head_skull",
		},
	},
	"head_m_dragon": {
		"display": "Dragon cheek scales",
		"folders": ["23_dragon_male"],
		"group": "face_markings",
		"slots": {
			"race_head": "head_m_dragon",
		},
	},
	"head_m_dragon2": {
		"display": "Dragon cheek scales 2",
		"folders": ["23_dragon_male"],
		"group": "face_markings",
		"slots": {
			"race_head": "head_m_dragon2",
		},
	},
	"horn_curve_down": {
		"folders": ["08_horns"],
		"group": "horns",
		"slots": {
			"horns": "horn_curve_down",
		},
	},
	"horn_curve_top": {
		"folders": ["08_horns"],
		"group": "horns",
		"slots": {
			"horns": "horn_curve_top",
		},
	},
	"horn_curve_up": {
		"folders": ["08_horns"],
		"group": "horns",
		"slots": {
			"horns": "horn_curve_up",
		},
	},
	"horn_dragon2": {
		"folders": ["08_horns"],
		"group": "horns",
		"slots": {
			"horns": "horn_dragon2",
		},
	},
	"horn_seraph_fibule": {
		"folders": ["08_horns"],
		"group": "horns",
		"slots": {
			"horns": "horn_seraph_fibule",
		},
	},
	"horn_spiral_2": {
		"folders": ["08_horns"],
		"group": "horns",
		"slots": {
			"horns": "horn_spiral 2",
		},
	},
	"kentaur_body": {
		"folders": ["14_animals_body"],
		"group": "animal_body",
		"hides": [
			"leg_left",
			"leg_right",
			"equip_leg_left",
			"equip_leg_right",
			"race_leg_left",
			"race_leg_right",
		],
		"slots": {
			"animal_body": "kentaur_body",
		},
	},
	"kobold_head_kobold": {
		"display": "Kobold spots",
		"folders": ["24_kobold_female"],
		"group": "face_markings",
		"slots": {
			"race_head": "kobold_head_kobold",
		},
	},
	"kobold_head_mask1": {
		"display": "Kobold cheek plates",
		"folders": ["24_kobold_female"],
		"group": "face_markings",
		"slots": {
			"race_head": "kobold_head_mask1",
		},
	},
	"lamia_body": {
		"folders": ["14_animals_body"],
		"group": "animal_body",
		"hides": [
			"leg_left",
			"leg_right",
			"equip_leg_left",
			"equip_leg_right",
			"race_leg_left",
			"race_leg_right",
		],
		"slots": {
			"animal_body": "lamia_body",
		},
	},
	"lips1": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips1",
		},
	},
	"lips2": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips2",
		},
	},
	"lips3": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips3",
		},
	},
	"lips4": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips4",
		},
	},
	"lips5": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips5",
		},
	},
	"lips_beast": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips_beast__body_female_beastkin",
		},
	},
	"lips_m1": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips_m1",
		},
	},
	"lips_m2": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips_m2",
		},
	},
	"lips_m3": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips_m3",
		},
	},
	"lips_m4": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips_m4",
		},
	},
	"lips_orc": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips_orc",
		},
	},
	"lips_orc_1": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips_orc 1",
		},
	},
	"lips_orc_2": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips_orc 2",
		},
	},
	"lips_orc_3": {
		"folders": ["12_lips"],
		"group": "lips",
		"slots": {
			"lips": "lips_orc 3",
		},
	},
	"nose_default": {
		"folders": ["03_noses"],
		"group": "nose",
		"slots": {
			"noses": "nose_default",
		},
	},
	"nose_dwarf": {
		"folders": ["03_noses"],
		"group": "nose",
		"slots": {
			"noses": "nose_dwarf",
		},
	},
	"nose_kobold": {
		"folders": ["03_noses"],
		"group": "nose",
		"slots": {
			"noses": "nose_kobold",
		},
	},
	"nose_kobold_2": {
		"folders": ["03_noses"],
		"group": "nose",
		"slots": {
			"noses": "nose_kobold_2",
		},
	},
	"nose_small": {
		"folders": ["03_noses"],
		"group": "nose",
		"slots": {
			"noses": "nose_small",
		},
	},
	"nose_straight": {
		"folders": ["03_noses"],
		"group": "nose",
		"slots": {
			"noses": "nose_straight",
		},
	},
	"outfit_cloth": {
		"display": "Cloth set",
		"folders": ["121_armory_set_cloth_male"],
		"group": "outfit",
		"slots": {
			"equip_back": "equip_back",
			"equip_leg_left": "legl_armor_cloth",
			"equip_leg_right": "legr_armor_cloth",
			"equip_pelvis": "pelvis_armor_cloth",
			"equip_shoulder_left": "shoulderl_armor_cloth",
			"equip_shoulder_right": "shoulderr_armor_cloth",
			"equip_torso": "torso_armor_cloth",
		},
		"zones": [0, 1, 2],
	},
	"outfit_cloth2": {
		"display": "Cloth set 2",
		"folders": ["121_armory_set_cloth2_male"],
		"group": "outfit",
		"slots": {
			"equip_arm_left": "arml1_armor_cloth2",
			"equip_arm_right": "armr1_armor_cloth2",
			"equip_back": "raincoat_cloth2",
			"equip_leg_left": "legl_armor_cloth2",
			"equip_leg_right": "legr_armor_cloth2",
			"equip_pelvis": "pelvis_armor_coth2",
			"equip_shoulder_left": "shoulderl_armor_cloth2",
			"equip_shoulder_right": "shoulderr_armor_cloth2",
			"equip_torso": "torso_armor_cloth2",
		},
		"zones": [0, 1, 2],
	},
	"outfit_cloth3": {
		"display": "Cloth set 3",
		"folders": ["121_armory_set_cloth_male"],
		"group": "outfit",
		"slots": {
			"equip_back": "equip_back",
			"equip_leg_left": "legl_armor_cloth",
			"equip_leg_right": "legr_armor_cloth",
			"equip_pelvis": "pelvis_armor_cloth",
			"equip_shoulder_left": "shoulderl_armor_cloth",
			"equip_shoulder_right": "shoulderr_armor_cloth",
			"equip_torso": "torso_armor_cloth3",
		},
		"zones": [0, 1, 2],
	},
	"outfit_jacket": {
		"display": "Jacket set",
		"folders": ["125_armory_set_jacket_male"],
		"group": "outfit",
		"slots": {
			"equip_leg_left": "legr_armor_jacket",
			"equip_leg_right": "legl_armor_jacket",
			"equip_pelvis": "pelvis_armor_m_jacket",
			"equip_torso": "torso_armor_m_jacket",
		},
		"zones": [0, 1],
	},
	"outfit_latex": {
		"display": "Latex set",
		"folders": ["124_armory_set_latex_male"],
		"group": "outfit",
		"slots": {
			"equip_arm_left": "arml1_armor_latex",
			"equip_arm_right": "armr1_armor_latex",
			"equip_hand_left": {
				"axis": "hand_pose",
				"options": {
					"1": "handl1_m_latex",
					"2": "handl2_m_latex",
				},
			},
			"equip_hand_right": {
				"axis": "hand_pose",
				"options": {
					"1": "handr1_armor_latex",
					"2": "handr2_armor_latex",
				},
			},
			"equip_leg_left": "legl_armor_latex",
			"equip_leg_right": "legr_armor_latex",
			"equip_pelvis": "pelvis_armor_latex",
			"equip_shoulder_left": "shoulderl_armor_latex",
			"equip_shoulder_right": "shoulderr_armor_latex",
			"equip_torso": {
				"axis": "body_shape",
				"options": {
					"femboy": "torso_armor_fb_latex",
					"male": "torso_armor_m_latex",
				},
			},
		},
		"zones": [0, 1],
	},
	"outfit_latex2": {
		"display": "Latex set (slim cut)",
		"folders": ["124_armory_set_latex_male"],
		"group": "outfit",
		"slots": {
			"equip_arm_left": "arml1_armor_latex2",
			"equip_arm_right": "armr1_armor_latex2",
			"equip_hand_left": {
				"axis": "hand_pose",
				"options": {
					"1": "handl1_m_latex",
					"2": "handl2_m_latex",
				},
			},
			"equip_hand_right": {
				"axis": "hand_pose",
				"options": {
					"1": "handr1_armor_latex",
					"2": "handr2_armor_latex",
				},
			},
			"equip_leg_left": "legl_armor_latex",
			"equip_leg_right": "legr_armor_latex",
			"equip_pelvis": "pelvis_armor_latex",
			"equip_shoulder_left": "shoulderl_armor_latex2",
			"equip_shoulder_right": "shoulderr_armor_latex2",
			"equip_torso": "torso_armor_latex",
		},
		"zones": [0, 1],
	},
	"outfit_leather": {
		"display": "Leather set",
		"folders": ["122_armory_set_leather_male"],
		"group": "outfit",
		"slots": {
			"equip_arm_left": "arml1_armor_leather",
			"equip_arm_right": "armr1_armor_leather",
			"equip_back": "raincoat_cloth2__122_armory_set_leather_male",
			"equip_hand_left": {
				"axis": "hand_pose",
				"options": {
					"1": "handl1_armor_leather",
					"2": "handl2_armor_leather",
				},
			},
			"equip_hand_right": {
				"axis": "hand_pose",
				"options": {
					"1": "handr1_armor_leather",
					"2": "handr2_armor_leather",
				},
			},
			"equip_leg_left": "legl_armor_leather",
			"equip_leg_right": "legr_armor_leather",
			"equip_pelvis": "pelvis_armor_leather",
			"equip_shoulder_left": "shoulderl_armor_leather",
			"equip_shoulder_right": "shoulderr_armor_leather",
			"equip_torso": "torso_armor_leather",
		},
		"zones": [0, 1, 2],
	},
	"outfit_leather2": {
		"display": "Leather set 2",
		"folders": ["122_armory_set_leather2_male"],
		"group": "outfit",
		"slots": {
			"equip_arm_left": "arml1_armor_leather2",
			"equip_arm_right": "armr1_armor_leather2",
			"equip_back": "raincoat_leather2",
			"equip_leg_left": "legl_armor_leather2",
			"equip_leg_right": "legr_armor_leather2",
			"equip_pelvis": "pelvis_armor_leather2",
			"equip_shoulder_left": "shoulderl_armor_leather2",
			"equip_shoulder_right": "shoulderr_armor_leather2",
			"equip_torso": "torso_armor_leather2",
		},
		"zones": [0, 1, 2],
	},
	"outfit_plate": {
		"display": "Plate set",
		"folders": ["123_armory_set_plate_male"],
		"group": "outfit",
		"slots": {
			"equip_arm_left": "arml1_armor_plate",
			"equip_arm_right": "armr1_armor_plate",
			"equip_back": "raincoat_cloth2__123_armory_set_plate_male",
			"equip_hand_left": {
				"axis": "hand_pose",
				"options": {
					"1": "handl1_armor_plate",
					"2": "handl2_armor_plate",
				},
			},
			"equip_hand_right": {
				"axis": "hand_pose",
				"options": {
					"1": "handr1_armor_plate",
					"2": "handr2_armor_plate",
				},
			},
			"equip_leg_left": "legl_armor_plate",
			"equip_leg_right": "legr_armor_plate",
			"equip_pelvis": "pelvis_armor_plate2",
			"equip_shoulder_left": "shoulderl_armor_plate",
			"equip_shoulder_right": "shoulderr_armor_plate",
			"equip_torso": "torso_armor_plate2",
		},
		"zones": [0, 1, 2],
	},
	"outfit_plate2": {
		"display": "Plate set 2",
		"folders": ["123_armory_set_plate2_male"],
		"group": "outfit",
		"slots": {
			"equip_arm_left": "arml1_armor_plate2",
			"equip_arm_right": "armr1_armor_plate2",
			"equip_back": "raincoat_plate2",
			"equip_leg_left": "legl_armor_plate2",
			"equip_leg_right": "legr_armor_plate2",
			"equip_pelvis": "pelvis_armor_plate3",
			"equip_shoulder_left": "shoulderl_armor_plate3",
			"equip_shoulder_right": "shoulderr_armor_plate3",
			"equip_torso": "torso_armor_plate3",
		},
		"zones": [0, 1, 2],
	},
	"outfit_servant": {
		"display": "Servant set",
		"folders": ["100_armory_set_servant_male"],
		"group": "outfit",
		"slots": {
			"equip_arm_left": "arml1_armor_m1",
			"equip_arm_right": "armr1_armor_m1",
			"equip_leg_left": "legl_armor_m1",
			"equip_leg_right": "legr_armor_m1",
			"equip_pelvis": "pelvis_armor_m1",
			"equip_shoulder_left": "shoulderl_armor_m1",
			"equip_shoulder_right": "shoulderr_armor_m1",
			"equip_torso": "torso_armor_m1",
		},
		"zones": [0, 1],
	},
	"outfit_slave": {
		"display": "Slave set",
		"folders": ["104_armory_set_slave_male"],
		"group": "outfit",
		"slots": {
			"equip_leg_left": "legl_armor_slave",
			"equip_leg_right": "legr_armor_slave",
			"equip_pelvis": "pelvis_armor_slave",
		},
		"zones": [0],
	},
	"outfit_smith": {
		"display": "Smith set",
		"folders": ["123_armory_set_smith_male"],
		"group": "outfit",
		"slots": {
			"equip_arm_left": "arml1_armor_smith",
			"equip_arm_right": "armr1_armor_smith",
			"equip_leg_left": "legl_armor_smith",
			"equip_leg_right": "legr_armor_smith",
			"equip_pelvis": "pelvis_armor_m_smith",
			"equip_torso": "torso_armor_m_smith",
		},
		"zones": [0, 1],
	},
	"outfit_tentacle": {
		"display": "Tentacle set",
		"folders": ["125_armory_set_tentackle_male"],
		"group": "outfit",
		"slots": {
			"equip_pelvis": "pelvis_armor_tentackle",
			"equip_torso": {
				"axis": "body_shape",
				"options": {
					"femboy": "torso_armor_fb_tentacke",
					"male": "torso_armor_m_tentacke",
				},
			},
		},
		"zones": [0, 1],
	},
	"outfit_waiter": {
		"display": "Waiter set",
		"folders": ["124_armory_set_waiter_male"],
		"group": "outfit",
		"slots": {
			"equip_arm_left": "arml1_armor_waiter",
			"equip_arm_right": "armr1_armor_waiter",
			"equip_hand_left": "handl1_armor_waiter",
			"equip_hand_right": "handr1_armor_waiter",
			"equip_leg_left": "legl_armor_waiter",
			"equip_leg_right": "legr_armor_waiter",
			"equip_pelvis": "pelvis_armor_m_waiter",
			"equip_shoulder_left": "soulderl_armor_waiter",
			"equip_shoulder_right": "soulderr_armor_waiter",
			"equip_torso": "torso_armor_m_waiter",
		},
		"zones": [0, 1],
	},
	"pigtails": {
		"folders": ["05_hairs_assist"],
		"group": "hair_assist",
		"slots": {
			"hairs_assist": "pigtails",
		},
	},
	"ponytail": {
		"folders": ["05_hairs_assist"],
		"group": "hair_assist",
		"slots": {
			"hairs_assist": "ponytail",
		},
	},
	"ponytail_2": {
		"folders": ["05_hairs_assist"],
		"group": "hair_assist",
		"slots": {
			"hairs_assist": "ponytail_2",
		},
	},
	"ponytail_3": {
		"folders": ["05_hairs_assist"],
		"group": "hair_assist",
		"slots": {
			"hairs_assist": "ponytail_3",
		},
	},
	"race_dragon": {
		"display": "Dragon",
		"folders": ["23_dragon_female", "23_dragon_male"],
		"group": "race_overlay",
		"slots": {
			"race_arm_left": "arml1_dragon",
			"race_arm_right": "armr1_dragon",
			"race_leg_left": "legl_m_dragon",
			"race_leg_right": "legr_m_dragon",
			"race_pelvis": "dragon_pelvis_m",
			"race_shoulder_left": "shoulderl_m_dragon",
			"race_shoulder_right": "shoulderr_m_dragon",
			"race_torso": "dragon_torso_m",
			"race_torso_lower": "dragon_torso_m2",
		},
		"zones": [1],
	},
	"race_dragon_scales": {
		"display": "Dragon (scales)",
		"folders": ["23_dragon_female", "23_dragon_male"],
		"group": "race_overlay",
		"slots": {
			"race_arm_left": "arml1_dragon",
			"race_arm_right": "armr1_dragon",
			"race_leg_left": "legl_m_dragon2",
			"race_leg_right": "legr_m_dragon2",
			"race_pelvis": "dragon_pelvis_m",
			"race_shoulder_left": "shoulderl_m_dragon",
			"race_shoulder_right": "shoulderr_m_dragon",
			"race_torso": "dragon_torso_m3",
			"race_torso_lower": "dragon_torso_m2",
		},
		"zones": [0, 1],
	},
	"race_dragon_scales2": {
		"display": "Dragon (scales 2)",
		"folders": ["23_dragon_female", "23_dragon_male"],
		"group": "race_overlay",
		"slots": {
			"race_arm_left": "arml1_dragon",
			"race_arm_right": "armr1_dragon",
			"race_leg_left": "legl_m_dragon",
			"race_leg_right": "legr_m_dragon",
			"race_pelvis": "dragon_pelvis_m",
			"race_shoulder_left": "shoulderl_m_dragon",
			"race_shoulder_right": "shoulderr_m_dragon",
			"race_torso": "dragon_body3",
			"race_torso_lower": "dragon_torso_m2",
		},
		"zones": [1],
	},
	"race_dryad": {
		"display": "Dryad",
		"folders": ["20_dryad"],
		"group": "race_overlay",
		"slots": {
			"race_leg_right": "dryad_legr",
			"race_shoulder_left": "dryad_shoulderl",
			"race_shoulder_right": "dryad_shoulderr",
			"race_torso": "dryad_body",
		},
		"zones": [0, 1],
	},
	"race_kobold": {
		"display": "Kobold",
		"folders": ["24_kobold_female"],
		"group": "race_overlay",
		"slots": {
			"race_arm_left": "kobold_arml1",
			"race_leg_left": "kobold_legl",
			"race_leg_right": "kobold_legr",
			"race_shoulder_left": "kobold_shoulderl1",
			"race_shoulder_right": "kobold_shoulderr1",
			"race_torso": "kobold_body1_1",
			"race_torso_lower": "kobold_body2_1",
		},
		"zones": [0, 1],
	},
	"race_kobold_spots": {
		"display": "Kobold (spots)",
		"folders": ["24_kobold_female"],
		"group": "race_overlay",
		"slots": {
			"race_arm_left": "kobold_arml2",
			"race_arm_right": "kobold_armr2",
			"race_leg_left": "kobold_legl2",
			"race_leg_right": "kobold_legr2",
			"race_pelvis": "kobold_pelvis2",
			"race_shoulder_left": "kobold_shoulderl2",
			"race_shoulder_right": "kobold_shoulderr2",
			"race_torso": "kobold_body1_2",
			"race_torso_lower": "kobold_body2_2",
		},
	},
	"race_nereid": {
		"display": "Nereid",
		"folders": ["21_nereid"],
		"group": "race_overlay",
		"slots": {
			"race_arm_left": "nereid_arml",
			"race_arm_right": "nereid_armr",
			"race_leg_left": "nereid_legl",
			"race_leg_right": "nereid_legr",
		},
	},
	"race_slime": {
		"display": "Slime",
		"folders": ["22_slime"],
		"group": "race_overlay",
		"slots": {
			"race_arm_left": "slime_arml",
			"race_arm_right": "slime_armr",
			"race_leg_left": "slime_legl",
			"race_leg_right": "slime_legr",
			"race_pelvis": "slime_pelvis",
			"race_torso": "slime_body",
		},
	},
	"scylla_body": {
		"folders": ["14_animals_body"],
		"group": "animal_body",
		"hides": [
			"leg_left",
			"leg_right",
			"equip_leg_left",
			"equip_leg_right",
			"race_leg_left",
			"race_leg_right",
		],
		"slots": {
			"animal_body": "scylla_body",
		},
	},
	"tail_cat": {
		"folders": ["07_tails"],
		"group": "tails",
		"slots": {
			"tails": "tail_cat",
		},
		"zones": [0, 1],
	},
	"tail_demon": {
		"folders": ["07_tails"],
		"group": "tails",
		"slots": {
			"tails": "tail_demon",
		},
	},
	"tail_dragon": {
		"folders": ["07_tails"],
		"group": "tails",
		"slots": {
			"tails": "tail_dragon",
		},
		"zones": [0, 2],
	},
	"tail_dragon2": {
		"folders": ["07_tails"],
		"group": "tails",
		"slots": {
			"tails": "tail_dragon2",
		},
	},
	"tail_fox": {
		"folders": ["07_tails"],
		"group": "tails",
		"slots": {
			"tails": "tail_fox",
		},
	},
	"tail_kobold": {
		"folders": ["07_tails"],
		"group": "tails",
		"slots": {
			"tails": "tail_kobold",
		},
	},
	"tail_mouse": {
		"folders": ["07_tails"],
		"group": "tails",
		"slots": {
			"tails": "tail_mouse",
		},
		"zones": [0],
	},
	"tail_nereid": {
		"folders": ["07_tails"],
		"group": "tails",
		"slots": {
			"tails": "tail_nereid",
		},
	},
	"tail_tanuk": {
		"folders": ["07_tails"],
		"group": "tails",
		"slots": {
			"tails": "tail_tanuk",
		},
	},
	"tail_wolf": {
		"folders": ["07_tails"],
		"group": "tails",
		"slots": {
			"tails": "tail_wolf",
		},
	},
	"tatoo_womb1": {
		"folders": ["97_tatoos"],
		"group": "tattoo",
		"slots": {
			"tatoos": "tatoo_womb1",
		},
	},
	"tatoo_womb10": {
		"folders": ["97_tatoos"],
		"group": "tattoo",
		"slots": {
			"tatoos": "tatoo_womb10",
		},
	},
	"tatoo_womb2": {
		"folders": ["97_tatoos"],
		"group": "tattoo",
		"slots": {
			"tatoos": "tatoo_womb2",
		},
	},
	"tatoo_womb3": {
		"folders": ["97_tatoos"],
		"group": "tattoo",
		"slots": {
			"tatoos": "tatoo_womb3",
		},
	},
	"tatoo_womb4": {
		"folders": ["97_tatoos"],
		"group": "tattoo",
		"slots": {
			"tatoos": "tatoo_womb4",
		},
	},
	"tatoo_womb5": {
		"folders": ["97_tatoos"],
		"group": "tattoo",
		"slots": {
			"tatoos": "tatoo_womb5",
		},
	},
	"tatoo_womb6": {
		"folders": ["97_tatoos"],
		"group": "tattoo",
		"slots": {
			"tatoos": "tatoo_womb6",
		},
	},
	"tatoo_womb7": {
		"folders": ["97_tatoos"],
		"group": "tattoo",
		"slots": {
			"tatoos": "tatoo_womb7",
		},
	},
	"tatoo_womb8": {
		"folders": ["97_tatoos"],
		"group": "tattoo",
		"slots": {
			"tatoos": "tatoo_womb8",
		},
	},
	"tatoo_womb9": {
		"folders": ["97_tatoos"],
		"group": "tattoo",
		"slots": {
			"tatoos": "tatoo_womb9",
		},
	},
	"twin_braids": {
		"folders": ["05_hairs_assist"],
		"group": "hair_assist",
		"slots": {
			"hairs_assist": "twin braids",
		},
	},
	"twin_tails": {
		"folders": ["05_hairs_assist"],
		"group": "hair_assist",
		"slots": {
			"hairs_assist": "twin_tails",
		},
	},
	"twin_tails_3": {
		"folders": ["05_hairs_assist"],
		"group": "hair_assist",
		"slots": {
			"hairs_assist": "twin_tails 3",
		},
	},
	"weapon_back_axe1": {
		"folders": ["201_weapon_back"],
		"group": "weapon_back",
		"slots": {
			"weapon_back": "weapon_back_axe1",
		},
		"zones": [0, 1, 2],
	},
	"weapon_back_axe2": {
		"folders": ["201_weapon_back"],
		"group": "weapon_back",
		"slots": {
			"weapon_back": "weapon_back_axe2",
		},
		"zones": [0, 1, 2],
	},
	"weapon_back_bow": {
		"folders": ["201_weapon_back"],
		"group": "weapon_back",
		"slots": {
			"weapon_back": "weapon_back_bow",
		},
		"zones": [0, 1],
	},
	"weapon_back_bow2": {
		"folders": ["201_weapon_back"],
		"group": "weapon_back",
		"slots": {
			"weapon_back": "weapon_back_bow2",
		},
		"zones": [0, 1],
	},
	"weapon_back_crossbow1": {
		"folders": ["201_weapon_back"],
		"group": "weapon_back",
		"slots": {
			"weapon_back": "weapon_back_crossbow1",
		},
		"zones": [0, 1],
	},
	"weapon_back_crossbow2": {
		"folders": ["201_weapon_back"],
		"group": "weapon_back",
		"slots": {
			"weapon_back": "weapon_back_crossbow2",
		},
		"zones": [0, 1, 2],
	},
	"weapon_back_mace2": {
		"folders": ["201_weapon_back"],
		"group": "weapon_back",
		"slots": {
			"weapon_back": "weapon_back_mace2",
		},
		"zones": [0, 1, 2],
	},
	"weapon_back_spear": {
		"folders": ["201_weapon_back"],
		"group": "weapon_back",
		"slots": {
			"weapon_back": "weapon_back_spear",
		},
		"zones": [0, 1, 2],
	},
	"weapon_back_spear2": {
		"folders": ["201_weapon_back"],
		"group": "weapon_back",
		"slots": {
			"weapon_back": "weapon_back_spear2",
		},
		"zones": [0, 1],
	},
	"weapon_back_stick": {
		"folders": ["201_weapon_back"],
		"group": "weapon_back",
		"slots": {
			"weapon_back": "weapon_back_stick",
		},
		"zones": [0, 1],
	},
	"weapon_back_stick2": {
		"folders": ["201_weapon_back"],
		"group": "weapon_back",
		"slots": {
			"weapon_back": "weapon_back_stick2",
		},
		"zones": [0, 1],
	},
	"weapon_belt_bat": {
		"folders": ["200_weapon_belt"],
		"group": "weapon_belt",
		"slots": {
			"weapon_belt": "weapon_belt_bat",
		},
		"zones": [0, 1],
	},
	"weapon_belt_dagger": {
		"folders": ["200_weapon_belt"],
		"group": "weapon_belt",
		"slots": {
			"weapon_belt": "weapon_belt_dagger",
		},
		"zones": [0, 1],
	},
	"weapon_belt_dagger2": {
		"folders": ["200_weapon_belt"],
		"group": "weapon_belt",
		"slots": {
			"weapon_belt": "weapon_belt_dagger2",
		},
		"zones": [0, 1],
	},
	"weapon_belt_mace": {
		"folders": ["200_weapon_belt"],
		"group": "weapon_belt",
		"slots": {
			"weapon_belt": "weapon_belt_mace",
		},
		"zones": [0, 2],
	},
	"weapon_belt_sword": {
		"folders": ["200_weapon_belt"],
		"group": "weapon_belt",
		"slots": {
			"weapon_belt": "weapon_belt_sword",
		},
		"zones": [0, 1],
	},
	"weapon_belt_sword2": {
		"folders": ["200_weapon_belt"],
		"group": "weapon_belt",
		"slots": {
			"weapon_belt": "weapon_belt_sword2",
		},
		"zones": [0, 1],
	},
	"wings_demon": {
		"folders": ["09_wings"],
		"group": "wings",
		"slots": {
			"wings": "wings_demon",
		},
	},
	"wings_harpia": {
		"folders": ["09_wings"],
		"group": "wings",
		"slots": {
			"wings": "wings_harpia",
		},
	},
}

const PRESETS = {
	"arachna": {
		"animal_body": "arachna_body",
	},
	"cat": {
		"ears": "ears_cat",
		"tails": "tail_cat",
	},
	"demon": {
		"horns": "horn_curve_up",
		"tails": "tail_demon",
		"wings": "wings_demon",
	},
	"dragon": {
		"face_markings": "head_m_dragon",
		"horns": "horn_dragon2",
		"race_overlay": "race_dragon",
		"tails": "tail_dragon",
		"wings": "Wings_dragon",
	},
	"dryad": {
		"race_overlay": "race_dryad",
	},
	"elf": {
		"ears": "ears_elven",
	},
	"fairy": {
		"wings": "Wings_fairy",
	},
	"fox": {
		"ears": "ears_fox",
		"tails": "tail_fox",
	},
	"goblin": {
		"ears": "ears_goblin",
	},
	"harpia": {
		"wings": "wings_harpia",
	},
	"kentaur": {
		"animal_body": "kentaur_body",
	},
	"kobold": {
		"face_markings": "kobold_head_kobold",
		"nose": "nose_kobold",
		"race_overlay": "race_kobold",
		"tails": "tail_kobold",
	},
	"lamia": {
		"animal_body": "lamia_body",
	},
	"mouse": {
		"ears": "ears_mouse",
		"tails": "tail_mouse",
	},
	"nereid": {
		"ears": "ears_nereid",
		"race_overlay": "race_nereid",
		"tails": "tail_nereid",
	},
	"orc": {
		"ears": "ears_orc",
		"lips": "lips_orc",
	},
	"rabbit": {
		"ears": "ears_rabbit",
	},
	"scylla": {
		"animal_body": "scylla_body",
	},
	"seraph": {
		"horns": "horn_seraph_fibule",
		"wings": "Wings_seraph",
	},
	"slime": {
		"race_overlay": "race_slime",
	},
	"tanuki": {
		"ears": "ears_tanuk",
		"tails": "tail_tanuk",
	},
	"wolf": {
		"ears": "ears_wolf",
		"tails": "tail_wolf",
	},
}

const ALIASES = {
	"head": {
		"head_chin_curve__scales": "head_chin_curve",
		"head_chin_kobold2__spots": "head_chin_kobold2",
	},
	"horns": {
		"horn_seraph_fibule__seraph": "horn_seraph_fibule",
		"horns": "horn_dragon2",
	},
	"lips": {
		"beastkin_lips_open": "lips_m1",
		"beastkin_lips_smile__2": "beastkin_lips_smile",
		"beastkin_lips_smile__3": "beastkin_lips_smile",
		"beastkin_lips_smile__4": "beastkin_lips_smile",
		"beastkin_lips_smile__5": "beastkin_lips_smile",
		"beastkin_lips_smile__6": "beastkin_lips_smile",
		"beastkin_lips_smile__7": "beastkin_lips_smile",
		"beastkin_lips_smile__body_female_beastkin": "beastkin_lips_smile",
		"lips_beast": "lips_m1",
		"lips_m1__body_female_base": "lips_m1",
	},
	"noses": {
		"nose_kobold_2__spots": "nose_kobold_2",
	},
	"testicle": {
		"testicle_furry__body_female_beastkin": "testicle_furry",
		"testicle_human__body_female_base": "testicle_human",
	},
}

const UNCATEGORIZED = {}

